### DISCUSSION TITLE
Self-hosted error after upgrade 0.56->0.59

### DISCUSSION THREAD

**Discussion by accesstechnology-mike** [outline/outline#2627] [Self Hosting]
1. docker-compose down
2. docker-compose pull (ensuring postgres is version 13 as 14 breaks)
3. yarn db:migrate --env=production-ssl-disabled
3. docker-compose up

reports this error:

outline             | 2021-10-04T15:27:07.832Z server Starting web service
outline             | 2021-10-04T15:27:07.862Z server Starting websockets service
outline             | 2021-10-04T15:27:07.879Z server Starting worker service
outline             | /opt/outline/build/server/index.js:73
outline             |     throw err;
outline             |     ^
outline             |
outline             | Error: bind EACCES null:443
outline             |     at listenOnMasterHandle (net.js:1387:18)
outline             |     at rr (internal/cluster/child.js:138:12)
outline             |     at Worker.<anonymous> (internal/cluster/child.js:105:7)
outline             |     at process.onInternalMessage (internal/cluster/utils.js:48:5)
outline             |     at process.emit (events.js:412:35)
outline             |     at process.emit (domain.js:470:12)
outline             |     at emit (internal/child_process.js:910:12)
outline             |     at processTicksAndRejections (internal/process/task_queues.js:83:21) {
outline             |   errno: -13,
outline             |   code: 'EACCES',
outline             |   syscall: 'bind',
outline             |   address: null,
outline             |   port: 443
outline             | }

**Expected behavior**
Updated version to start

**Outline upgrade from 0.56 to 0.59
- Version: self hosted

**Comment by accesstechnology-mike** [comment]
For reference, this is the docker-compose file, which works perfectly for v 0.56. Only change is adding `:13 `to postgres image

```
version: "3"
services:
  outline_redis:
    image: redis
    container_name: outline_redis
    restart: unless-stopped
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:13
    container_name: outline_postgres
    env_file: ./.env
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - outline-internal
    volumes:
      - ./db:/var/lib/postgresql/data  outline_minio:
    image: minio/minio
    container_name: outline_minio
    volumes:
      - ./data:/data
    env_file: ./.env
    restart: unless-stopped
    networks:
      - caddy
    command: "server /data"
    labels:
      caddy: ${AWS_S3_UPLOAD_BUCKET_URL}
      caddy.reverse_proxy: "{{upstreams 9000}}"
      caddy.reverse_proxy.1_header_up_0: X-Forwarded-Proto {scheme}
      caddy.reverse_proxy.2_header_up_1: X-Forwarded-Host {host}

  outline:
    image: outlinewiki/outline
    container_name: outline
    # set this command instead to initialize/upgrade the db
    # command: sh -c "sleep 5 && yarn sequelize:migrate --env=production-ssl-disabled"
    # command: yarn db:migrate --env=production-ssl-disabled
    command: yarn start --env=production-ssl-disabled
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    env_file: ./.env
    restart: unless-stopped
    labels:
      caddy: ${URL}
      caddy.reverse_proxy: "{{upstreams 443}}"
      caddy.reverse_proxy.1_header_up_0: "X-Forwarded-Proto {scheme}"
      caddy.reverse_proxy.2_header_up_1: "X-Forwarded-Host {host}"
    networks:
      - outline-internal
      - caddy

networks:
  outline-internal:
  caddy:
    external: true
```
