### DISCUSSION TITLE
Oauth behind proxy server

### DISCUSSION THREAD

**Discussion by y-furuta** [outline/outline#2771] [Self Hosting]
I'm running the outline behind a proxy server.
fetch-with-proxy was applied in issue #1893, but it doesn't apply in oauth2, so it seems to time out during slack authentication.
Is there a solution?
```
InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:422:17)
    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (events.js:400:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  oauthError: Error: connect ETIMEDOUT 35.74.58.174:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'connect',
    address: '35.74.58.174',
    port: 443
  }
}
```

**Comment by luguenth** [comment]
I've the same Issue with Google Oauth

**Reply by funkybunch** [reply]
Ever get it working?  I'm running up against this right now.

**Reply by dechristopher** [reply]
Never could fully diagnose the issue unfortunately.

**Comment by tommoor** [comment]
Agreed that this should be fixed, would accept a patch

**Comment by dechristopher** [comment]
I'm having the same issue running outline behind an Nginx reverse proxy that terminates SSL. Can someone explain what's causing this so I can understand?

**Reply by tommoor** [reply]
A reverse proxy acting as SSL termination wouldn't cause this issue, this is more for when there is a proxy between the internal network that Outline is running on and the global internet.

**Reply by dechristopher** [reply]
Strange, though, because I'm getting this exact error although it's being truncated due to JSON logging mode. Is there any way for me to enable full length log messages without flipping development mode on? I'm having some issues when trying to do that and Outline won't finish starting.

**Reply by tommoor** [reply]
> Is there any way for me to enable full length log messages

Honestly there isn't any truncation that I'm aware of, you should see full stack traces in the logs. Are you running from latest docker image?

**Reply by dechristopher** [reply]
I'm running in Kubernetes with the latest image. Here's the manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: prod-wiki
spec:
  type: NodePort
  selector:
    app: prod-wiki
  ports:
    - name: http
      protocol: TCP
      nodePort: 31000
      port: 7777
      targetPort: 8200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-wiki
  template:
    metadata:
      labels:
        app: prod-wiki
    spec:
      containers:
        - name: wiki
          image: outlinewiki/outline:0.60.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8200
              protocol: TCP
          env:
            - name: PORT
              value: "8200"
            - name: URL
              value: "https://wiki.<my domain>"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: secret_key
            - name: UTILS_SECRET
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: utils_secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: db_url
            - name: DATABASE_URL_TEST
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: db_test_url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: redis_url
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: b2_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: b2_secret_access_key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: b2_region
            - name: AWS_S3_UPLOAD_BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: b2_upload_bucket_url
            - name: AWS_S3_UPLOAD_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: b2_upload_bucket_name
            - name: AWS_S3_UPLOAD_MAX_SIZE
              value: "26214400"
            - name: AWS_S3_FORCE_PATH_STYLE
              value: "false"
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: google_client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wiki-env
                  key: google_client_secret
            - name: ENABLE_UPDATES
              value: "true"
            - name: ALLOWED_DOMAINS
              value: "<my domain>"

---
```

Here's the error:
```json
{"error":"Failed to obtain access token","stack":"InternalOAuthError: Failed to obtain access token\n    at Strategy.OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)\n    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45\n    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","level":"error","message":"Error during authentication"}
```
Raw stack trace:
```
InternalOAuthError: Failed to obtain access token
at Strategy.OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)
at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18
at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)
at ClientRequest.emit (events.js:400:28)
at ClientRequest.emit (domain.js:475:12)
at TLSSocket.socketErrorListener (_http_client.js:475:9)
at TLSSocket.emit (events.js:400:28)
at TLSSocket.emit (domain.js:475:12)
at emitErrorNT (internal/streams/destroy.js:106:8)
at emitErrorCloseNT (internal/streams/destroy.js:74:3)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
