### DISCUSSION TITLE
I have build a site use outline with docker, but it was return 504 when login with slack.

### DISCUSSION THREAD

**Discussion by bestbugwriter** [outline/outline#2875] [General]
docker logs -f see logs, it has this exception
```
{"error":"request to https://secure.gravatar.com/avatar/f15d9fabc94561eac11b31a075371232.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-192.png failed, reason: connect ETIMEDOUT 31.13.85.53:443","stack":"FetchError: request to https://secure.gravatar.com/avatar/f15d9fabc94561eac11b31a075371232.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2Fdf10d%2Fimg%2Favatars%2Fava_0026-192.png failed, reason: connect ETIMEDOUT 31.13.85.53:443\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/node-fetch/lib/index.js:1461:11)\n    at ClientRequest.emit (events.js:400:28)\n    at ClientRequest.emit (domain.js:475:12)\n    at TLSSocket.socketErrorListener (_http_client.js:475:9)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket.emit (domain.js:475:12)\n    at emitErrorNT (internal/streams/destroy.js:106:8)\n    at emitErrorCloseNT (internal/streams/destroy.js:74:3)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)","level":"error","message":"Error uploading to S3 from URL"}
```

How to avoid visiting this website `secure.gravatar.com`

and my docker-compose.yml is 
```

version: "3"
services:
  redis:
    image: redis
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: xxx
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
  minio:
    image: minio/minio
    volumes:
      - ./data/minio_root:/minio_root:z
      - ./data/certs:/root/.minio/certs:z
    command: "minio server /minio_root"
    env_file: ./env.minio
    restart: always
  outline:
    image: outlinewiki/outline:latest
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://root:xxx@postgres:5432/outline
      - DATABASE_URL_TEST=postgres://root:xxxx@postgres:5432/outline-test
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./env.outline
      - ./env.slack
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 444:444
    volumes:
      - ./data/nginx:/etc/nginx/conf.d/:z
      - ./data/certs:/etc/nginx/ssl/:z
    restart: always
    depends_on:
      - outline
```
