### DISCUSSION TITLE
CORS error with outline + minio behind traefik as reverse proxy

### DISCUSSION THREAD

**Discussion by OCram85** [outline/outline#3002] [Self Hosting]
Hi, folks!

I managed to get outline running with Gitea as auth-provider. While editing my first pages I tried uploading images and get these errors:

![image](https://user-images.githubusercontent.com/13993700/150935550-f9c17e86-bdde-4337-af67-1c1db1ee0e54.png)

So I tried to add a traefik middleware to manipulate the headers for the outline service:

```yaml
# Set addtional cors header
- "traefik.http.middlewares.testheader.headers.accesscontrolallowmethods=GET,OPTIONS,PUT,POST"
- "traefik.http.middlewares.testheader.headers.accesscontrolalloworiginlist=https://outline.****.net,https://minio.*****.net"
- "traefik.http.middlewares.testheader.headers.accesscontrolmaxage=100"
- "traefik.http.middlewares.testheader.headers.addvaryheader=true"
- "traefik.http.routers.outline.middlewares=testheader@docker"
```

I'm, not quite sure what causes the problem.

**Comment by tommoor** [comment]
The CORS headers would come from Minio, not Outline – I'm not familiar with all the setup for Minio however there is probably a way to configure CORS as part of that service?

**Reply by OCram85** [reply]
Hmm that's strange. I've checket the minio settings. The CORS these are the default settings which should work:

![image](https://user-images.githubusercontent.com/13993700/151114812-635cca2c-a0fa-43cd-bf31-4568eac734b3.png)

**Reply by lenaxia** [reply]
Did you ever figure this out? I'm running into this issue now.

**Comment by OCram85** [comment]
I just solved it this week. 😄
The problem is  related to the mini bucket itself. It seems like the upload to minio objects is done with the credentials. But the access only works if you allow anon acccess to the objects within minio.

**Comment by lenaxia** [comment]
I ran into a different CORS issue, but for completeness, I'll include my write up here for anyone else who stumbles across this

**### CORS Policy Violation**

In web developer tools (F12), when getting a CORS policy violation, check all sources of the request. In this case, Traefik was overwriting the response from MINIO and replacing the referrerPolicy with same-origin preventing cross origin requests. The error looked like this:

```
Access to XMLHttpRequest at 'https://s3.domain.tld/outline-3eyxnvg6' from origin 
'https://w.domain.tld' has been blocked by CORS policy: Response to preflight request 
doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present 
on the requested resource.
```

This required setting up a custom middleware for MINIO that hardcodes the response header. There may be a better way to do it that would pass MINIO’s headers, but this is how I do it for now. The specific headers in question are `accessControlAllowMethods`, `accessControlAllowOriginList`, `accessControllMaxAge`, `addVaryHeader`, `referrerPolicy`.

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middlewares-minio-headers
  namespace: networking
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
    accessControlAllowOriginList:
      - "*"
        #      - https://w.${SECRET_DEV_DOMAIN}
        #      - https://s3.${SECRET_DEV_DOMAIN}
    accessControlMaxAge: 100
    addVaryHeader: true
    stsSeconds: 63072000
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
    forceSTSHeader: true
    # frameDeny: true #overwritten by customFrameOptionsValue
    customFrameOptionsValue: "allow-from https:${SECRET_DEV_DOMAIN}" #CSP takes care of this but may be needed for organizr.
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "origin-when-cross-origin"
      #referrerPolicy: "same-origin"
    # Setting contentSecurityPolicy is more secure but it can break things. Proper auth will reduce the risk.
    # the below line also breaks some apps due to 'none' - sonarr, radarr, etc.
    # contentSecurityPolicy: "frame-ancestors '*.example.com:*';object-src 'none';script-src 'none';"
    permissionsPolicy: "camera 'none'; geolocation 'none'; microphone 'none'; payment 'none'; usb 'none'; vr 'none';"
    customResponseHeaders:
      X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex,"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: chain-no-auth-minio
  namespace: networking
spec:
  chain:
    middlewares:
      - name: middlewares-rate-limit
      - name: middlewares-minio-headers
```
