### DISCUSSION TITLE
DatabaseError [SequelizeDatabaseError]: column "slackData" does not exist

### DISCUSSION THREAD

**Discussion by TheSander562** [outline/outline#3043] [Self Hosting] [answered]
DatabaseError [SequelizeDatabaseError]: column "slackData" does not exist, after latest docker image.
Was working correctly with 0.61.1 but since few days i get this error in log file when opening the website. And it shows white page with nothing.
Also with docker compose i always used yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled
But after the the update it couldnt find db, so i replaced db:migrate with sequelize:migrate. But than i get the databaseError

**To Reproduce**
1. Have a outline instance with database from before few days.
2. Update the image and get the docker compose up
3. Check the error in the log or try to go to the website.

**Expected behavior**
The database should migrate correctly after each updates and no problems occur.

**Error log**
```
DatabaseError [SequelizeDatabaseError]: column "slackData" does not exist
    at Query.formatError (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)
    at Query.run (/opt/outline/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:619:16
    at async PostgresQueryInterface.select (/opt/outline/node_modules/sequelize/lib/dialects/abstract/query-interface.js:938:12)
    at async Function.findAll (/opt/outline/node_modules/sequelize/lib/model.js:1753:21)
    at async /opt/outline/build/server/api/auth.js:74:19
    at async apiWrapperMiddleware (/opt/outline/build/server/api/middlewares/apiWrapper.js:14:5)
    at async errorHandlingMiddleware (/opt/outline/build/server/middlewares/errorHandling.js:17:7)
    at async /opt/outline/node_modules/koa-mount/index.js:58:5
    at async /opt/outline/node_modules/koa-mount/index.js:52:26 {
  parent: error: column "slackData" does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '125',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3504',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "name", "subdomain", "domain", "slackId", "googleId", "avatarUrl", "sharing", "guestSignin", "documentEmbeds", "slackData", "createdAt", "updatedAt", "deletedAt" FROM "teams" AS "team" WHERE ("team"."deletedAt" IS NULL);',
    parameters: undefined
  },
  original: error: column "slackData" does not exist
      at Parser.parseErrorMessage (/opt/outline/node_modules/pg-protocol/dist/parser.js:278:15)
      at Parser.handlePacket (/opt/outline/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:10:42)
      at Socket.emit (events.js:315:20)
      at Socket.EventEmitter.emit (domain.js:467:12)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    length: 110,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: undefined,
    position: '125',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3504',
    routine: 'errorMissingColumn',
    sql: 'SELECT "id", "name", "subdomain", "domain", "slackId", "googleId", "avatarUrl", "sharing", "guestSignin", "documentEmbeds", "slackData", "createdAt", "updatedAt", "deletedAt" FROM "teams" AS "team" WHERE ("team"."deletedAt" IS NULL);',
    parameters: undefined
  },
  sql: 'SELECT "id", "name", "subdomain", "domain", "slackId", "googleId", "avatarUrl", "sharing", "guestSignin", "documentEmbeds", "slackData", "createdAt", "updatedAt", "deletedAt" FROM "teams" AS "team" WHERE ("team"."deletedAt" IS NULL);',
  parameters: undefined
}
```

**Outline:**
- Install: self hosted
- Version: sha256:6f7e4474e1f773af6747a966ae4f64a3c0549b563c5422a96cffda5f9f984c9a

**Desktop:**
 - OS: Windows 11
 - Browser: Edge (Chromium based)
 - Version: 97.0.1072.76

**Current Docker-compose:**
```
version: "3.9"
services:
  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    depends_on:
      outline-postgres:
        condition: service_healthy
      outline-redis:
        condition: service_started
      minio:
        condition: service_started
    env_file: 
      - /secrets/outline.env
    networks:
      - default
      - outline-internal
    labels:
      com.centurylinklabs.watchtower.enable: true
    command: sh -c "yarn sequelize:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    restart: always
  outline-redis:
    image: redis:latest
    container_name: outline-redis
    volumes:
      - /volume1/docker/outline/redis:/data
    networks:
      - outline-internal
    labels:
      com.centurylinklabs.watchtower.enable: true
    restart: always
  outline-postgres:
    image: postgres:13
    container_name: outline-postgres
    env_file: 
      - /secrets/outline.env
    volumes:
      - /volume1/docker/outline/postgresql:/var/lib/postgresql/data
    networks:
      - outline-internal
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outline"]
      interval: 10s
      start_period: 30s
      timeout: 5s
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    env_file: 
      - /secrets/outline.env
    volumes:
      - /volume1/docker/minio:/data
    networks:
      - default
    labels:
      com.centurylinklabs.watchtower.enable: true
    command: "server /data --console-address :9001"
    restart: always

networks:
  outline-internal:
  default:
    external:
      name: apps_network
```
