### DISCUSSION TITLE
Help with docker compose outline

### DISCUSSION THREAD

**Discussion by joezappie** [outline/outline#3224] [Self Hosting]
I'm running outline via a docker-compose script. I accidently ran "docker-compose down" which after rebooting it caused my website to wipe losing all my data. 

I'm pretty new to docker but my understanding is docker-compose down deletes the container, but the volume should persist as I didn't run it with the -v arg.

Checking the logs I can see that after doing a down then up, it causes the postgres migration to rerun. Doing stop/up works fine as the containers don't get deleted.

If the outline container is deleted and recreated, does that somehow trigger the database to reset? Arn't the migrations stored in postgres? Deleting the container should be safe?

My minio container which is in the same docker-compose script persists data between down/up. Checking the volumes, my pg-data volume is still from 12 hours ago set up outline so I don't think the docker is deleting the data.

Anyone have an idea why this is happening? I'm afraid I'll accidently do a "down" in the future and lose all my data when I have more than just a few hours of work in it.

Here is my docker-compose script:

```
version: "3"
services:
  outline-postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: outline
      POSTGRES_PASSWORD: ...
      POSTGRES_USER: outline
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/outline/data

  outline-s3:
    image: minio/minio
    container_name: outline_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=outline
      - MINIO_ROOT_PASSWORD=...
      - MINIO_BROWSER_REDIRECT_URL=...
    command: server --address ":9000" --console-address ":9001" /data

  outline-redis:
    image: redis
    restart: unless-stopped

  outline:
    image: outlinewiki/outline:latest
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start" 
    #command: yarn start
    environment:
      ########## Outline Database
      - DATABASE_URL=postgres://outline:...@outline-postgr$
      - DATABASE_URL_TEST=postgres://outline:...@outline-p$
      - REDIS_URL=redis://outline-redis:6379
      - SECRET_KEY=....
      - UTILS_SECRET=...
      ########## Outline Default URL
      - URL=...
      ########## Outline S3 Provider credentials
      - AWS_ACCESS_KEY_ID=outline
      - AWS_SECRET_ACCESS_KEY=...
      - AWS_REGION=us-east-2
      - AWS_S3_UPLOAD_BUCKET_URL=...
      - AWS_S3_UPLOAD_BUCKET_NAME=outline-wiki
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - PGSSLMODE=disable
      ########## Email Provider
      - SMTP_HOST=smtp.zoho.com
      - SMTP_PORT=465
      - SMTP_USERNAME=...
      - SMTP_PASSWORD=....
      - SMTP_FROM_EMAIL=...
      - SMTP_REPLY_EMAIL=...
      - SMTP_SECURE=true
      ########## Slack Auth
      - SLACK_KEY=...
      - SLACK_SECRET=...
      - SLACK_VERIFICATION_TOKEN=...
      - SLACK_APP_ID=...
    restart: always
    depends_on:
      - outline-postgres
      - outline-redis
    ports:
      - "3000:3000"

networks:
  default:
    name: nginx
    external: true

volumes:
  db-data:
  minio-data:

```
