### DISCUSSION TITLE
Slack Authentication Doesn't work

### DISCUSSION THREAD

**Discussion by navjotjsingh** [outline/outline#3288] [Self Hosting] [answered]
Here is my docker.env file.

```
# –––––––––––––––– REQUIRED ––––––––––––––––

# Generate a hex-encoded 32-byte random key. You should use `openssl rand -hex 32`
# in your terminal to generate a random value.
SECRET_KEY=XXXXXXXXXXXX

# Generate a unique random key. The format is not important but you could still use
# `openssl rand -hex 32` in your terminal to produce this.
UTILS_SECRET=XXXXXXXXXXXX

# Postgres
POSTGRES_USER=outlinepg
POSTGRES_PASSWORD=XXXXXXX
POSTGRES_DB=outline

# For production point these at your databases, in development the default
# should work out of the box.
DATABASE_URL=postgres://outlinepg:XXXXXXX@postgres:5432/outline
DATABASE_URL_TEST=postgres://outlinepg:XXXXXX@postgres:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
# Uncomment this to disable SSL for connecting to Postgres
PGSSLMODE=disable
REDIS_URL=redis://redis:6379

# URL should point to the fully qualified, publicly accessible URL. If using a
# proxy the port in URL and PORT may be different.
URL=http://localhost:3000
PORT=3000

# To support uploading of images for avatars and document attachments an
# s3-compatible storage must be provided. AWS S3 is recommended for redundency
# however if you want to keep all file storage local an alternative such as
# minio (https://github.com/minio/minio) can be used.

# A more detailed guide on setting up S3 is available here:
# => https://wiki.generaloutline.com/share/125de1cc-9ff6-424b-8415-0d58c809a40f
#
AWS_ACCESS_KEY_ID=XXXXXXXXXXXX
AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXX
AWS_REGION=us-west-2
AWS_S3_UPLOAD_BUCKET_URL=https://XXXXXX.s3.us-west-2.amazonaws.com/
AWS_S3_UPLOAD_BUCKET_NAME=XXXXXX
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true

# –––––––––––––– AUTHENTICATION ––––––––––––––

# Third party signin credentials, at least ONE OF EITHER Google, Slack,
# or Microsoft is required for a working installation or you'll have no sign-in
# options.

# To configure Slack auth, you'll need to create an Application at
# => https://api.slack.com/apps
#
# When configuring the Client ID, add a redirect URL under "OAuth & Permissions":
# https://<URL>/auth/slack.callback
SLACK_KEY=XXXXXXXXXXXX
SLACK_SECRET=XXXXXXXXXXXX

# –––––––––––––––– OPTIONAL ––––––––––––––––

# For a complete Slack integration with search and posting to channels the
# following configs are also needed, some more details
# => https://wiki.generaloutline.com/share/be25efd1-b3ef-4450-b8e5-c4a4fc11e02a
#
SLACK_VERIFICATION_TOKEN=XXXXXXXXXXXX
SLACK_APP_ID=XXXXXXXXXXXX
SLACK_MESSAGE_ACTIONS=true

# Auto-redirect to https in production. The default is true but you may set to
# false if you can be sure that SSL is terminated at an external loadbalancer.
FORCE_HTTPS=false

# Have the installation check for updates by sending anonymized statistics to
# the maintainers
ENABLE_UPDATES=true

# How many processes should be spawned. As a reasonable rule divide your servers
# available memory by 512 for a rough estimate
WEB_CONCURRENCY=1

# To support sending outgoing transactional emails such as "document updated" or
# "you've been invited" you'll need to provide authentication for an SMTP server
SMTP_HOST=email-smtp.us-west-2.amazonaws.com
SMTP_PORT=587
SMTP_USERNAME=XXXXXXXXXXXX
SMTP_PASSWORD=XXXXXXXXXXXX
SMTP_FROM_EMAIL=noreply@example.com
SMTP_REPLY_EMAIL=navjot@example.com
SMTP_SECURE=true
```

This is my docker-compose.yml file

```
version: "3"
services:

  outline:
    image: outlinewiki/outline:latest
    restart: always
    env_file: ./docker.env
    command: sh -c "yarn sequelize:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    ports:
      - "3000:3000"
    depends_on:
      - outline_postgres
      - outline_redis

  outline_redis:
    image: redis
    restart: always
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  outline_postgres:
    image: postgres:13
    restart: always
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U outlinepg"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  database-data:
```

As soon as I click the Slack Login button, I get redirected to **http://localhost:3000/auth/slack** thus resulting in an error.

I have double-checked my Slack settings and I have set **https://outline.example.com/auth/slack.callback** as the redirect URL.

Please advise me as to what I am doing wrong?

I am using Nginx as a reverse proxy with Let's Encrypt SSL for the domain https://outline.example.com.
