### DISCUSSION TITLE
Not connecting to redis and postgresql

### DISCUSSION THREAD

**Discussion by VityaSchel** [outline/outline#3291] [Self Hosting]
Someone please help me I'm stuck on this issue for days now

outline_1 logs:

```
Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
```

```
original: Error: connect ECONNREFUSED 127.0.0.1:5432
```

redis is running:
![image](https://user-images.githubusercontent.com/59040542/160276036-89488432-c2b3-43eb-a575-3aada4847cfb.png)

postgresql is running too on 5432 port

docker-compose.yml:

![image](https://user-images.githubusercontent.com/59040542/160276063-8d87000e-d2aa-4dcc-9674-662a4c40d9e3.png)

![image](https://user-images.githubusercontent.com/59040542/160276069-6afde0c9-19b4-4a33-bb09-6083979f4fc0.png)

![image](https://user-images.githubusercontent.com/59040542/160276074-1ab747a9-5e09-42e0-829f-9ef05d07bca5.png)

network type is bridge:
![image](https://user-images.githubusercontent.com/59040542/160276123-0dbc479f-2572-45f3-802a-4305b701b929.png)

i'm lost 😢

**Comment by evgeniy0** [comment]
It seems that sample env file is broken
I had to change redis and postgres urls to point not to 'localhost' but to 'redis' and 'postgres' respectively

**Reply by tommoor** [reply]
By default the docker internal network should be bridged to the localhost

**Reply by evgeniy0** [reply]
In my default ubuntu installation it is not bridged though

**Reply by almereyda** [reply]
While this may work for local development installs that use the `docker-compose.yml` file in the root of this repository, where the ports are explicitly mapped to the local host

https://github.com/outline/outline/blob/096b35e08e9501939d56371001c2dbaa89c3ec22/docker-compose.yml#L5-L6

https://github.com/outline/outline/blob/096b35e08e9501939d56371001c2dbaa89c3ec22/docker-compose.yml#L9-L10

https://github.com/outline/outline/blob/096b35e08e9501939d56371001c2dbaa89c3ec22/docker-compose.yml#L17-L18

this is not the case with production setups that rely on virtual networks created per project in Compose.

In comparison, the setup described in https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t does also use port mappings, but to all available interfaces, where using expose directives with a dedicated network for internal database access and a dedicated frontend proxy could provide more manageability, e.g. on hosts that provide more than one Redis or Postgres service, or do not want to bridge the port 3000 of the application directly.

This is our configuration for running Outline:

```yaml
version: "3"

services:

  outline:
    image: outlinewiki/outline:0.62.0
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - URL=${OUTLINE_URL}
      - COLLABORATION_URL=${COLLABORATION_URL}
      - FORCE_HTTPS=false
      # SSO
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_SCOPES=${OIDC_SCOPES}
      - OIDC_USERNAME_CLAIM=${OIDC_USERNAME_CLAIM}
      - ALLOWED_DOMAINS=${OIDC_ALLOWED_DOMAINS}
      # DB
      - DATABASE_URL=${DATABASE_URL}
      - PGSSLMODE=${PGSSLMODE}
      - REDIS_URL=${REDIS_URL}
      # Secret
      - SECRET_KEY=${OUTLINE_SECRET_KEY}
      - UTILS_SECRET=${OUTLINE_UTILS_SECRET}
      # S3
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_UPLOAD_BUCKET_URL=${AWS_S3_UPLOAD_BUCKET_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=${AWS_S3_UPLOAD_BUCKET_NAME}
      - AWS_S3_UPLOAD_MAX_SIZE=${AWS_S3_UPLOAD_MAX_SIZE}
      - AWS_S3_FORCE_PATH_STYLE=${AWS_S3_FORCE_PATH_STYLE}
      - AWS_S3_ACL=${AWS_S3_ACL}
      # etc.
      - ENABLE_UPDATES=true
      - MAXIMUM_IMPORT_SIZE=5120000
      - DEBUG=cache,presenters,events,emails,mailer,utils,http,server,services
      #- DEBUG=http
      - SLACK_MESSAGE_ACTIONS=false
      - DEFAULT_LANGUAGE=en_US

      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_REPLY_EMAIL=${SMTP_REPLY_EMAIL}
      - SMTP_SECURE=${SMTP_SECURE}

      - TEAM_LOGO=${TEAM_LOGO}

    restart: unless-stopped
    networks:
      - web
      - outline
    labels:
      traefik.enable: true
      traefik.http.routers.com-example.rule: Host(`${DOCKER_OUTLINE_HOSTNAME}`)  
      traefik.http.routers.com-example.tls: true
      traefik.http.routers.com-example.tls.certresolver: le
    extra_hosts:
      - "${DOCKER_OUTLINE_HOSTNAME}:0.0.0.0"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASS}
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/bases/postgres/example.com:/var/lib/postgresql/data
    networks:
      - outline
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DOCKER_POSTGRES_USER}"]
      interval: 3s
      retries: 12
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  redis:
    image: redis:6-alpine
    networks: ["outline"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      retries: 12
    environment:
      TZ: Europe/Berlin
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /data/bases/redis/example.com:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  outline:
  web:
    external: true

```

What we see here is that we explicitly map the variables from `.env` into the containers, as they will be substituted with the values in the file upon container startup.

In our case, the S3 service Minio is hosted in another place and made available through setting the correct credentials through `.env`.
