### DISCUSSION TITLE
Upload image | fail MINIO s3

### DISCUSSION THREAD

**Discussion by wdfxl** [outline/outline#3366] [General]
Hi guys! 
Have a problem with upload image to minio 
Domain with https cert and authorized users from google api
Minio s3 on http

When upload image i view on preview, but after update page nothing image saves(
example
![Screenshot from 2022-04-12 17-44-07](https://user-images.githubusercontent.com/53470505/162989153-e63835ec-3958-47d2-86f1-6d12debc6a22.png)

and error on browser logs
![Screenshot from 2022-04-12 16-29-38](https://user-images.githubusercontent.com/53470505/162989340-1ef5d9b4-3af4-43da-86b6-0a0f85dfeb4e.png)

Also i see error message go to hyperlink:

NoSuchKeyThe specified key does not exist.public/e362957b-4b41-401e-acdc-4883718e2e5b/439be56e-17a9-4fb7-9f9e-348f2c3f2ea4/photo_2022-03-29_12-55-26.jpgoutline-bucket/outline-bucket/public/e362957b-4b41-401e-acdc-4883718e2e5b/439be56e-17a9-4fb7-9f9e-348f2c3f2ea4/photo_2022-03-29_12-55-26.jpg16E52947A744ECF4e394e40b-2455-4dd4-8f79-7311f4c55ea5

**Comment by N4v41** [comment]
in the browser network tab does it show any error in the call to minio endpoint ?

**Reply by s-praveen-kumar** [reply]
I have the same issue. In my case, the image is uploaded to the minio bucket. But strangely, there is an amazonaws url in the network tab with a status 403. Bug or misconfiguration?

**Reply by Nicicalu** [reply]
> I have the same issue. In my case, the image is uploaded to the minio bucket. But strangely, there is an amazonaws url in the network tab with a status 403. Bug or misconfiguration?

Check my newest reply here

**Comment by Limezy** [comment]
You may have more problems here, but as a start, Minio **has to be** on https

**Comment by wdfxl** [comment]
Hi! Done, Download the minio 2021year release.!

**Comment by Nicicalu** [comment]
A few things I picked up along the way of implementing Minio with outline:

1. Using `outline` in the URL or the bucket name can cause it not to work, try changing that.
2. The folder `public` in the bucket needs to be public in order for profile avatars to work. For this, I used the following custom ACL on the bucket:
```
    {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Action": [
                "s3:GetObject",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::my_bucket_name/public/*"
            ]
        }
    ]
}
```
4. Set `AWS_S3_ACCELERATE_URL` to the same as `AWS_S3_UPLOAD_BUCKET_URL` even if not using that.
5. For me it only worked when setting the `AWS_S3_FORCE_PATH_STYLE` to `false` and adding the bucket name to the two URLs:
  ```
  AWS_REGION=eu-east-1
  AWS_S3_ACCELERATE_URL=https://minio.mydomain.com/docs
  AWS_S3_UPLOAD_BUCKET_URL=https://minio.mydomain.com/docs
  AWS_S3_UPLOAD_BUCKET_NAME=docs
  AWS_S3_FORCE_PATH_STYLE=false
  ```

If you have any questions, let me know

**Reply by dmikushin** [reply]
Thanks for implicitly pointing out to the fact that in order for Outline to work, the minio has to be a public service. This fact does not agree with the proposed Docker container setups, which are therefore deemed to fail trying to publicly access http://storage:9000/ or similar URL.

Issue is filled here: https://github.com/outline/outline/issues/5654

**Reply by heyvaldemar** [reply]
hey @Nicicalu, how are you doing?

May I kindly ask for your help with MinIO and Outline?

I still get an error 'Upload Failed' if I try to upload any image.

Here is my code:

`01-traefik-outline-letsencrypt-docker-compose.yml`
```
networks:
  traefik-network:
    external: true

volumes:
  traefik-certificates:

services:
  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-certificates:/etc/traefik/acme
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:8082/ping","--spider"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_HOSTNAME}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.services.dashboard.loadbalancer.passhostheader=true"
      - "traefik.http.routers.dashboard.middlewares=authtraefik"
      - "traefik.http.middlewares.authtraefik.basicauth.users=${TRAEFIK_BASIC_AUTH}"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    restart: unless-stopped
```

`02-keycloak-outline-docker-compose.yml`
```
networks:
  outline-network:
    external: true
  keycloak-network:
    external: true
  traefik-network:
    external: true

volumes:
  keycloak-postgres:

services:
  postgres-keycloak:
    image: ${KEYCLOAK_POSTGRES_IMAGE_TAG}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_DB -d $$POSTGRES_USER -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  keycloak:
    image: ${KEYCLOAK_IMAGE_TAG}
    command: start
    environment:
      KC_DB: ${KEYCLOAK_DB_TYPE}
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOG_LEVEL}
    networks:
      - outline-network
      - keycloak-network
      - traefik-network
    labels:
      - "traefik.enable=true"
      # Keycloak URL
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOSTNAME}`)"
      - "traefik.http.routers.keycloak.service=keycloak"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.passhostheader=true"
      - "traefik.http.routers.keycloak.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      postgres-keycloak:
        condition: service_healthy
```

`03-outline-minio-redis-docker-compose.yml`
```
networks:
  outline-network:
    external: true
  keycloak-network:
    external: true
  traefik-network:
    external: true

volumes:
  minio-data:
  outline-postgres:

services:
  postgres-outline:
    image: ${OUTLINE_POSTGRES_IMAGE_TAG}
    volumes:
      - outline-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${OUTLINE_DB_NAME}
      POSTGRES_USER: ${OUTLINE_DB_USER}
      POSTGRES_PASSWORD: ${OUTLINE_DB_PASSWORD}
    networks:
      - outline-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  redis:
    image: ${OUTLINE_REDIS_IMAGE_TAG}
    networks:
      - outline-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  minio:
    image: ${OUTLINE_MINIO_IMAGE_TAG}
    entrypoint: /bin/sh
    command:
      - -c
      - |
        minio server /data --console-address :9001 &
        sleep 20
        mc config host add minio http://localhost:9000 ${OUTLINE_MINIO_ADMIN} ${OUTLINE_MINIO_ADMIN_PASSWORD}
        mc mb minio/${OUTLINE_MINIO_BUCKET_NAME}
        mc admin user add minio ${OUTLINE_MINIO_USER} ${OUTLINE_MINIO_USER_PASSWORD}
        cat > outline-policy.json <<-EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "s3:GetBucketLocation",
                  "s3:ListBucket",
                  "s3:ListBucketMultipartUploads"
                ],
                "Resource": [
                  "arn:aws:s3:::${OUTLINE_MINIO_BUCKET_NAME}"
                ]
              },
              {
                "Action": [
                  "s3:AbortMultipartUpload",
                  "s3:DeleteObject",
                  "s3:GetObject",
                  "s3:ListMultipartUploadParts",
                  "s3:PutObject",
                  "s3:GetObject"
                ],
                "Effect": "Allow",
                "Resource": [
                  "arn:aws:s3:::${OUTLINE_MINIO_BUCKET_NAME}/*"
                ],
                "Sid": ""
              }
            ]
          }
        EOF
        cat > data-public.json <<-EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                "AWS": [
                  "*"
                ]
              },
                "Action": [
                  "s3:GetObject",
                  "s3:ListMultipartUploadParts"
                ],
                "Resource": [
                  "arn:aws:s3:::data/public/*"
                ]
              }
            ]
          }
        EOF
        mc anonymous set-json data-public.json minio/${OUTLINE_MINIO_BUCKET_NAME}
        mc admin policy create minio OutlineAppFullAccess outline-policy.json
        mc admin policy attach minio OutlineAppFullAccess --user=${OUTLINE_MINIO_USER}
        tail -f /dev/null
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${OUTLINE_MINIO_ADMIN}
      MINIO_ROOT_PASSWORD: ${OUTLINE_MINIO_ADMIN_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: ${OUTLINE_MINIO_CONSOLE_URL}
    networks:
      - outline-network
      - traefik-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio-api.rule=Host(`${OUTLINE_MINIO_CONSOLE_HOSTNAME}`)"
      - "traefik.http.routers.minio-api.service=minio-api"
      - "traefik.http.routers.minio-api.entrypoints=websecure"
      - "traefik.http.services.minio-api.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-api.tls=true"
      - "traefik.http.routers.minio-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio-api.loadbalancer.passhostheader=true"
      - "traefik.http.routers.minio-api.middlewares=compresstraefik"
      - "traefik.http.routers.minio-console.rule=Host(`${OUTLINE_MINIO_CONSOLE_HOSTNAME}`)"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio-console.loadbalancer.passhostheader=true"
      - "traefik.http.routers.minio-console.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped

  outline:
    image: ${OUTLINE_IMAGE_TAG}
    environment:
      DATABASE_URL: postgres://${OUTLINE_DB_USER}:${OUTLINE_DB_PASSWORD}@postgres-outline:5432/${OUTLINE_DB_NAME}?sslmode=disable&connect_timeout=10
      PGSSLMODE: disable
      REDIS_URL: redis://redis:6379
      URL: ${OUTLINE_URL}
      PORT: 3000
      SECRET_KEY: ${OUTLINE_SECRET_KEY}
      UTILS_SECRET: ${OUTLINE_UTILS_SECRET}
      FORCE_HTTPS: 'false'
      ENABLE_UPDATES: 'true'
      AWS_REGION: eu-east-1
      AWS_ACCESS_KEY_ID: ${OUTLINE_MINIO_USER}
      AWS_SECRET_ACCESS_KEY: ${OUTLINE_MINIO_USER_PASSWORD}
      AWS_S3_UPLOAD_BUCKET_URL: ${OUTLINE_AWS_S3_UPLOAD_BUCKET_URL}
      AWS_S3_ACCELERATE_URL: ${OUTLINE_AWS_S3_UPLOAD_BUCKET_URL}
      AWS_S3_UPLOAD_BUCKET_NAME: ${OUTLINE_MINIO_BUCKET_NAME}
      AWS_S3_UPLOAD_MAX_SIZE: ${OUTLINE_AWS_S3_UPLOAD_MAX_SIZE}
      AWS_S3_FORCE_PATH_STYLE: 'false'
      AWS_S3_ACL: private
      OIDC_CLIENT_ID: outline
      OIDC_CLIENT_SECRET: ${OUTLINE_OIDC_CLIENT_SECRET}
      OIDC_AUTH_URI: ${OUTLINE_OIDC_AUTH_URI}
      OIDC_TOKEN_URI: ${OUTLINE_OIDC_TOKEN_URI}
      OIDC_USERINFO_URI: ${OUTLINE_OIDC_USERINFO_URI}
      OIDC_DISPLAY_NAME: ${OUTLINE_OIDC_DISPLAY_NAME}
      OIDC_USERNAME_CLAIM: ${OUTLINE_OIDC_USERNAME_CLAIM}
      OIDC_SCOPES: ${OUTLINE_OIDC_SCOPES}
    networks:
      - outline-network
      - keycloak-network
      - traefik-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.rule=Host(`${OUTLINE_HOSTNAME}`)"
      - "traefik.http.routers.outline.service=outline"
      - "traefik.http.routers.outline.entrypoints=websecure"
      - "traefik.http.services.outline.loadbalancer.server.port=3000"
      - "traefik.http.routers.outline.tls=true"
      - "traefik.http.routers.outline.tls.certresolver=letsencrypt"
      - "traefik.http.services.outline.loadbalancer.passhostheader=true"
      - "traefik.http.routers.outline.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik-network"
    restart: unless-stopped
    depends_on:
      postgres-outline:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
```

`.env`
```
# Traefik Variables
TRAEFIK_IMAGE_TAG=traefik:2.9
TRAEFIK_LOG_LEVEL=WARN
TRAEFIK_ACME_EMAIL=callvaldemar@gmail.com
# Traefik URL
TRAEFIK_HOSTNAME=traefik.outline.heyvaldemar.net
# Basic Authentication for Traefik Dashboard
# Username: traefikadmin
# Passwords must be encoded using MD5, SHA1, or BCrypt https://hostingcanada.org/htpasswd-generator/
TRAEFIK_BASIC_AUTH=traefikadmin:$$2y$$10$$sMzJfirKC75x/hVpiINeZOiSm.Jkity9cn4KwNkRvO7hSQVFc5FLO

# Keycloak Variables
KEYCLOAK_POSTGRES_IMAGE_TAG=postgres:14
KEYCLOAK_IMAGE_TAG=quay.io/keycloak/keycloak:22.0
KEYCLOAK_DB_TYPE=postgres
KEYCLOAK_DB_NAME=keycloakdb
KEYCLOAK_DB_USER=keycloakdbuser
KEYCLOAK_DB_PASSWORD=EqhvLbsPhrkkZjcaGWcV7qT
KEYCLOAK_ADMIN_USERNAME=keycloakadmin
KEYCLOAK_ADMIN_PASSWORD=rwXPqspCABJzqh47i723wf9
KEYCLOAK_HOSTNAME=keycloak.outline.heyvaldemar.net
KEYCLOAK_LOG_LEVEL=WARN

# Outline Variables
OUTLINE_POSTGRES_IMAGE_TAG=postgres:14
OUTLINE_IMAGE_TAG=outlinewiki/outline:0.70.2
OUTLINE_REDIS_IMAGE_TAG=redis:7.0
OUTLINE_MINIO_IMAGE_TAG=minio/minio:RELEASE.2023-08-04T17-40-21Z
OUTLINE_DB_NAME=outlinedb
OUTLINE_DB_USER=outlinedbuser
OUTLINE_DB_PASSWORD=wkhuneTBF3F5gMUrtDaKs9Xe
# Outline URL
OUTLINE_URL=https://wiki.heyvaldemar.net
# Outline hostname
OUTLINE_HOSTNAME=wiki.heyvaldemar.net
OUTLINE_MINIO_ADMIN=minioadmin
OUTLINE_MINIO_ADMIN_PASSWORD=2MsqJ7KpUrmEe8Y5LmWL
OUTLINE_MINIO_USER=bucket.data
OUTLINE_MINIO_USER_PASSWORD=fK9Xr5auseJC8ByE6Lk7
OUTLINE_MINIO_BUCKET_NAME=data
# MiniIO API hostname
OUTLINE_MINIO_HOSTNAME=minio.heyvaldemar.net
# MiniIO console URL
OUTLINE_MINIO_CONSOLE_URL=https://console.minio.heyvaldemar.net
# MiniIO console hostname
OUTLINE_MINIO_CONSOLE_HOSTNAME=console.minio.heyvaldemar.net
# Secret key
# It can be generated with the command:
# openssl rand -hex 32
OUTLINE_SECRET_KEY=00703eaa1fedbb92d903c439feac11e4268c76f6eecc097ba6cc714431b5cb08
# Utils secret
# It can be generated with the command:
# openssl rand -hex 32
OUTLINE_UTILS_SECRET=7eee2571836979d3724f9900a55b1291aa3cdfbc32c42056aacfaaa5b9978649
OUTLINE_AWS_S3_UPLOAD_BUCKET_URL=https://minio.heyvaldemar.net/data
OUTLINE_AWS_S3_UPLOAD_MAX_SIZE=26214400
# Keycloak realm secret
# You need to specify it before starting the Outline container
# It can be found in your realm manage section. Clients/YourClient/Credentials.
OUTLINE_OIDC_CLIENT_SECRET=6fVdywHiRwQbgTecgiG9TbIat0lGSnIU
# Authentication endpoints
# It can be found in your realm configure section. Realm Settings/General/Endpoints.
# Example: https://keycloak.outline.heyvaldemar.net/realms/outline/.well-known/openid-configuration
OUTLINE_OIDC_AUTH_URI=https://keycloak.outline.heyvaldemar.net/realms/outline/protocol/openid-connect/auth
# It can be found in your realm configure section. Realm Settings/General/Endpoints.
# Example: https://keycloak.outline.heyvaldemar.net/realms/outline/.well-known/openid-configuration
OUTLINE_OIDC_TOKEN_URI=https://keycloak.outline.heyvaldemar.net/realms/outline/protocol/openid-connect/token
# It can be found in your realm configure section. Realm Settings/General/Endpoints.
# Example: https://keycloak.outline.heyvaldemar.net/realms/outline/.well-known/openid-configuration
OUTLINE_OIDC_USERINFO_URI=https://keycloak.outline.heyvaldemar.net/realms/outline/protocol/openid-connect/userinfo
OUTLINE_OIDC_DISPLAY_NAME=Keycloak
OUTLINE_OIDC_USERNAME_CLAIM=email
OUTLINE_OIDC_SCOPES=openid profile email
```
