### DISCUSSION TITLE
Can't upload image. Found error "Validation isIn on acl failed (acl)"

### DISCUSSION THREAD

**Discussion by Knight52** [outline/outline#3436] [Self Hosting]
When users try to use /image tag, they get an error "Sorry, an error occured uploading an image". Attaching to the Docker's process says it got 400 Bad Request error. When I look on the client side, I found the responding json file contains the error "Validation isIn on acl failed (acl)". Google doesn't seem to have anything related to this project.

The setup is not perfect. I'm still running Outline on http port 3000 right now, with 4 MinIO containers and a Postgres and a Redis container. 

How do I solve this issue? Thanks in advance.

**Comment by almereyda** [comment]
This sounds like an error with the Minio connection and configuration. Can you provide us with your `docker-compose.yml` and a redacted `.env` file?

A similar error had been reported here earlier at #1907 and #3062. There the solution is to set `AWS_S3_ACL=public-read`. Would this work for you?

Another example for a working Minio setup was also described by me in https://github.com/outline/outline/discussions/3281#discussioncomment-2430516

Please also note that the Outline container and the Minio container both need to be exposed to the host system. And that due to browser security implications, both need to be available through the same scheme.

**Reply by Knight52** [reply]
> This sounds like an error with the Minio connection and configuration. Can you provide us with your `docker-compose.yml` and a redacted `.env` file?
> 
> A similar error had been reported here earlier at #1907 and #3062. There the solution is to set `AWS_S3_ACL=public-read`. Would this work for you?
> 
> Another example for a working Minio setup was also described by me in [#3281 (comment)](https://github.com/outline/outline/discussions/3281#discussioncomment-2430516)
> 
> Please also note that the Outline container and the Minio container both need to be exposed to the host system. And that due to browser security implications, both need to be available through the same scheme.

That sort of works.. Now it shows a different error

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<local ip address>:9001/buckets/outline-bucket

Now I know what caused it, but I don't the proper way to add the local ip address to the allowed list, and I don't want to expose the MinIO to the internet either.

Here's the docker-compose-yml files I use. I'm still messing around so I haven't merged those files into one just yet. As for the outline itself, I use the docker command.

`sudo docker run -d -p “<new port>:3000” –env-file=.env –name “outline” outlinewiki/outline`

I hope these help. Thanks.

[outline-env.txt](https://github.com/outline/outline/files/8552875/outline-env.txt)
[outline-compose-1.txt](https://github.com/outline/outline/files/8552876/outline-compose-1.txt)
[outline-compose-2.txt](https://github.com/outline/outline/files/8552877/outline-compose-2.txt)

**Reply by tommoor** [reply]
Files are uploaded from the browser -> Minio so it needs to be exposed to the same degree as Outline. It also needs a proper domain name to support SSL.

**Reply by Knight52** [reply]
> Files are uploaded from the browser -> Minio so it needs to be exposed to the same degree as Outline. It also needs a proper domain name to support SSL.

Hey, sorry this took a while.

I've made it so minio is at https://minio.site.com and outline is at https://outline.site.com. Both are still in the same docker, but redirected via OPNSense. I've also edited the .env file accordingly too.

But I still can't upload the image. It says:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://minio.site.com/buckets/outline-bucket.

Please help me with this. Thanks.

**Reply by N4v41** [reply]
Hi @Knight52  I was seeing your env file and noticed that the minio port that you are using is 9001 if i'm not wrong thats the webadmin port, i've a test enviroment using minio with the following env vars:
```
AWS_ACCESS_KEY_ID=accesskey
AWS_SECRET_ACCESS_KEY=secret
AWS_REGION=local
AWS_S3_UPLOAD_BUCKET_URL=http://localhost:9000
AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
AWS_S3_UPLOAD_MAX_SIZE=26214400
```
and that's the docker compose minio service:
```
  storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=accesskey
      - MINIO_ROOT_PASSWORD=secret
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storage:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```
