### DISCUSSION TITLE
MINIO Setup with Docker Compose

### DISCUSSION THREAD

**Discussion by dominikgeimer** [outline/outline#3437] [Self Hosting] [answered]
Hey,

I followed the instructions to set up outline with docker compose and docker.env file. It works without any problem.

https://app.getoutline.com/share/770a97da-13e5-401e-9f8a-37949c19f97e/doc/docker-7pfeLP5a8t

But the MINIO Container is always stopped after docker-compose up and I don't know what to put into my docker.env to use that MINIO Container.

Can anyone give me a hint?

**Comment by almereyda** [comment]
Can you paste the logs from the Minio container, e.g. is there an error reported that might hint at why it's stopping?

**Reply by rromanchuk** [reply]
@almereyda  it's just constantly restarting, but the `exit 1` logs are literally just the -h flag to STDOUT. Vanilla setup. 

```
outline-outline-1   | {"label":"http","level":"info","message":"  --> GET / 200 12ms 1.11kb"}
outline-storage-1   | NAME:
outline-storage-1   |   minio server - start object storage server
outline-storage-1   | 
outline-storage-1   | USAGE:
outline-storage-1   |   minio server [FLAGS] DIR1 [DIR2..]
outline-storage-1   |   minio server [FLAGS] DIR{1...64}
outline-storage-1   |   minio server [FLAGS] DIR{1...64} DIR{65...128}
outline-storage-1   | 
outline-storage-1   | DIR:
outline-storage-1   |   DIR points to a directory on a filesystem. When you want to combine
outline-storage-1   |   multiple drives into a single large system, pass one directory per
outline-storage-1   |   filesystem separated by space. You may also use a '...' convention
outline-storage-1   |   to abbreviate the directory arguments. Remote directories in a
outline-storage-1   |   distributed setup are encoded as HTTP(s) URIs.
outline-storage-1   | 
outline-storage-1   | FLAGS:
outline-storage-1   |   --address value              bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname (default: ":9000") [$MINIO_ADDRESS]
outline-storage-1   |   --listeners value            bind N number of listeners per ADDRESS:PORT (default: 1) [$MINIO_LISTENERS]
outline-storage-1   |   --console-address value      bind to a specific ADDRESS:PORT for embedded Console UI, ADDRESS can be an IP or hostname [$MINIO_CONSOLE_ADDRESS]
outline-storage-1   |   --certs-dir value, -S value  path to certs directory (default: "/root/.minio/certs")
outline-storage-1   |   --quiet                      disable startup and info messages
outline-storage-1   |   --anonymous                  hide sensitive information from logging
outline-storage-1   |   --json                       output logs in JSON format
outline-storage-1   |   --help, -h                   show help
outline-storage-1   |   
outline-storage-1   | EXAMPLES:
outline-storage-1   |   1. Start minio server on "/home/shared" directory.
outline-storage-1   |      $ minio server /home/shared
outline-storage-1   | 
outline-storage-1   |   2. Start single node server with 64 local drives "/mnt/data1" to "/mnt/data64".
outline-storage-1   |      $ minio server /mnt/data{1...64}
outline-storage-1   | 
outline-storage-1   |   3. Start distributed minio server on an 32 node setup with 32 drives each, run following command on all the nodes
outline-storage-1   |      $ export MINIO_ROOT_USER=minio
outline-storage-1   |      $ export MINIO_ROOT_PASSWORD=miniostorage
outline-storage-1   |      $ minio server http://node{1...32}.example.com/mnt/export{1...32}
outline-storage-1   | 
outline-storage-1   |   4. Start distributed minio server in an expanded setup, run the following command on all the nodes
outline-storage-1   |      $ export MINIO_ROOT_USER=minio
outline-storage-1   |      $ export MINIO_ROOT_PASSWORD=miniostorage
outline-storage-1   |      $ minio server http://node{1...16}.example.com/mnt/export{1...32} \
outline-storage-1   |             http://node{17...64}.example.com/mnt/export{1...64}
outline-storage-1 exited with code 1
outline-outline-1   | {"label":"http","level":"info","message":"  <-- GET /"}
outline-outline-1   | {"label":"http","level":"info","message":"  --> GET / 200 12ms 1.11kb"}
outline-outline-1   | {"label":"http","level":"info","message":"  <-- GET /"}
outline-outline-1   | {"label":"http","level":"info","message":"  --> GET / 200 14ms 1.11kb"}
outline-outline-1   | {"label":"http","level":"info","message":"  <-- GET /"}
outline-outline-1   | {"label":"http","level":"info","message":"  --> GET / 200 11ms 1.11kb"}
outline-outline-1   | {"label":"http","level":"info","message":"  <-- GET /"}
outline-outline-1   | {"label":"http","level":"info","message":"  --> GET / 200 9ms 1.11kb"}
outline-storage-1   | NAME:
outline-storage-1   |   minio server - start object storage server
outline-storage-1   | 
outline-storage-1   | USAGE:
outline-storage-1   |   minio server [FLAGS] DIR1 [DIR2..]
outline-storage-1   |   minio server [FLAGS] DIR{1...64}
```

**Comment by N4v41** [comment, marked as answer]
I use this to test new versions in my desktop:
```yaml
version: "3"
services:

  outline:
    image: outlinewiki/outline:0.63.0
    env_file: ./docker.env
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis

  postgres:
    image: postgres
    #env_file: ./docker.env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=outline
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U outline"]
      interval: 30s
      timeout: 20s
      retries: 3

  storage:
    image: minio/minio
    #env_file: ./docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=<access-key>
      - MINIO_ROOT_PASSWORD=<secret-key>
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storage:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3


volumes:
  storage-data:
  database-data:
```
S3 variables:
```
AWS_ACCESS_KEY_ID=<access-key>
AWS_SECRET_ACCESS_KEY=<secret-key>
AWS_REGION=local
#AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=http://localhost:9000
AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
AWS_S3_UPLOAD_MAX_SIZE=26214400
#AWS_S3_FORCE_PATH_STYLE=true
#AWS_S3_ACL=private
```
