### DISCUSSION TITLE
DATABASE_URL does not work

### DISCUSSION THREAD

**Discussion by Halllo5** [outline/outline#3595] [Self Hosting] [answered]
I have a problem with selfohsting outline in a docker environment.
The outline container produces the following log.

```
yarn run v1.22.18
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".

ERROR: connect ECONNREFUSED 172.18.0.8:5432
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here we can see that outline is trying to connect to a postgressDB on IP `172.18.0.8` (IP of the Docker container).
Although in the .env the ( DATABASE_URL=`postgres://outline:pw@172.23.0.3:5432/outline`
And so the container keeps restarting and repeating the request to the wrong address.
Below I have added my `docker-compose.yml`
I apologize if this is a stupid question but I could not find anything online.

```yml
version: "2"
services:
  outline_redis:
    image: redis
    restart: always
    container_name: outline_redis
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:13
    restart: always
    container_name: outline_postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    networks:
      - outline-internal
    volumes:
      - /mnt/containers/outline/container-data/db:/var/lib/postgresql/data:Z

  outline_minio:
    image: minio/minio
    restart: always
    container_name: outline_minio
    volumes:
      - /mnt/containers/outline/container-data/data:/data:Z
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    ports:
       - 9000:9000
       - 9001:9001
    networks:
      - nginx-proxy-manager_default
    command: "server /data --console-address :9001"

  outline:
    image: outlinewiki/outline
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn sequelize:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@172.23.0.3:5432/outline
      - REDIS_URL=redis://outline_redis:6379
      - URL=${WIKI_URL}
      - PORT=444
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - OIDC_CLIENT_ID=outline-data
      - OIDC_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - OIDC_AUTH_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/auth
      - OIDC_TOKEN_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/token
      - OIDC_USERINFO_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/userinfo
      - OIDC_USERNAME_CLAIM=email
      - OIDC_DISPLAY_NAME=Keycloak
      - OIDC_SCOPES=email
    ports:
       - 444:444
    networks:
      - outline-internal
      - nginx-proxy-manager_default

networks:
  outline-internal:
  nginx-proxy-manager_default:
    external: true
```

**Comment by almereyda** [comment, marked as answer]
Hi! I've spotted little incongruencies in the above, which might help identify the cause of error.

First it connects to an IP that is `172.18.0.8`:

```
Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".

ERROR: connect ECONNREFUSED 172.18.0.8:5432
```

Second something completely different, `172.23.0.3` is defined in the `DATABASE_URL` string:

          - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@172.23.0.3:5432/outline

Can you try replacing that IP with `outline-postgres`, which Docker in return resolves internally to the appropriate IP of the `outline-postres` container on the `outline-internal` network?

**Reply by Halllo5** [reply]
Unfortunatly i didnt work

I first chaged the docker-compose file to only feature one network `outline-internal` i thougt it may not work if the container is in multiple networks.

Also i change as you sugestet the IP with `outline-postgres` wich also didnt work. After that i tried replacing it with `outline_postgres` wich also didnt work.

Now it is jut tring to access `172.23.0.5` the IP of the docker container `outline` in the network `outline-internal` instead of `172.23.0.4` wich would be the IP of the container `outline_postgres` . Down i added the new error message and the Info for the network `outline-internal`

```bash
yarn run v1.22.18
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".

ERROR: connect ECONNREFUSED 172.23.0.5:5432

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Containers in network `outline-internal`

| Container Name | IPv4 Address | MacAddress |
| --- | --- | --- |
| outline_minio | 172.23.0.2/16 | 02:42:ac:17:00:02 |
| outline_postgres | 172.23.0.3/16 | 02:42:ac:17:00:03 |
| outline_redis | 172.23.0.4/16 | 02:42:ac:17:00:04 |
| outline | 172.23.0.5/16 | 02:42:ac:17:00:05 |

Even if it didnt work yet thank you for your help

**Reply by tommoor** [reply]
Don't you need to expose the port in the compose file?

**Reply by almereyda** [reply]
Ah, now I see! At first you tried to put the IP of the Postgres container directly. And sorry, my bad. I didn't read carefully enough. Of course it should be `outline_postgres`.

Do you have anything else running on that system, which might block certain network connections, like those within a Docker network? Maybe something's off the limits in `iptables`, or there's an additional firewall running.

But as of your list, `172.23.0.4` should be the `outline_redis` container, and not `outline_postgres`.

Also, when using your `nginx-proxy-manager`, is there a specific reason why you expose port `444` via the host system to the outside world?

Let's step back a little and test things bit by bit for connectivity, before we make any assumptions. Could you test if you can reach the Postgres container from your Outline service at all? You should be able to run `docker-compose exec -u root outline ping -c 1 outline_postgres` and receive a positive result.

Here is the output from my instance:

```
$ docker-compose exec -u root outline ping -c 1 postgres
PING postgres (192.168.112.4): 56 data bytes
64 bytes from 192.168.112.4: seq=0 ttl=64 time=0.127 ms

--- postgres ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.127/0.127/0.127 ms

```

If this is not the case, something is wrong with the internal DNS of your Docker networking setup. I'd suggest to first check there before drawing any more conclusions.

If that works, we can also check if another Postgres (client) container can successfully talk to the database via the Docker network:

```
$ docker-compose run --rm postgres sh -c 'psql postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB} -c "\dt"'
Creating wikiwikiexamplecom_postgres_run ... done
                  List of relations
 Schema |           Name           | Type  |  Owner  
--------+--------------------------+-------+---------
 public | SequelizeMeta            | table | outline
 public | apiKeys                  | table | outline
 public | attachments              | table | outline
 public | authentication_providers | table | outline
 public | authentications          | table | outline
 public | backlinks                | table | outline
 public | collection_groups        | table | outline
 public | collection_users         | table | outline
 public | collections              | table | outline
 public | documents                | table | outline
 public | events                   | table | outline
 public | file_operations          | table | outline
 public | group_users              | table | outline
 public | groups                   | table | outline
 public | integrations             | table | outline
 public | notification_settings    | table | outline
 public | notifications            | table | outline
 public | pins                     | table | outline
 public | revisions                | table | outline
 public | search_queries           | table | outline
 public | shares                   | table | outline
 public | stars                    | table | outline
 public | teams                    | table | outline
 public | user_authentications     | table | outline
 public | users                    | table | outline
 public | views                    | table | outline
(26 rows)

```

Your command would read something like `docker-compose run --rm postgres sh -c 'psql postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@outline_postgres/${POSTGRES_DB} -c "\dt"'`

My third suggestion would be to remove all `container_name` entries from the Compose file and to rely on the automatic naming conventions applied to the individual containers.

---

The `EXPOSE` can also happen in the Dockerfile, and for Postgres is implicitly applied from there:

https://github.com/docker-library/postgres/blob/f060d1236051da2205da24f7caa6ff5301c6be9a/13/bullseye/Dockerfile#L223

**Reply by Halllo5** [reply]
I could fix the Error with the docker-compose file down below i dont realy know how but the password of postgres was not set corectly and i have to change it manualy.

Thank you all so much for your help

I could change it by connecting to the terminal of the docker container `outline_postgres` and use the command `\password outline`

The docker-compose file

```yml
version: "2"
services:
  outline_redis:
    image: redis
    restart: always
    container_name: outline_redis
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:13
    restart: always
    container_name: outline_postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    networks:
      - outline-internal
    ports:
      - 5432:5432
    volumes:
      - /mnt/containers/outline/container-data/db:/var/lib/postgresql/data:Z

  outline_minio:
    image: minio/minio
    restart: always
    container_name: outline_minio
    volumes:
      - /mnt/containers/outline/container-data/data:/data:Z
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    ports:
       - 9000:9000
       - 9001:9001
    networks:
      - outline-internal
    command: "server /data --console-address :9001"

  outline:
    image: outlinewiki/outline
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn sequelize:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline_postgres:5432/outline
      - REDIS_URL=redis://outline_redis:6379
      - URL=${WIKI_URL}
      - PORT=444
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - OIDC_CLIENT_ID=outline-data
      - OIDC_CLIENT_SECRET=${AUTH_CLIENT_SECRET}
      - OIDC_AUTH_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/auth
      - OIDC_TOKEN_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/token
      - OIDC_USERINFO_URI=${AUTH_URL}/auth/realms/master/protocol/openid-connect/userinfo
      - OIDC_USERNAME_CLAIM=email
      - OIDC_DISPLAY_NAME=Keycloak
      - OIDC_SCOPES=email
    ports:
       - 444:444
    networks:
      - outline-internal
      #- nginx-proxy-manager_default

networks:
  outline-internal:
  #nginx-proxy-manager_default:
    #external: true
```
