### DISCUSSION TITLE
How can I trust Postgresql server certificates to encrypt traffic between server and client?

### DISCUSSION THREAD

**Discussion by leonsteinhaeuser** [outline/outline#4191] [Self Hosting] [answered]
Hi there,

I was trying to connect outline to our HA-postgresql-cluster which uses tls to encrypt traffic between the client and the server. To set up the secure connection, I need to pass a tls certificate to trust the CA (self-signed). The things I have already tried are the following:

```
...
env:
    NODE_OPTIONS: --use-openssl-ca
    NODE_EXTRA_CA_CERTS: '["/certs/ssl/pgbouncer.crt"]'
mounts:
    - ./mycert.crt:/certs/ssl/pgbouncer.crt
    - ./mycert.crt:/etc/ssl/certs/pgbouncer.crt
```

Both settings from above does not help. Is there by any chance an option that can be specified to trust the certificate?

Error generated by the outline:

```
Defaulted container "outline" out of: outline, outline-tls-ca-trust (init), outline-migration (init)
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142
                reject(new sequelizeErrors.ConnectionError(err));
                       ^

ConnectionError [SequelizeConnectionError]: self signed certificate in certificate chain
    at Client._connectionCallback (/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:142:24)
    at Client._handleErrorWhileConnecting (/opt/outline/node_modules/pg/lib/client.js:305:19)
    at Client._handleErrorEvent (/opt/outline/node_modules/pg/lib/client.js:315:19)
    at Connection.emit (node:events:526:28)
    at Connection.emit (node:domain:475:12)
    at TLSSocket.reportStreamError (/opt/outline/node_modules/pg/lib/connection.js:53:12)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  parent: Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
      at TLSSocket.emit (node:events:526:28)
      at TLSSocket.emit (node:domain:475:12)
      at TLSSocket._finishInit (node:_tls_wrap:944:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  },
  original: Error: self signed certificate in certificate chain
      at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)
      at TLSSocket.emit (node:events:526:28)
      at TLSSocket.emit (node:domain:475:12)
      at TLSSocket._finishInit (node:_tls_wrap:944:8)
      at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
    code: 'SELF_SIGNED_CERT_IN_CHAIN'
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by almereyda** [comment, marked as answer]
When you have mapped your certificates into the respective container, from which the database connection will be initialised, you can add the properties to the `DATABASE_URL`, similar to what is explained in https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/ssl_connections/:

- `sslkey=/path/to/credentials.key`
- `sslcert=/path/to/credentials.crt`
- `sslrootcert=/path/to/ca.crt`

This is a complete example for a database connection string within a Kubernetes environment that uses the Crunchy Operator. Beforehand we have copied the `postgres-tls-secrets` into the appropriate namespace. In general, it looks like this:

`deployment.yaml`

```yaml
...
spec:
  ...
  containers:
    ...
    - name: next
      ...
      volumeMounts:
        - name: postgres-tls-secrets
          mountPath: /etc/ssl/certs/postgress.ca.crt
          subPath: ca.crt
        - name: postgres-tls-secrets
          mountPath: /etc/ssl/certs/postgres.crt
          subPath: tls.crt
        - name: postgres-tls-secrets
          mountPath: /etc/ssl/private/postgres.key
          subPath: tls.key
      ...
    ...
...
```

In our case the properties are added to the connection string with a little pipeline, that copies the database secret from the operator namespace into the application namespace, and transforms it according to our liking:

```shell
k neat get -- secret operator-postgres1-pguser-next -o yaml | \
  yq e ".data.uri = \"$(                                      \
    k get secret operator-postgres1-pguser-next -o yaml     | \
    yq '.data.uri'                                          | \
    base64 -d                                               | \
    sed 's|$|?sslcert=/etc/ssl/certs/postgres.crt\&sslkey=/etc/ssl/private/postgres.key\&sslrootcert=/etc/ssl/certs/postgress.ca.crt|g' | \
    base64 -w0                                                \
  )\""                                                      | \
  sed 's/namespace: postgres-operator/namespace: next/g'    | \
  k apply -f -
```

Please note some of the character escapes are neccessary due to the use of `zsh`, and might not apply in your shell. `k` is an alias to `kubectl` and [`neat`](https://github.com/itaysk/kubectl-neat) is a [`krew`](https://krew.sigs.k8s.io/) [plugin](https://krew.sigs.k8s.io/plugins/).

Also take notice of the different `| \` and `\` line endings, which are needed for multiline input on a shell REPL. I have aligned those to the right, but they can also immediately follow the commands. Each `\` can be delete, if you also delete the following line break `\n` after it. The `|` need to remain intact for functioning.

---

PS: Kommst du auch auf der Bits & Bäume Eröffnung heute Abend?
