### DISCUSSION TITLE
Setting a Redis password for container

### DISCUSSION THREAD

**Discussion by HardChalice** [outline/outline#4233] [Self Hosting] [answered]
Hey all,

Running an docker outline setup and I want to add a password for my redis container. My nessus scan recommended passing in the `requirepass` arg to my redis. conf. However once I added and tried starting up my compose file again I get an error from outline.

Outline Error:
```
outline                  | yarn run v1.22.18
outline                  | $ node ./build/server/index.js
outline                  | {"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
outline                  | /opt/outline/node_modules/redis-parser/lib/parser.js:179
outline                  |     return new ReplyError(string)
outline                  |            ^
outline                  | 
outline                  | ReplyError: EXECABORT Transaction discarded because of: NOAUTH Authentication required.
outline                  |     at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
outline                  |     at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
outline                  |   command: { name: 'exec', args: [] },
outline                  |   previousErrors: [
outline                  |     ReplyError: NOAUTH Authentication required.
outline                  |         at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
outline                  |         at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
outline                  |       command: { name: 'multi', args: [] }
outline                  |     },
outline                  |     ReplyError: NOAUTH Authentication required.
outline                  |         at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
outline                  |         at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
outline                  |       command: { name: 'llen', args: [ 'bull:globalEvents:wait' ] }
outline                  |     },
outline                  |     ReplyError: NOAUTH Authentication required.
outline                  |         at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
outline                  |         at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
outline                  |       command: { name: 'llen', args: [ 'bull:globalEvents:paused' ] }
outline                  |     },
outline                  |     ReplyError: NOAUTH Authentication required.
outline                  |         at parseError (/opt/outline/node_modules/redis-parser/lib/parser.js:179:12)
outline                  |         at parseType (/opt/outline/node_modules/redis-parser/lib/parser.js:302:14) {
outline                  |       command: { name: 'zcard', args: [ 'bull:globalEvents:delayed' ] }
outline                  |     }
outline                  |   ]
outline                  | }
```

Redis.conf:
```
requirepass MY_PASS
```

docker-compose.yml
```
  redis:
    image: redis
    #container_name: outline-redis
    restart: always
    env_file:
      - ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/redis.conf:/etc/redis/redis.conf
    command: ["redis-server", "/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline
```

Any idea what else I need? I imagine it's something to do with the Redis URL in my `docker.env` now but Im unsure exactly what the fix would be.
