### DISCUSSION TITLE
Strange behaviour with Minio

### DISCUSSION THREAD

**Discussion by padey** [outline/outline#4558] [Self Hosting]
Hello all. Short description of my setup:

On the same docker host:
- Outline 
- MinIO

Second server as reverse proxy (haproxy) where Outline and MinIO are made accessible via https. 

Now it is so that Outline uploads via https are possible without any problems, also the uploads (pictures, documents etc.) are displayed or can be downloaded via Outline. However, if I want to export the entire data, it fails with the error: "Inaccessible host: `s3......com' at port `443'. This service may not be available in the `local' region." - In the case of an HTML export, the images are missing, for example.

If I configure Outline to the IP address of MinIO directly, without https, e.g. http://minio:9000 - the export of the data including pictures, documents etc. works. BUT no more data can be uploaded or displayed in the wikis. 

I've been working on this for a while now and can't find a solution that is logical for me... Do you have any ideas?

**Comment by winkelement** [comment]
I have a very similar setup except haproxy is running on the same machine as the docker-containers and can not reproduce that error.
Maybe post you (redacted) `haproxy.cfg`, `docker.env`, `docker-compose.yml` so i can compare settings? Or maybe it's specific to the MinIO setup... actually i had to tinker around with that quite a bit (due to lack of expertise in the matter) to get that running at all.

**Reply by padey** [reply]
I suspect the problems are more with HAProxy by now. As soon as it comes into play, there is the strange behaviour.
Maybe I'm working with hdr(host) or something is missing in the backend. A wrong header, I have no idea.



**docker.env: Image/File Upload/Display works, Export not**
```
AWS_ACCESS_KEY_ID=asdfasdf
AWS_SECRET_ACCESS_KEY=asdfasdf
AWS_REGION=local
AWS_S3_ACCELERATE_URL=https://s3...com
AWS_S3_UPLOAD_BUCKET_URL=https://s3...com
AWS_S3_UPLOAD_BUCKET_NAME=outline
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
```

**docker.env: Image/File Upload/Display works NOT, Export works**
```
AWS_ACCESS_KEY_ID=asdfasdf
AWS_SECRET_ACCESS_KEY=asdfasdf
AWS_REGION=local
AWS_S3_ACCELERATE_URL=http://192.168.XXX.XXX:9000
AWS_S3_UPLOAD_BUCKET_URL=http://192.168.XXX.XXX:9000
AWS_S3_UPLOAD_BUCKET_NAME=outline
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
```

docker-compse.yml is very basic
```
version: "3"
services:

  outline:
    image: outlinewiki/outline
    env_file: ./docker.env
    networks:
     - internal_net
    ports:
      - "3773:3000"
 networks:
   internal_net:
    external: true
```

haproxy.cfg
```
frontend
        bind *:443 ssl crt /etc/ssl/ alpn h2,http/1.1

        redirect scheme https code 301 if !{ ssl_fc }
        http-response set-header Strict-Transport-Security max-age=63072000
        http-request set-header X-Forwarded-Proto https if { ssl_fc }

        http-request add-header X-Real-Ip %[src]
        option forwardfor # X-forwarded-for

        use_backend s3 if { hdr(Host) -i s3...com }

....
backend s3
        server XXXXXXXXXXX 192.168.XXX.XXX:9000 check port ssl verify none
```

**Reply by winkelement** [reply]
Mhmm the only obvious difference to my config seems to be that i terminate ssl for MinIO via haproxy.

docker.env
```INI
AWS_ACCESS_KEY_ID=outline_user
AWS_SECRET_ACCESS_KEY=XXX
AWS_REGION=local
#AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=https://storage.wiki.XXX.XXX
AWS_S3_UPLOAD_BUCKET_NAME=XXX
AWS_S3_UPLOAD_MAX_SIZE=26214400
#AWS_S3_FORCE_PATH_STYLE=true
#AWS_S3_ACL=public-read
```

docker-compose.yml

```YAML

version: "3"
services:

  outline:
    image: outlinewiki/outline:latest
    container_name: outline-server
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage
[...]

  storage:
    image: minio/minio
    container_name: outline-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=XXX
      - MINIO_ROOT_PASSWORD=XXX
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://storage:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

```
haproxy.cfg
```CFG
[...]
frontend fe
    bind *:80
    bind *:443 ssl crt /etc/ssl/wiki.XXX.XXX/wiki.XXX.XXX.pem crt /etc/ssl/storage.wiki.XXX.XXX/storage.wiki.XXX.XXX.pem
    redirect scheme https code 301 if !{ ssl_fc }
    acl letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
    http-response set-header Strict-Transport-Security "max-age=16000000; includeSubDomains; preload;"
    http-request add-header X-Forwarded-Port 443
    http-request add-header X-Forwarded-Proto https
    http-request add-header X-Forwarded-Ssl on
    acl outline-acl hdr(host) -i wiki.XXX.XXX
    use_backend be-outline if outline-acl
    acl outline-storage-acl hdr(host) -i storage.wiki.XXX.XXX
    use_backend be-outline-storage if outline-storage-acl

backend letsencrypt-backend
    server letsencrypt 127.0.0.1:8888

backend be-outline
    server outline 127.0.0.1:3000

backend be-outline-storage
    server outline-storage 127.0.0.1:9000
```
