### DISCUSSION TITLE
Authelia works fine but Outline gives me an error! Please help!

### DISCUSSION THREAD

**Discussion by felixsanz** [outline/outline#4676] [Self Hosting] [answered]
This is so `F`rustrating! It should be called OIDC**F**. I'm trying to integrate Authelia and doesn't work fine. This is the UI workflow:

### Welcome:
![1673451742](https://user-images.githubusercontent.com/6182099/211851057-3bce0bb9-c9c4-423d-a527-281b2f8fd3b4.png)

### Authentication:
![1673451757](https://user-images.githubusercontent.com/6182099/211851091-30f6ce1f-d5ca-4df6-8c64-dd7bd40f5ddf.png)

### Authorization:
![1673451948](https://user-images.githubusercontent.com/6182099/211851104-7f41ba4f-4ffa-4b56-a0d1-9c1adb49d481.png)

## **FAILS !!!**
![1673451953](https://user-images.githubusercontent.com/6182099/211851305-157f1022-1e93-44a1-9db8-7d10f914bbac.png)

### Authelia logs says it's all OK:
```
time="2023-01-11T15:45:49Z" level=debug msg="Authorization Request with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' on client with id 'outline' is being processed" method=GET path=/api/oidc/authorization remote_ip=10.0.2.100
time="2023-01-11T15:45:49Z" level=debug msg="Authorization Request with id 'xxxxxxxxxxxxxxxxxxxxxxxxx' on client with id 'outline' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=10.0.2.100
```

### But Outline complains!
```
error:	Failed to obtain access token

stack:	InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)
    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (node:events:526:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

level:	error

message:	Error during authentication
```

# Outline config:

```
SECRET_KEY="<Reserved>" \
UTILS_SECRET="<Reserved>" \
URL="https://outline.mydomain.com" \
PORT=3000 \
FORCE_HTTPS=false \
ENABLE_UPDATES=false \
DEFAULT_LANGUAGE="en_US" \
DEBUG="cache,presenters,events,emails,mailer,utils,multiplayer,server,services" \

REDIS_URL="redis://localhost:6379" \

DATABASE_URL="postgres://outline:<Reserved>@localhost:5432/outline" \
PGSSLMODE="disable" \

AWS_ACCESS_KEY_ID="<Reserved>" \
AWS_SECRET_ACCESS_KEY="<Reserved>" \
AWS_S3_UPLOAD_BUCKET_URL="http://localhost:9000" \
AWS_S3_UPLOAD_BUCKET_NAME="outline-bucket" \
AWS_S3_UPLOAD_MAX_SIZE=26214400 \
AWS_S3_FORCE_PATH_STYLE=true \
AWS_S3_ACL="private" \

OIDC_DISPLAY_NAME="Authelia" \
OIDC_CLIENT_ID="outline" \
OIDC_CLIENT_SECRET="<Reserved_XXX>" \
OIDC_AUTH_URI="https://authelia.mydomain.com/api/oidc/authorization" \
OIDC_TOKEN_URI="https://authelia.mydomain.com/api/oidc/token" \
OIDC_USERINFO_URI="https://authelia.mydomain.com/api/oidc/userinfo" \
OIDC_SCOPES="openid offline_access profile email" \
OIDC_USERNAME_CLAIM="preferred_username" \
```

# Authelia config

```
server:
  host: 0.0.0.0
  port: 8081

log:
  level: debug

jwt_secret: <Reserved>

authentication_backend:
  file:
    path: /config/users.yml

storage:
  encryption_key: <Reserved>
  local:
    path: /data/db.sqlite3

notifier:
  filesystem:
    filename: /tmp/authelia/notification.txt

session:
  name: authelia_session
  secret: <Reserved>
  expiration: 3600
  inactivity: 300
  domain: mydomain.com

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

access_control:
  default_policy: deny
  rules:
    - domain: "mydomain.com"
      policy: one_factor

identity_providers:
  oidc:
    hmac_secret: <Reserved>
    issuer_private_key: |
      -----BEGIN PRIVATE KEY-----
     <Reserved>
      -----END PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://outline.mydomain.com
      allowed_origins_from_client_redirect_uris: false
    clients:
      - id: outline
        description: Outline
        secret: <Reserved_XXX>
        public: false
        authorization_policy: one_factor
        redirect_uris:
          - https://outline.mydomain.com/auth/oidc.callback
        scopes:
          - openid
          - offline_access
          - profile
          - email
        userinfo_signing_algorithm: none
```

_Notice how `OIDC_CLIENT_ID` and `OIDC_CLIENT_SECRET` maps to Authelia's `identity_providers.oidc.clients[0].id` and `identity_providers.oidc.clients[0].secret`_

# Authelia users.yml:

```
users:
  admin:
    displayname: "admin"
    password: "$argon2<Reserved>"
    email: <Reserved>
    groups:
      - admins
```

# My infrastructure:

- Authelia running on https://authelia.mydomain.com
- Outline running on https://outline.mydomain.com
- They both managed by Caddy, with self-signed certificates and SSL termination. So at this point caddy redirects to plain HTTP services like:

```
authelia.mydomain.com {
  tls internal
  reverse_proxy http://10.0.0.2:8081
}

outline.mydomain.com {
  tls internal
  reverse_proxy http://10.0.0.2:8091
}
```

# What i've tried:

- Setting `FORCE_HTTPS` to true...... **NOTHING**

- Playing with `OIDC_SCOPES` and authelia's `oidc.client.scopes` (removing `offline_access`, adding only `email`, only `openid`, etc)...... **NOTHING**

- Setting `two_factor` where `one_factor` appears...... **NOTHING**

# PLEASE

![1673453279](https://user-images.githubusercontent.com/6182099/211856612-1fb26986-f06b-4f3c-b86d-e008871ab918.png)

🙏🙏🙏🙏🙏🙏
