### DISCUSSION TITLE
Installed Outline Wiki; A few days later: FATAL Password authentication failed for user "postgres"

### DISCUSSION THREAD

**Discussion by Tagette** [outline/outline#4740] [Self Hosting]
Hello, I recently installed outline wiki v0.67.1 using docker compose and at first it was working. A few days later

### The Problem
```
outline2-postgres-1         | 2023-01-19 03:53:08.967 UTC [1111] FATAL:  password authentication failed for user "postgres"
outline2-postgres-1         | 2023-01-19 03:53:08.967 UTC [1111] DETAIL:  Role "postgres" does not exist.
outline2-postgres-1         |   Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

These errors spam my docker logs and the service no longer works with a 503 error.

### Details
My docker compose looks like this:
```yaml
version: "3"
services:

  storage_startup:
    image: minio/mc:RELEASE.2023-01-11T03-14-16Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 secret secret2
      /usr/bin/mc mb minio/outline-bucket;
      /usr/bin/mc anonymous set download minio/outline-bucket;
      exit 0;
      "

  outline:
    image: outlinewiki/outline:0.67.1
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio

  redis:
    image: redis:7.0.7
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    image: postgres:15.1
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - /storage/outline/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z
    env_file: ./minio.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'minio server /minio_root'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /storage/outline/file_data:/data
      - /storage/outline/files:/minio_root
```
Here is some entries from docker.env:
```ini
DATABASE_URL=postgres://user:pass@postgres:5432/outline
DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
# Uncomment this to disable SSL for connecting to Postgres
PGSSLMODE=disable

URL=https://wiki.mydomain.com
PORT=3000

# The default interface language. See translate.getoutline.com for a list of
# available language codes and their rough percentage translated.
DEFAULT_LANGUAGE=en_US

# Optionally enable rate limiter at application web server
RATE_LIMITER_ENABLED=true

# Configure default throttling parameters for rate limiter
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

Everything is run on the same machine in docker. Ports 3000 and 9000 are open in the firewall.
(I found I had to open port 9000 to get minio to work. Maybe someone knows a better way?)

### My Question
Does anyone know why postgres would stop working all of a sudden?
Why is it complaining about the postgres user when the user is supposed to be "user"?
How can I fix this?

Thanks.

Edit: Further Information:
I started it up and it worked for about 10 minutes then this happened:
![image](https://user-images.githubusercontent.com/682189/213843689-4813edf9-b945-4351-84df-230ae62e0b68.png)

These are the logs from when it broke.
```
outline2-postgres-1         | 2023-01-21 04:32:33.655 UTC [27] LOG:  checkpoint starting: time
outline2-postgres-1         | 2023-01-21 04:32:34.399 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.287 s, sync=0.260 s, total=0.745 s; sync files=3, longest=0.242 s, average=0.087 s; distance=8 kB, estimate=200 kB
outline2-redis-1            | 1:S 21 Jan 2023 04:35:01.721 * Before turning into a replica, using my own master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
outline2-redis-1            | 1:S 21 Jan 2023 04:35:01.721 * Connecting to MASTER 194.40.243.206:8886
outline2-redis-1            | 1:S 21 Jan 2023 04:35:01.722 * MASTER <-> REPLICA sync started
outline2-redis-1            | 1:S 21 Jan 2023 04:35:01.722 * REPLICAOF 194.40.243.206:8886 enabled (user request from 'id=12 addr=109.237.97.141:44416 laddr=172.18.0.3:6379 fd=15 name= age=0 idle=0 flags=N db=0 sub=0 psub=0 ssub=0 multi=-1 qbuf=48 qbuf-free=20426 argv-mem=25 multi-mem=0 rbs=1024 rbp=0 obl=0 oll=0 omem=0 tot-mem=22321 events=r cmd=slaveof user=default redir=-1 resp=2')
outline2-outline-1          | {"level":"warn","message":"Retrying redis connection: attempt 1"}
outline2-outline-1          | {"level":"warn","message":"Retrying redis connection: attempt 1"}
outline2-outline-1          | {"level":"warn","message":"Retrying redis connection: attempt 1"}
outline2-outline-1          | {"level":"warn","message":"Retrying redis connection: attempt 1"}
outline2-redis-1            | 1:S 21 Jan 2023 04:35:01.846 * Non blocking connect for SYNC fired the event.
outline2-postgres-1         | bash: line 2: pkill: command not found
outline2-postgres-1         | bash: line 3: pkill: command not found
outline2-postgres-1         | bash: line 4: pkill: command not found
outline2-postgres-1         | chattr: No such file or directory while trying to stat /etc/ld.so.preload
outline2-postgres-1         | chattr: No such file or directory while trying to stat /var/spool/cron
outline2-postgres-1         | chattr: No such file or directory while trying to stat /etc/crontab
outline2-postgres-1         | bash: line 9: ufw: command not found
outline2-postgres-1         | bash: line 10: iptables: command not found
outline2-postgres-1         | bash: line 11: /proc/sys/kernel/nmi_watchdog: Read-only file system
outline2-postgres-1         | bash: line 12: /etc/sysctl.conf: Permission denied
outline2-postgres-1         | bash: line 108: curl: command not found
outline2-postgres-1         | bash: line 108: /usr/local/bin/curl: Permission denied
outline2-postgres-1         | chmod: cannot access '/usr/local/bin/curl': No such file or directory
outline2-postgres-1         | bash: line 109: /usr/local/bin/curl: No such file or directory
outline2-postgres-1         | bash: line 110: /usr/local/bin/curl: No such file or directory
outline2-redis-1            | 1:S 21 Jan 2023 04:35:03.381 * Master replied to PING, replication can continue...
outline2-redis-1            | 1:S 21 Jan 2023 04:35:03.636 * Trying a partial resynchronization (request 0a657788e8422fa7d6340993d2f182f017a38069:1).
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.011 * Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:1
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.011 * MASTER <-> REPLICA sync: receiving 54992 bytes from master to disk
outline2-postgres-1         | chmod: cannot access '/tmp/curl': No such file or directory
outline2-postgres-1         | bash: line 113: /tmp/curl: No such file or directory
outline2-postgres-1         | main: line 177: ps: command not found
outline2-postgres-1         | main: line 178: ps: command not found
outline2-postgres-1         | main: line 179: pkill: command not found
outline2-postgres-1         | main: line 180: pkill: command not found
outline2-postgres-1         | main: line 181: ps: command not found
outline2-postgres-1         | main: line 182: ps: command not found
outline2-postgres-1         | main: line 183: pkill: command not found
outline2-postgres-1         | main: line 184: netstat: command not found
outline2-postgres-1         | main: line 185: netstat: command not found
outline2-postgres-1         | main: line 186: netstat: command not found
outline2-postgres-1         | main: line 187: netstat: command not found
outline2-postgres-1         | main: line 188: pkill: command not found
outline2-postgres-1         | main: line 189: pkill: command not found
... Repeating Lines
outline2-postgres-1         | main: line 216: ps: command not found
outline2-postgres-1         | cat: /tmp/.X11-unix/01: No such file or directory
outline2-postgres-1         | cat: /tmp/.X11-unix/11: No such file or directory
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.259 * Discarding previously cached master state.
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.259 * MASTER <-> REPLICA sync: Flushing old data
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.259 * MASTER <-> REPLICA sync: Loading DB in memory
outline2-postgres-1         | cat: /tmp/.X11-unix/22: No such file or directory
outline2-postgres-1         | cat: /tmp/.pg_stat.0: No such file or directory
outline2-postgres-1         | cat: /tmp/.pg_stat.1: No such file or directory
outline2-postgres-1         | cat: /var/lib/postgresql/data/./oka.pid: No such file or directory
outline2-postgres-1         | main: line 223: pkill: command not found
... Repeating Lines
outline2-postgres-1         | main: line 235: ps: command not found
outline2-postgres-1         | md5sum: /tmp/kinsing: No such file or directory
outline2-postgres-1         | /tmp/kinsing is not 2c44b4e4706b8bd95d1866d7867efa0e, actual
outline2-postgres-1         | chmod: cannot access '/tmp/kinsing': No such file or directory
outline2-postgres-1         |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
outline2-postgres-1         |                                  Dload  Upload   Total   Spent    Left  Speed
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.297 # Wrong signature trying to load DB from file
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.297 # Failed trying to load the MASTER synchronization DB from disk: Invalid argument
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.298 * Reconnecting to MASTER 194.40.243.206:8886 after failure
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.298 * MASTER <-> REPLICA sync started
outline2-redis-1            | 1:S 21 Jan 2023 04:35:04.422 * Non blocking connect for SYNC fired the event.
100 6168k  100 6168k    0     0  4386k      0  0:00:01  0:00:01 --:--:-- 4386k
outline2-postgres-1         | /tmp/kinsing is 2c44b4e4706b8bd95d1866d7867efa0e
outline2-postgres-1         | md5sum: /tmp/libsystem.so: No such file or directory
outline2-postgres-1         | /tmp/libsystem.so is not ccef46c7edf9131ccffc47bd69eb743b, actual
outline2-postgres-1         | chmod: cannot access '/tmp/libsystem.so': No such file or directory
outline2-postgres-1         |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
outline2-postgres-1         |                                  Dload  Upload   Total   Spent    Left  Speed
100 26800  100 26800    0     0  69430      0 --:--:-- --:--:-- --:--:-- 69430
outline2-postgres-1         | /tmp/libsystem.so is ccef46c7edf9131ccffc47bd69eb743b
outline2-postgres-1         |   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
outline2-postgres-1         |                                  Dload  Upload   Total   Spent    Left  Speed
outline2-redis-1            | 1:S 21 Jan 2023 04:35:06.233 # Failed to read response from the server: Success
outline2-redis-1            | 1:S 21 Jan 2023 04:35:06.233 # Master did not respond to command during SYNC handshake
100 26800  100 26800    0     0  70341      0 --:--:-- --:--:-- --:--:-- 70341
outline2-postgres-1         | /tmp/libsystem.so is ccef46c7edf9131ccffc47bd69eb743b
outline2-postgres-1         | main: line 266: /etc/ld.so.preload: Permission denied
outline2-postgres-1         | main: line 270: crontab: command not found
outline2-postgres-1         | main: line 270: crontab: command not found
... Repeating Lines
outline2-postgres-1         | bash: line 369: crontab: command not found
outline2-redis-1            | 1:S 21 Jan 2023 04:35:06.967 * Connecting to MASTER 194.40.243.206:8886
outline2-redis-1            | 1:S 21 Jan 2023 04:35:06.967 * MASTER <-> REPLICA sync started
outline2-redis-1            | 1:S 21 Jan 2023 04:35:07.095 * Non blocking connect for SYNC fired the event.
outline2-redis-1            | 1:S 21 Jan 2023 04:35:08.386 # Failed to read response from the server: Success
outline2-redis-1            | 1:S 21 Jan 2023 04:35:08.386 # Master did not respond to command during SYNC handshake
outline2-redis-1            | 1:S 21 Jan 2023 04:35:08.977 * Connecting to MASTER 194.40.243.206:8886
outline2-redis-1            | 1:S 21 Jan 2023 04:35:08.977 * MASTER <-> REPLICA sync started
outline2-redis-1            | 1:S 21 Jan 2023 04:35:09.111 * Non blocking connect for SYNC fired the event.
outline2-redis-1            | 1:S 21 Jan 2023 04:35:11.117 # Failed to read response from the server: Success
outline2-redis-1            | 1:S 21 Jan 2023 04:35:11.117 # Master did not respond to command during SYNC handshake
outline2-redis-1            | 1:S 21 Jan 2023 04:35:11.990 * Connecting to MASTER 194.40.243.206:8886
outline2-redis-1            | 1:S 21 Jan 2023 04:35:11.990 * MASTER <-> REPLICA sync started
outline2-redis-1            | 1:S 21 Jan 2023 04:35:12.118 * Non blocking connect for SYNC fired the event.
outline2-redis-1            | 1:S 21 Jan 2023 04:35:13.614 # Failed to read response from the server: Success
outline2-redis-1            | 1:S 21 Jan 2023 04:35:13.614 # Master did not respond to command during SYNC handshake
outline2-redis-1            | 1:S 21 Jan 2023 04:35:14.001 * Connecting to MASTER 194.40.243.206:8886
outline2-redis-1            | 1:S 21 Jan 2023 04:35:14.001 * MASTER <-> REPLICA sync started
```
