### DISCUSSION TITLE
Please fix the documentation on deploying with Docker. 🙏🏻

### DISCUSSION THREAD

**Discussion by jinrenjie** [outline/outline#4742] [Self Hosting] [answered]
I used the method in [this document](https://wiki.generaloutline.com/s/hosting/doc/docker-7pfeLP5a8t) to deploy, but found that the Postgres DB is always in an unhealthy state, but it does not affect the normal use of Outline.

```yaml
services:
  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
```

After I changed `test: ["CMD", "pg_isready -U user"]` to `test: ["CMD", "pg_isready"]`, the status of the container is healthy!
