### DISCUSSION TITLE
Unable to login for the first time using Authelia

### DISCUSSION THREAD

**Discussion by Brawdunoir** [outline/outline#4817] [Self Hosting] [answered]
Hello !

I am having trouble to start Outline using a docker-compose solution and I am running out of ideas to debug this…
I never used Outline before, and it the first time I try to setup it, sorry if I missed something obvious !
I use bunkerweb as a reverse proxy, which is a nginx with default security rules.

Steps:
1. Connect to Outline URL `notes.mydomain.com`
2. Get redirected to Authelia and login successfully
3. Accept Consent Request
4. Get redirected to Outline URL again
5. Go to step 1

This is the logs I got from Outline then I authenticate through OIDC (Authelia)
```
outline           | {"label":"http","level":"info","message":"  <-- GET /auth/oidc"}
outline           | {"label":"http","level":"info","message":"  --> GET /auth/oidc 302 5ms 0b"}
outline           | {"label":"http","level":"info","message":"  <-- GET /auth/oidc.callback?code=authelia_ac_o2WinOwXxYTIyVTJmhdQ0tYo8sPkakSs0dFXW5z4Ub8.s5Y9R4odvKpAF7gai_VML1KTQIrUWjUg2oEbcmeHE6Q&scope=openid+profile+email&state=aba3b8797a2ac921"}
outline           | {"name":"users.signin","modelId":null,"attempt":0,"label":"worker","level":"info","message":"Processing users.signin"}
outline           | {"label":"http","level":"info","message":"  --> GET /auth/oidc.callback?code=authelia_ac_o2WinOwXxYTIyVTJmhdQ0tYo8sPkakSs0dFXW5z4Ub8.s5Y9R4odvKpAF7gai_VML1KTQIrUWjUg2oEbcmeHE6Q&scope=openid+profile+email&state=aba3b8797a2ac921 302 148ms 147b"}
outline           | {"name":"users.signin","modelId":null,"label":"worker","level":"info","message":"WebhookProcessor running users.signin"}
outline           | {"label":"http","level":"info","message":"  <-- GET /collection/welcome-IzXhJDZtCQ"}
outline           | {"label":"http","level":"info","message":"  --> GET /collection/welcome-IzXhJDZtCQ 200 29ms 790b"}
outline           | {"label":"http","level":"info","message":"  <-- POST /api/auth.config"}
outline           | {"label":"http","level":"info","message":"  --> POST /api/auth.config 200 11ms 170b"}
```

This is my `docker-compose` and my `docker.env` files:
```yaml
services:
  outline:
    image: outlinewiki/outline:0.67.0
    container_name: outline
    restart: unless-stopped
    env_file: ./docker.env
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    networks:
      bw-notes:
        aliases:
          - notes
      internal:
    volumes:
      - ./config:/config
    security_opt:
      - no-new-privileges:true
    labels:
      - "bunkerweb.SERVER_NAME=notes.mydomain.com"
      - "bunkerweb.USE_MODSECURITY=no"
      - "bunkerweb.ALLOWED_METHODS=GET|POST|HEAD|DELETE|PUT"
      - "bunkerweb.USE_REVERSE_PROXY=yes"
      - "bunkerweb.REVERSE_PROXY_URL=/"
      - "bunkerweb.REVERSE_PROXY_HOST=http://notes:3000"
    depends_on:
      - postgres
      - redis
      - s3

  s3:
    image: bitnami/minio:2023
    ports:
      - 9000:9000
      - 9001:9001
    env_file: ./docker.env
    container_name: s3
    networks:
      internal:
    volumes:
      - ./data:/data

  postgres:
    image: postgres:15
    env_file: ./docker.env
    networks:
      internal:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=xxx
      - POSTGRES_PASSWORD=xxx
      - POSTGRES_DB=outline

  redis:
    image: redis
    env_file: ./docker.env
    networks:
      internal:
        aliases:
          - redis

networks:
  bw-notes:
    name: bw-notes
    external: true
  internal:
  ```
  
  ```env
NODE_ENV=production
SECRET_KEY=xxx
UTILS_SECRET=xxx
DATABASE_URL=postgres://outline:xxx@postgres:5432/outline
DATABASE_URL_TEST=postgres://user:pass@localhost:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
PGSSLMODE=disable

REDIS_URL=redis://redis:6379

URL=https://notes.mydomain.com
PORT=3000

COLLABORATION_URL=

AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_REGION=gra
AWS_S3_UPLOAD_BUCKET_URL=s3
AWS_S3_UPLOAD_BUCKET_NAME=outline

MINIO_ROOT_USER=xxx
MINIO_ROOT_PASSWORD=xxx
MINIO_DEFAULT_BUCKETS=outline

# –––––––––––––– AUTHENTICATION ––––––––––––––

OIDC_CLIENT_ID=outline
OIDC_CLIENT_SECRET=xxx
OIDC_AUTH_URI=https://auth.mydomain.com/api/oidc/authorization
OIDC_TOKEN_URI=https://auth.mydomain.com/api/oidc/token
OIDC_USERINFO_URI=https://auth.mydomain.com/api/oidc/userinfo
OIDC_USERNAME_CLAIM=preferred_username
OIDC_DISPLAY_NAME=Authelia
OIDC_SCOPES="openid profile email"

SSL_KEY=
SSL_CERT=
CDN_URL=
FORCE_HTTPS=false
ENABLE_UPDATES=true
WEB_CONCURRENCY=1
MAXIMUM_IMPORT_SIZE=5120000
DEBUG=http
GOOGLE_ANALYTICS_ID=
SENTRY_DSN=
SENTRY_TUNNEL=
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

I followed [Authelia steps](https://www.authelia.com/integration/openid-connect/outline/) regarding OIDC setup:
```yaml
clients:
  - id: outline
    description: Outline
    secret: '$plaintext$xxx'
    public: false
    authorization_policy: one_factor
    redirect_uris:
      - https://notes.mydomain.com/auth/oidc.callback
    scopes:
      - openid
      - profile
      - email
    userinfo_signing_algorithm: none
 ```
 
 It may be worth noting that OIDC using Authelia works with my self-hosted Nextcloud.
 
 Any clue is welcome !
 Thanks.
