### DISCUSSION TITLE
role "root" does not exist and minio server doesn't starts

### DISCUSSION THREAD

**Discussion by andreyairesvoiicr** [outline/outline#4926] [Self Hosting]
outline-postgres-1  | 2023-02-24 20:18:37.083 UTC [101] FATAL:  role "root" does not exist

1) Postgres Error
I keep getting the FATAL:  role "root" does not exist but the it looks all ok on the server.
I don't even have it mentioned on the docker.env file... it's all outline user and db.

2) MinIO Error
outline-storage-1   |   minio server [FLAGS] DIR{1...64}
outline-storage-1   |   minio server [FLAGS] DIR{1...64} DIR{65...128}
outline-storage-1   | DIR:
outline-storage-1   |   DIR points to a directory on a filesystem. When you want to combine
outline-storage-1   |   multiple drives into a single large system, pass one directory per
outline-storage-1   |   filesystem separated by space. You may also use a '...' convention
outline-storage-1   |   to abbreviate the directory arguments. Remote directories in a
outline-storage-1   |   distributed setup are encoded as HTTP(s) URIs.

It looks like it loops the manual forever.

Have no idea what is causing this.

I have folllowed the instalation steps on Docker, the server is hosted online on a aws ec2 amazon linux 2.

Thanks!

**Comment by c0nf1den71al** [comment]
### Postgres error
I'm pretty sure this is because you haven't specified the username within the healthcheck script. Try using the following for your docker-compose.yml:
```
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=outline
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U outline"]
      interval: 30s
      timeout: 20s
      retries: 3
```

Note the healthcheck command specifies `-U outline`.

### Minio
I'm unsure what the error is you are trying to outline. Please send your docker-compose.yml.

Thanks
