### DISCUSSION TITLE
S3 Config for Alibaba Cloud / Aliyun OSS with CDN

### DISCUSSION THREAD

**Discussion by Fierce-Cat** [outline/outline#4955] [Self Hosting] [answered]
Spent half an hour figuring out how to set it up.

# env
```
AWS_ACCESS_KEY_ID=[YOUR ACCESS ID]
AWS_SECRET_ACCESS_KEY=[YOUR ACCESS KEY]
AWS_REGION=[OSS REGION]
AWS_S3_UPLOAD_BUCKET_NAME=[OSS BUCKET NAME]
AWS_S3_UPLOAD_BUCKET_URL=https://[OSS BUCKET NAME].[OSS REGION].aliyuncs.com // Replace the [OSS BUCKET NAME] and [OSS REGION] by yours.
AWS_S3_ACCELERATE_URL=https://[CDN DOMAIN]
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=false // Important! Set this to 'false' to avoid being forced to use the AWS format.
AWS_S3_ACL=public-read // You also need to set your OSS ACL to public-read （公共读）.
```

**Comment by Fierce-Cat** [comment, marked as answer]
Self-answered.

**Comment by S4kur4** [comment]
Additional configurations on Aliyun OSS console:

1. CORS (跨域资源共享)
Don't forget to add a CORS configuration to your bucket based on your owned domain and outline URL, otherwise you may encounter a 403 error when trying to upload an image. For security reasons, it is not recommended to set CORS to any source (*).
![image](https://user-images.githubusercontent.com/17521941/223944610-0b60b2eb-eb3e-4d90-8873-c9653ca35802.png)

2. Bucket Policy (授权策略)
For security reasons, it is recommended to restrict your bucket access to a limited IP range, otherwise the data will be leaked and the cost will increase.
![image](https://user-images.githubusercontent.com/17521941/223944438-5b5055b0-d992-49bb-a618-a259ef11efa1.png)

**Comment by Spinestars** [comment]
outline version： 0.69.2

After many attempts, the following requirements were finally realized:
1. aliyun oss policies are private
2. Objects uploaded to oss are private
3. Access oss objects in signature mode

```
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  # This is a region id, not a region id for a service, and service identifiers, such as oss, should not be added
  AWS_REGION: cn-beijing
  AWS_S3_UPLOAD_BUCKET_NAME: <bucket_name>
  AWS_S3_UPLOAD_BUCKET_URL: http://<bucket_name>.oss-cn-beijing.aliyuncs.com
  # This is not a CDN address! Oss Acceleration enabled. This is necessary because only then will all uploads and downloads go directly to this variable, rather than using the concatenated address, which in the current version has the S3 identifier, which prevents access to oss
  AWS_S3_ACCELERATE_URL: http://<bucket_name>.oss-accelerate.aliyuncs.com
  AWS_S3_UPLOAD_MAX_SIZE: "26214400"
  AWS_S3_FORCE_PATH_STYLE: "false"
  # This is not an oss bucket policy, So you don't need to set a bucket level policy. But a file object permission set after uploading a file via ram ak, which has three values, public-read-write, public-read, and private. For security reasons, be sure to use private here. Don't worry about losing access to the outline, which passes ${AWS_S3_ACCELERATE_URL}/xyz  + signature for secure access, signature permissions from ram ak.
  AWS_S3_ACL: private
```
