### DISCUSSION TITLE
Docker "Failed to obtain access token" with Slack and Authelia

### DISCUSSION THREAD

**Discussion by Josef-99** [outline/outline#4977] [Self Hosting] [answered]
I'm trying to run a Outline Instance in a Docker Environment on a local network. 

Setting up each docker container with **docker compose** works very well, but during login the follwing error message appears:

```
{
  "error":"Failed to obtain access token",
  "stack":"Error: Failed to obtain access token\n
      at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:178:49\n
      at /opt/outline/node_modules/oauth/lib/oauth2.js:209:7\n
      at passBackControl (/opt/outline/node_modules/oauth/lib/oauth2.js:134:9)\n
      at IncomingMessage.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:157:7)\n
      at IncomingMessage.emit (node:events:538:35)\n
      at IncomingMessage.emit (node:domain:475:12)\n
      at endReadableNT (node:internal/streams/readable:1345:12)\n
      at processTicksAndRejections (node:internal/process/task_queues:83:21)",
  "level":"error",
  "message":"Error during authentication"
}
```

with the URL: https://example-dns.entry/?notice=auth-error
![image](https://user-images.githubusercontent.com/59767499/222905847-5c802568-4df7-4cec-8193-4ee54f210745.png)

I have already done research on Github, Stackoverflow and Google, and considered the following:
- https://github.com/outline/outline/discussions/3501
- https://github.com/outline/outline/discussions/3495
- https://github.com/outline/outline/discussions/3478
- https://github.com/outline/outline/discussions/2942

After accepting that it probably won't work with Slack, I set up an authelia docker container, but the same error message appeared again.

Here's my docker-compose.yml: 
```
version: "3"

services:

  outline:
    image: outlinewiki/outline #Version 0.68.1
    hostname: outline
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    image: postgres
    hostname: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'usertest'
      POSTGRES_PASSWORD: 'passtest'
      POSTGRES_DB: 'outline'

  storage:
    image: minio/minio
    hostname: redis
    env_file: ./docker.env
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    environment:
      # Public DNS Entry -> Local IP-Adress (from Docker Server)
      DOMAINS: 'example-dns.entry -> http://192.168.2.16:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

My docker.env - File:
```
SECRET_KEY=generated through openssl rand -hex 32
UTILS_SECRET=generated through openssl rand -hex 32

#POSTGRES
DATABASE_URL=postgres://usertest:passtest@192.168.2.16:5432/outline?sslmode=disable
DATABASE_URL_TEST=postgres://usertest:passtest@192.168.2.16:5432/outline-test?sslmode=disable
DATABASE_CONNECTION_POOL_MIN=2
DATABASE_CONNECTION_POOL_MAX=4
PGSSLMODE=disable

#REDIS
REDIS_URL=redis://192.168.2.16:6379

URL=https://example-dns.entry
PORT=3000

AWS_ACCESS_KEY_ID=<key id>
AWS_SECRET_ACCESS_KEY=<key secret>
AWS_REGION=local
# AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=http://192.168.2.16:9000
AWS_S3_UPLOAD_BUCKET_NAME=wiki
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private


SLACK_CLIENT_ID=Copied from api.slack.com
SLACK_CLIENT_SECRET=Copied from api.slack.com
```

I tried different configurations, and finally went back to the configuration as described on [wiki.generaloutline.com](https://wiki.generaloutline.com/s/hosting/doc/docker-7pfeLP5a8t), with small changes and without the healthcheck, unfortunately the login didn't work with it either. 

In Slack I have added the scopes and the URLs.

Thanks in advance.
