### DISCUSSION TITLE
Need help with Self-hosting outline

### DISCUSSION THREAD

**Discussion by RitZz48** [outline/outline#5254] [Self Hosting]
Heya, I recently installed Outline through Docker on my home server. Here are the details:

Docker-compose:
```
version: "3"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: stack.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: stack.env
    ports:
      - "6379:6379"
    volumes:
      - /home/ritzz/server/outline/redis:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: stack.env
    ports:
      - "5432:5432"
    volumes:
      - /home/ritzz/server/outline/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  storage:
    image: minio/minio
    env_file: stack.env
    ports:
      - "9444:9000"
    entrypoint: sh
    command: -c 'minio server'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /home/ritzz/server/outline/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9444/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  https-portal:
    image: steveltn/https-portal
    env_file: stack.env
    ports:
      - '8987:80'
      - '9446:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - /home/ritzz/server/outline/portal:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'docs.mycompany.com -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
```

Environment file: 
```
NODE_ENV=production
SECRET_KEY=<secret_key_redacted>
UTILS_SECRET=<utils_secret_redacted>
DATABASE_URL=postgres://user:pass@localhost:5432/outline
DATABASE_URL_TEST=postgres://user:pass@localhost:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
REDIS_URL=redis://0.0.0.0:6379
URL=http://0.0.0.0:3000
PORT=3000
COLLABORATION_URL=
GOOGLE_CLIENT_ID=<client_id_redacted>
GOOGLE_CLIENT_SECRET=<client_secret_redacted>
SSL_KEY=
SSL_CERT=
FORCE_HTTPS=true
ENABLE_UPDATES=true
WEB_CONCURRENCY=1
MAXIMUM_IMPORT_SIZE=5120000
DEBUG=http
LOG_LEVEL=info
GOOGLE_ANALYTICS_ID=
SENTRY_DSN=
SENTRY_TUNNEL=
SMTP_HOST=
SMTP_PORT=
SMTP_USERNAME=
SMTP_PASSWORD=
SMTP_FROM_EMAIL=hello@example.com
SMTP_REPLY_EMAIL=hello@example.com
SMTP_TLS_CIPHERS=
SMTP_SECURE=true
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

Now after deploying the stack the Outline container is 'exited' with the following log :

```
yarn run v1.22.19
$ node ./build/server/index.js
INF 
Is your team enjoying Outline? Consider supporting future development by sponsoring the project:

https://github.com/sponsors/outline
 | label=lifecycle
ERROR: connect ECONNREFUSED 127.0.0.1:5432
error Command failed with exit code 1.
WRN Could not connect to the database. Please check your connection settings. 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I am not sure what to do here. Please help me out!
