### DISCUSSION TITLE
Unable to store files on Digital Ocean Spaces

### DISCUSSION THREAD

**Discussion by TylerMills** [outline/outline#5326] [Self Hosting]
I've followed the instructions exactly in the documentation and have tried dozens of permutations and I feel like I'm missing something obvious here.

**To Reproduce**
1. Use the following configuration in `docker.env`:

```
AWS_ACCESS_KEY_ID=123
AWS_SECRET_ACCESS_KEY=XYZ
AWS_REGION=nyc3 
AWS_S3_UPLOAD_BUCKET_URL=https://nyc3.digitaloceanspaces.com
AWS_S3_UPLOAD_BUCKET_NAME=mybucketname
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=false
AWS_S3_ACL=private
AWS_S3_ACCELERATE_URL=https://nyc3.digitaloceanspaces.com
```

Things I've also tried:
- Variations of BUCKET_URL that include the region and bucket as the docs say
- AWS_REGION = us-east-1
- commenting out the ACCELERATE_URL
- Commenting out variations of other fields as much as possible
- Removing all firewalls & ACL rules

**Expected behavior**
Files should upload successfully.

**Screenshots**
My settings in Digital Ocean:
![CleanShot 2023-05-09 at 00 28 44@2x](https://user-images.githubusercontent.com/7108676/236994168-2833482f-3a02-4d3f-bf62-3fa297c4b648.png)

My errors in network console:
<img width="680" alt="CleanShot 2023-05-09 at 00 30 36@2x" src="https://user-images.githubusercontent.com/7108676/236994371-145eaac2-5a45-4c7d-afb0-968911b06137.png">

**Outline (please complete the following information):**
- Install: self-hosted latest

**Desktop (please complete the following information):**
 - OS: Ubuntu LTS
 - Browser: Chrome
 - Version: Latest, non-Beta

**Comment by TylerMills** [comment]
I believe I found the cause... but haven't fixed it yet.

I think the issue is due to the fact that I was using CloudFlare for SSL and not the built in SSL functionality, this causes redirects that are considered insecure and are blocked from the frontend.

This link has more information about what browsers expect: https://stackoverflow.com/questions/18995845/aws-s3-cors-403-error-with-options-request

**Comment by denismorozov** [comment]
@TylerMills I'm not sure if you're still struggling with this or not, but noting just in-case this is helpful for others.

The order of the CORS rules in Digital Ocean Spaces matters. I had to put the catch-all GET rule last:

<img width="1290" alt="do-spaces-cors-order" src="https://github.com/outline/outline/assets/8063291/c54902f3-2052-4cf8-8f42-29451c344bb3">

In the UI you can drag the rules to order them, or w/ Terraform use `digitalocean_spaces_bucket_cors_configuration` "id" attribute.

```terraform
resource "digitalocean_spaces_bucket" "outline" {
  name   = "example-com-outline"
  region = var.region
  acl = "public-read"
}

resource "digitalocean_project_resources" "outline" {
  project = var.project_id
  resources = [
    digitalocean_spaces_bucket.outline.urn
  ]
}

resource "digitalocean_spaces_bucket_cors_configuration" "outline" {
  bucket = digitalocean_spaces_bucket.outline.id
  region = digitalocean_spaces_bucket.outline.region

  # the order of the rules matters, setting "id" seems to control the order:

  cors_rule {
    id              = "10"
    allowed_headers = ["*"]
    allowed_methods = ["PUT", "POST"]
    allowed_origins = ["https://docs.example.com"]
    expose_headers  = []
  }

  cors_rule {
    id              = "20"
    allowed_headers = []
    allowed_methods = ["GET"]
    allowed_origins = ["*"]
    expose_headers  = []
  }
}


resource "digitalocean_spaces_bucket_policy" "outline" {
  bucket = digitalocean_spaces_bucket.outline.name
  region = digitalocean_spaces_bucket.outline.region
  policy = jsonencode({
    "Version" : "2012-10-17",
    "Statement" : [
      {
        "Sid" : "VisualEditor",
        "Effect" : "Allow",
        "Action" : [
          "s3:GetObjectAcl",
          "s3:DeleteObject",
          "s3:PutObject",
          "s3:GetObject",
          "s3:PutObjectAcl"
        ]
        "Resource" : [
          "arn:aws:s3:::${digitalocean_spaces_bucket.outline.name}",
          "arn:aws:s3:::${digitalocean_spaces_bucket.outline.name}/*"
        ]
      }
    ]
  })
}

```

For completeness, my Outline config:
```yaml
  AWS_REGION: "sfo3"
  # uploading to docs did not work without ACCELERATE_URL being set, but profile picture upload worked
  # see: https://github.com/outline/outline/discussions/2635
  AWS_S3_ACCELERATE_URL: "https://example-com-outline.sfo3.digitaloceanspaces.com"
  AWS_S3_UPLOAD_BUCKET_URL: "https://example-com-outline.sfo3.digitaloceanspaces.com"
  AWS_S3_UPLOAD_BUCKET_NAME: "example-com-outline"
  AWS_S3_FORCE_PATH_STYLE: "false"
  AWS_S3_ACL: "private"
  # + the secret keys
```

edit: despite [the docs](https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7) saying bucket has to be public, mine seems to be working fine with it being private as well (i.e. `acl = 'private'`).
