### DISCUSSION TITLE
Unable to sign in with OIDC (keycloak)

### DISCUSSION THREAD

**Discussion by raphih18** [outline/outline#5388] [Self Hosting]
Deploy environment

| Service | Usage| Type | Domain|
|--------|--------|--------|--------|
| Outline | -| Docker Compose | wiki.pcslab.ch |
| Keycloak | OIDC Provider| Docker Compose (seperately from Outline) | auth.pcslab.ch |
| Nginx | Webserver (reverse proxy) | Native (barebone) | -| 

- Minio used as self-hosted s3 storage
- The usual dependencies (redis, postgres)

Setup Information:
-> All services installed on the same host (Ubuntu 22.04 LTS)
-> Public DNS A-records pointing to the public IP of the firewall, NATting towards Ubuntu host, allowed ports 80, 443 in the firewall.
-> Self-signed SSL certificates using certbot
-> All setup by using this tutorial: https://wenkdth.org/posts/keycloak-outline-setup/

**PROBLEM:**
Accessing outline via wiki.pcslab.ch works like a charm. Then choosing OIDC auth method and entering the correct details results in 502 bad gateway and not being redirect via oidc.callback back to Outline. Outline shows the following error in the log files:
`"stack":"Error: connect ETIMEDOUT 146.4.81.212:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)"} {"error":"connect ETIMEDOUT 146.4.81.212:443","level":"error","message":"`

This is the error i get from nginx:
```
*384 upstream prematurely closed connection while reading response header from upstream, client: 178.196.163.235, server: wiki.pcslab.ch, request: "GET /auth/oidc.callback?state=937abd03ecf6baa0&session_state=f998a40c-3115-4ad6-a3f3-4038fc609e32&code=bee6a1b7-7be3-4c7c-974c-1fa86f5d0869.f998a40c-3115-4ad6-a3f3-4038fc609e32.aecf4dda-acb1-46f1-b375-3d5c024b032a HTTP/1.1", upstream: "http://127.0.0.1:7215/auth/oidc.callback?state=937abd03ecf6baa0&session_state=f998a40c-3115-4ad6-a3f3-4038fc609e32&code=bee6a1b7-7be3-4c7c-974c-1fa86f5d0869.f998a40c-3115-4ad6-a3f3-4038fc609e32.aecf4dda-acb1-46f1-b375-3d5c024b032a", host: "wiki.pcslab.ch"
``` 

So now, I tried everything and couldn't get it to work because I do now know what causes the Timeout or the buffer being closed prematurely.
I hope anyone ran into the same problem and can share their knowledge with me.

Thanks!

### Outline Setup
**docker-compose.yml**
```
version: "3"
services:

  outline:
    image: outlinewiki/outline:0.69.2
    env_file: ./docker.env
    networks:
      - outline-network
    ports:
      - "7215:3000"
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_started
      minio:
          condition: service_started
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"

  redis:
    image: redis
    env_file: ./docker.env
    networks:
      - outline-network
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    image: postgres
    env_file: ./docker.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - outline-network
    volumes:
      - outline-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2023-05-18T00-05-36Z
    env_file: ./docker.env
    networks:
      - outline-network
    ports:
      - "7216:9000"
      - "9001:9001"
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - outline-minio-data:/data
    entrypoint: sh
    command: -c 'minio server --console-address ":9001" /data'


volumes:
  outline-minio-data:
  outline-postgres-data:

networks:
  outline-network:
    name: outlinewiki-network

``` 

**docker.env**
```
# Generated with"openssl rand -hex 32".
SECRET_KEY=<key1>
UTILS_SECRET=<key2>

# Please see "Enviroment Variables" for more information.
# Make sure to change "user" and "pass".
POSTGRES_USER=outline
POSTGRES_PASSWORD=totalsecurepassword
POSTGRES_DB=outline

DATABASE_URL=postgres://outline:totalsecurepassword@postgres:5432/outline
# Was in the official Docker.env. Probably not needed?
DATABASE_URL_TEST=postgres://outline:totalsecurepassword@postgres:5432/outline-test

URL=https://wiki.pcslab.ch

# Please see "Enviroment Variables" for more information.
# Make sure to change "user" and "pass".
MINIO_ROOT_USER=minio_admin
MINIO_ROOT_PASSWORD=totalsecurepassword

# You will need to get this from the Minio admin panel.
AWS_ACCESS_KEY_ID=<minio access key id>
AWS_SECRET_ACCESS_KEY=<minio access key secret>
AWS_REGION=CH-emmen

AWS_S3_UPLOAD_BUCKET_URL=https://data.pcslab.ch
AWS_S3_UPLOAD_BUCKET_NAME=outline
AWS_S3_UPLOAD_MAX_SIZE=26214400
## Probably shouldn't change these
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private

# You will need to get this from the Keycloak admin panel. Please see "Keycloak OIDC Setup".
OIDC_CLIENT_ID=outline-wiki
OIDC_CLIENT_SECRET=<keycloak oidc secret>
OIDC_AUTH_URI=https://auth.pcslab.ch/realms/outline/protocol/openid-connect/auth
OIDC_TOKEN_URI=https://auth.pcslab.ch/realms/outline/protocol/openid-connect/token
OIDC_USERINFO_URI=https://auth.pcslab.ch/realms/outline/protocol/openid-connect/userinfo
## Changes what shows up on the login button.
OIDC_DISPLAY_NAME=Keycloak
## Probably shouldn't change
OIDC_USERNAME_CLAIM=preferred_username
OIDC_SCOPES=openid profile email

ENABLE_UPDATES=false
WEB_CONCURRENCY=1
``` 
**nginx wiki.pcslab.ch vhost**
```
server {
        server_name wiki.pcslab.ch;
        listen 443 ssl;

        ssl_certificate /etc/letsencrypt/live/wiki.pcslab.ch/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/wiki.pcslab.ch/privkey.pem;
        include /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        access_log /var/log/nginx/wiki-access.log;
        error_log /var/log/nginx/wiki-error.log info;

        # SSO requests tend to be very long, will fail on default settings.
        #proxy_buffer_size 12k;
        proxy_buffering off;

          location / {
                proxy_pass http://localhost:7215/;

                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;proxy_set_header Host $host;
                proxy_set_header Host $http_host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Scheme $scheme;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
        }
#        ## SIMPLE HTML WELCOME PAGE (FOR DEBUGGING)
#        root /var/www/pcslab.ch/wiki/html;
#        index index.html index.htm index.nginx-debian.html;
#
#        location / {
#                try_files $uri $uri/ =404;
#        }
}

server {
        server_name wiki.pcslab.ch;
        listen 80;

        if ($host = wiki.pcslab.ch) {
                return 301 https://$host$request_uri;
        }

        return 404;
}
```
