### DISCUSSION TITLE
Can't connect to postgres database (same host)

### DISCUSSION THREAD

**Discussion by Compr0mzd** [outline/outline#5411] [Self Hosting] [answered]
I have a portainer instance where I create all of my docker.
I decided to create a postgres and redis docker dedicated to all of my services and edited the docker compose of outline to remove the dedicated ones : 
This is the docker compose after modifying it : 
```version: "3"
services:
  outline:
    image: outlinewiki/outline:latest
    ports:
      - "127.0.0.1:3000:3000"
    command: sh -c "yarn start --env=production-ssl-disabled --net=host"
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - REDIS_URL=redis://localhost:6379
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/**REDACTED**
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_USERNAME_CLAIM=email
      - URL=${URL}
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${DATA_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=${BUCKET_NAME}
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private 
     
```
However after starting the stack I get the error  :
```
yarn run v1.22.19
$ node ./build/server/index.js --env=production-ssl-disabled --net=host
INF Note: Restricting process count to 1 due to use of collaborative service | label=lifecycle 
INF 
Is your team enjoying Outline? Consider supporting future development by sponsoring the project:

https://github.com/sponsors/outline
 | label=lifecycle 
ERROR: connect ECONNREFUSED 127.0.0.1:5432
error Command failed with exit code 1.
WRN Could not connect to the database. Please check your connection settings. 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I tried connecting to the postgres database without any issues : 
`psql -h localhost -p 5432 -d  **REDACTED** -U **REDACTED** -W`
I had no issues with that command and was able to connect to the postgres database

I even used the same command used in the docker compose :
`psql "postgres://**REDACTED**:**REDACTED**@localhost:5432/**REDACTED**"`
And again no issues connecting to it. I didn't use any special network, I use the bridge one. Outline does not have any issues connecting to Redis either. 
Is there any way I can get more logs from the docker or debug the issue ?
Did you encounter a similar problem ?

Would appreciate it ! 

Thanks in advance

**Comment by Marshyp** [comment]
I get the exact same error myself.

**Reply by jenny787** [reply]
me too

**Reply by Marshyp** [reply]
@jenny787 / @Compr0mzd - I have rectified this on my own instance.
See my guide here : https://sysadmins.zone/topic/35/how-to-install-outline -- Specifically the section "If you get an error"

**Reply by Compr0mzd** [reply]
> @jenny787 / @Compr0mzd - I have rectified this on my own instance.
> See my guide here : https://sysadmins.zone/topic/35/how-to-install-outline -- Specifically the section "If you get an error" 
> 

Well I checked your guide and the issue is that I have created the database myself, and i run the docker on the same host but not on the same dockerfile so it can't work that way unfortunately

**Reply by Marshyp** [reply]
> > @jenny787 / @Compr0mzd - I have rectified this on my own instance.
> > See my guide here : https://sysadmins.zone/topic/35/how-to-install-outline -- Specifically the section "If you get an error"
> 
> Well I checked your guide and the issue is that I have created the database myself, and i run the docker on the same host but not on the same dockerfile so it can't work that way unfortunately

Do you have a copy of your docker.env @Compr0mzd - You should be able to run similar regardless and it work. Happy to take a look.

**Reply by jenny787** [reply]
@Marshyp Thank you, I will try your guide.  it is the shortest one yet!  I do have a question for your domain prep...are you installing on a server open to the public?  I have tried this with first setting the domains as many guides say, before doing the installation.  I have tried with nginx reverse proxy.  But i figure with the https-portal, i dont need the reverse proxy?  This is such a complicated setup.

**Reply by jenny787** [reply]
I still get the ERROR: connect ECONNREFUSED 127.0.0.1:5432 no matter what.  i am also using "docker compose' command because "docker-compose" doesn't work at all I get many lines of error with the dash compose.

**Reply by Marshyp** [reply]
> @Marshyp Thank you, I will try your guide. it is the shortest one yet! I do have a question for your domain prep...are you installing on a server open to the public? I have tried this with first setting the domains as many guides say, before doing the installation. I have tried with nginx reverse proxy. But i figure with the https-portal, i dont need the reverse proxy? This is such a complicated setup.

I have mine open to the public, it sits behind an NGinx reverse proxy (I am using NGinx Proxy Manager for mine).
Happy to assist you where I can - Do you have an account at the above site (where the guide is)? - It may be easier to post it there and then migrate the findings here so that we can keep this thread to the full fix rather than the journey and spamming everyone's notification.

**Reply by edgarwideman** [reply]
Coming here with the same issue... sorta 
```
Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".

ERROR: connect ECONNREFUSED 127.0.0.1:5432

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: 1
```
Fresh Ubuntu 22.04 install, following [this](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t)  guide. Had pre-installed Postgres and Redis, but got conflicts saying the service is being used elsewhere, or something along that line. Uninstalled them, got farther but now stuck with above error. according to `lsof -i:5432` shows 2 services running? I really don't know what I am doing here.
```
docker-pr 19412 root    4u  IPv4  89922      0t0  TCP *:postgresql (LISTEN)
docker-pr 19418 root    4u  IPv6  89939      0t0  TCP *:postgresql (LISTEN)
```

**Comment by Compr0mzd** [comment]
> > > @jenny787 / @Compr0mzd - I have rectified this on my own instance.
> > > See my guide here : https://sysadmins.zone/topic/35/how-to-install-outline -- Specifically the section "If you get an error"
> > 
> > 
> > Well I checked your guide and the issue is that I have created the database myself, and i run the docker on the same host but not on the same dockerfile so it can't work that way unfortunately
> 
> Do you have a copy of your docker.env @Compr0mzd - You should be able to run similar regardless and it work. Happy to take a look.

On the first message you see the entire docker compose for the Oultine Stack. My postgres db is just a standalone docker where I created the database, user, password by hand using shell.

**Comment by hiepxanh** [comment]
I have the same issue, did anyone else can run it can connect to database?

**Comment by jinwyp** [comment]
same issue

```
docker-outline-1  | Please migrate your code to use AWS SDK for JavaScript (v3).
docker-outline-1  | For more information, check the migration guide at https://a.co/7PzMCcy
docker-outline-1  | (Use `node --trace-warnings ...` to show where the warning was created)
docker-outline-1  | {"level":"warn","message":"Could not connect to the database. Please check your connection settings."}
docker-outline-1  | error Command failed with exit code 1.
docker-outline-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

docker-compose.yml

```

version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    ports:
      - "300:3000"
    depends_on:
      - postgres
      - redis
      - storage
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=b494b7537b124c6ebb539bb785be4397c00c55cb6ef64e69f5b460d8bfc9f190
      - UTILS_SECRET=86e78d11646900620bbfdcbe1192db16ef7d1e2b3e340633d74c6fc40b59f53f
      - REDIS_URL=redis://localhost:6379
      - DATABASE_URL=postgres://postgreuseradmin:postgreuseradminpw@localhost:5432/outlinedb
      - URL=http://localhost:3000
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadminpw
      - AWS_REGION=us-east-1
      - AWS_S3_UPLOAD_BUCKET_URL=http://127.0.0.1:9000
      - AWS_S3_UPLOAD_BUCKET_NAME=wiki
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - /root/outline/docker/redis/redis_data/:/data
    command: ["redis-server" ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3


  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      -  /root/outline/docker/postgres/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outlinedb", "-U", "postgreuseradmin"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'postgreuseradmin'
      POSTGRES_PASSWORD: 'postgreuseradminpw'
      POSTGRES_DB: 'outlinedb'

  storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /root/outline/docker/minio/storage_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw



  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add myminio http://storage:9000 minioadmin minioadminpw;
      /usr/bin/mc mb myminio/wiki;
      /usr/bin/mc policy set public myminio/wiki;
      exit 0;
      "

  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - /root/outline/docker/https_portal:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'ot.freair.com -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'


```
