### DISCUSSION TITLE
Unable to run the Container

### DISCUSSION THREAD

**Discussion by adyabajpai21** [outline/outline#5430] [Self Hosting]
I am trying to setup outline with the docker on an ec2 instance: 

```
NODE_ENV=production

SECRET_KEY={Key}

UTILS_SECRET={Key}

DATABASE_URL=postgres://{uname}:{pass}@{Public Ip}:5432/{dbname}
DATABASE_URL_TEST=postgres://{uname}:{pass}@{Public Ip}:5432/{dbname}

REDIS_URL=redis://{Public Ip}:6379

URL=http://{Public Ip}:3000
PORT=3000

AWS_ACCESS_KEY_ID={Key}
AWS_SECRET_ACCESS_KEY={Key}
AWS_REGION=ap-south-1
```

docker-compose.yml File:

```
version: "3"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER:{uname}
      POSTGRES_PASSWORD: {pass}
      POSTGRES_DB: {dbname}

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'minio server'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://{Public IP}:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'docs.mycompany.com -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

I am following the [official documentation](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t). Each command is running successfully, but when I try to run the outline image, it gives me the following error: 

```
 ubuntu@ip-172-31-41-163:~$ sudo docker run c46db92492e3
yarn run v1.22.19
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- SECRET_KEY's byte length must fall into (32, 64) range"}
{"level":"warn","message":"- UTILS_SECRET should not be empty"}
{"level":"warn","message":"- DATABASE_URL must be a URL address, DATABASE_URL should not be empty"}
{"level":"warn","message":"- REDIS_URL should not be empty"}
{"level":"warn","message":"- URL must be a URL address, URL should not be empty"}
error Command failed with exit code 1.
```

Kindly help me rectify this error, as I am a newbie and I have a feeling that I must be missing out on a very basic detail that is causing this error.
