### DISCUSSION TITLE
aliyun oss secure configure

### DISCUSSION THREAD

**Discussion by Spinestars** [outline/outline#5442] [Show and tell] [answered]
outline version： 0.69.2

After many attempts, the following requirements were finally realized:
1. aliyun oss policies are private
2. Objects uploaded to oss are private
3. Access oss objects in signature mode

```
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 
  # This is a region id, not a region id for a service, and service identifiers, such as oss, should not be added
  AWS_REGION: cn-beijing
  AWS_S3_UPLOAD_BUCKET_NAME: <bucket_name>
  AWS_S3_UPLOAD_BUCKET_URL: http://<bucket_name>.oss-cn-beijing.aliyuncs.com
  # This is not a CDN address! Oss Acceleration enabled. This is necessary because only then will all uploads and downloads go directly to this variable, rather than using the concatenated address, which in the current version has the S3 identifier, which prevents access to oss
  AWS_S3_ACCELERATE_URL: http://<bucket_name>.oss-accelerate.aliyuncs.com
  AWS_S3_UPLOAD_MAX_SIZE: "26214400"
  AWS_S3_FORCE_PATH_STYLE: "false"
  # This is not an oss bucket policy, So you don't need to set a bucket level policy. But a file object permission set after uploading a file via ram ak, which has three values, public-read-write, public-read, and private. For security reasons, be sure to use private here. Don't worry about losing access to the outline, which passes ${AWS_S3_ACCELERATE_URL}/xyz  + signature for secure access, signature permissions from ram ak.
  AWS_S3_ACL: private
```
2. Cross-domain configuration
![image](https://github.com/outline/outline/assets/7272900/af3c4646-48d7-484c-8098-d2d4c80f4279)

3. ram policy for ak
```
{
    "Version": "1",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "oss:ListBuckets",
                "oss:GetBucketStat",
                "oss:GetBucketInfo",
                "oss:GetBucketTagging",
                "oss:GetBucketAcl"
            ],
            "Resource": "acs:oss:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "oss:ListObjects",
                "oss:GetBucketAcl"
            ],
            "Resource": "acs:oss:*:*:<bucket_name>"
        },
        {
            "Effect": "Allow",
            "Action": [
                "oss:GetObject*",
                "oss:DeleteObject*",
                "oss:PutObject*",
                "oss:RestoreObject*"
            ],
            "Resource": "acs:oss:*:*:<bucket_name>/*"
        }
    ]
}
```
