### DISCUSSION TITLE
Docker container dies without error message

### DISCUSSION THREAD

**Discussion by simonfrey** [outline/outline#5492] [Self Hosting]
When I start up the docker container (outlinewiki/outline:0.69.2) it runs until the 

```bash

{"label":"database","level":"debug","message":"Executing (default): SELECT count(*) AS \"count\" FROM \"documents\" AS \"document\" LEFT OUTER JOIN \"users\" AS \"createdBy\" ON \"document\".\"createdById\" = \"createdBy\".\"id\" LEFT OUTER JOIN \"users\" AS \"updatedBy\" ON \"document\".\"lastModifiedById\" = \"updatedBy\".\"id\" WHERE (\"document\".\"deletedAt\" IS NULL AND \"document\".\"publishedAt\" IS NOT NULL);"}
```
and then dies without any error messsage. Any idea how I could debug this?

---
I run it within kubernetes with the following deployment

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: outline
    owner: infra
  name: outline
  namespace: infra
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: outline
      owner: infra
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      creationTimestamp: null
      labels:
        app: outline
        owner: infra
    spec:
      containers:
      - env: # ENV based on https://github.com/outline/outline/blob/main/.env.sample
        - name: NODE_ENV
          value: production
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY
              name: outline-secrets
        - name: UTILS_SECRET
          valueFrom:
            secretKeyRef:
              key: UTILS_SECRET
              name: outline-secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: outline-database-url
        - name: PGSSLMODE
          value: disable
        - name: REDIS_URL
          value: redis://10.164.158.147:6379 # stage-outline google managed redis
        - name: URL
          value: https://mydomain.com/outline
        - name: PORT
          value: "3000"
        - name: FORCE_HTTPS
          value: "false"
        - name: ENABLE_UPDATES
          value: "false"
        - name: WEB_CONCURRENCY # How many processes should be spawned. As a reasonable rule divide your servers available memory by 512 for a rough estimate
          value: "1"
        - name: LOG_LEVEL
          value: "silly"
        - name: AWS_REGION
          value: eu
        - name: AWS_S3_UPLOAD_BUCKET_NAME
          value: stage-outline
        - name: AWS_S3_UPLOAD_BUCKET_URL
          value: https://www.googleapis.com/storage/v1/b/stage-outline
        - name: AWS_S3_ACCELERATE_URL
          value: https://www.googleapis.com/storage/v1/b/stage-outline
        - name: AWS_S3_UPLOAD_MAX_SIZE
          value: "26214400"
        - name: AWS_S3_FORCE_PATH_STYLE
          value: "false"
        - name: AWS_S3_ACL
          value: private
        image: outlinewiki/outline:0.69.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: outline
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
        securityContext:
          capabilities:
            drop:
            - SETPCAP
            - MKNOD
            - AUDIT_WRITE
            - CHOWN
            - NET_RAW
            - DAC_OVERRIDE
            - FOWNER
            - FSETID
            - KILL
            - SETGID
            - SETUID
            - NET_BIND_SERVICE
            - SYS_CHROOT
            - SETFCAP
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /home/node
            name: nodecache
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        env:
          - name: INSTANCE_CONNECTION_NAME
            value: "data:europe:stage-outlinedb"
        command:
          - "/cloud_sql_proxy"
          - "-instances=$(INSTANCE_CONNECTION_NAME)=tcp:5432"
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 250m
            memory: 2Gi
          requests:
            cpu: 50m
            memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccount: outline
      serviceAccountName: outline
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: tmp
        - emptyDir:
            medium: Memory
          name: nodecache
status: {}
```
