### DISCUSSION TITLE
Outline running from Docker fetches files from port 3001 despite being configured for port 3000

### DISCUSSION THREAD

**Discussion by jonasjancarik** [outline/outline#5578] [Self Hosting] [answered]
I'm attempting to self-host Outline in a local staging environment using Docker. While Outline is configured to serve from http://localhost:3000, it's attempting to fetch some files from localhost:3001 (e.g., http://localhost:3001/static/@vite/client or http://localhost:3001/static/app/index.tsx). This results in only the HTML skeleton loading and nothing rendered in the browser.

My docker-compose.yml and docker.env files are configured as closely as possible to the [docs](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t). However, I've made some changes for my local staging environment, and while they've helped me proceed, I'm not entirely confident they're correct. One example is the addition of /data to the command for the Minio service, without which it would fail.

I'm unsure why Outline is attempting to fetch files from port 3001 when it should be operating exclusively on port 3000 according to my configuration. It's possible I am missing something obvious.

Currently, with this config, accessing Outline at http://localhost:8888 (through `https-portal`) doesn't work as it tries to redirect to `https://localhost/` (and I have nothing listening on port 443). But it should still work over http://localhost:3000, I believe.

```
version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5138:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "4586:9000"
    entrypoint: sh
    command: -c 'minio server /data'  # it would fail without adding /data, even though the version in the docs doesn't include this https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '8888:80'
      - '4433:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      # running on localhost
      DOMAINS: 'localhost -> http://outline:3000'
      STAGE: 'local'
      WEBSOCKET: 'true'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

`docker.env`:

```
NODE_ENV=development
SECRET_KEY=94628b4ba...
UTILS_SECRET=4993cd765...
DATABASE_URL=postgres://user:pass@postgres:5432/outline
DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
PGSSLMODE=disable
REDIS_URL=redis://redis:6379
URL=http://localhost:3000
PORT=3000
COLLABORATION_URL=
DEFAULT_LANGUAGE=en_US
```
