### DISCUSSION TITLE
RangeError: Invalid time value

### DISCUSSION THREAD

**Discussion by min9538p** [outline/outline#5696] [Self Hosting] [answered]
While testing the outline wiki, I got the following error. Does anyone know how to fix it?

docker-compose.yml
```
services:
  outline_redis:
    image: redis
    restart: always
    container_name: outline_redis
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:15
    restart: always
    container_name: outline_postgres
    security_opt:
      - label:disable
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    networks:
      - outline-internal
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  outline_minio:
    image: minio/minio
    restart: always
    container_name: outline_minio
    security_opt:
      - label:disable
    volumes:
      - ./container-data/data:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
    # ports:
      # - 9000:9000
      # - 9001:9001
    networks:
      - reverseproxy-nw
    command: "server /data --console-address :9001"

  outline:
    image: docker.getoutline.com/outlinewiki/outline-enterprise:latest
    user: root
    restart: always
    container_name: outline
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    environment:
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline_postgres:5432/outline
      - REDIS_URL=redis://outline_redis:6379
      - URL=${WIKI_URL}
      - PORT=80
      - AWS_ACCESS_KEY_ID=minio
      - AWS_REGION=us-east-1
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - AWS_S3_UPLOAD_BUCKET_URL=${WIKIDATA_URL}
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_REPLY_EMAIL=${SMTP_REPLY_EMAIL}
      - SMTP_SECURE=${SMTP_SECURE}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_USERNAME_CLAIM=email
      - LICENSE_KEY=./KIMB_LICENSE_KEY
    # ports:
    #   443:443
    networks:
      - outline-internal
      - reverseproxy-nw
networks:
  outline-internal:
  reverseproxy-nw:
    external: true
```

.env
```
SECRET_KEY={SECRET_KEY}

UTILS_SECRET={UNIT_SECRET}

MINIO_ROOT_PASSWORD={MINIO_ROOT_PASSWD}
POSTGRES_PASSWORD={POSTGRES_PW}

MINIO_BROWSER_REDIRECT_URL=https://kbdata-admin.{URL}
WIKI_URL=https://kb.{URL}
WIKIDATA_URL=https://kbdata.{URL}

# To support sending outgoing transactional emails such as "document updated" or
# "you've been invited" you'll need to provide authentication for an SMTP server
SMTP_HOST={SMTP_HOST}
SMTP_PORT=587
SMTP_USERNAME={MAIL_ID}
SMTP_PASSWORD={MAIL_PW}
SMTP_FROM_EMAIL={EMAIL}
SMTP_REPLY_EMAIL={EMAIL}
SMTP_SECURE=true

#oidc information
OIDC_CLIENT_ID=kb.{URL}
OIDC_CLIENT_SECRET={OIDC_SECRET}
OIDC_AUTH_URI=https://auth.{URL}/realms/master/protocol/openid-connect/auth
OIDC_TOKEN_URI=https://auth.{URL}/realms/master/protocol/openid-connect/token
OIDC_USERINFO_URI=https://auth.{URL}/realms/master/protocol/openid-connect/userinfo
OIDC_DISPLAY_NAME=Keycloak
```

Error
```
outline           | yarn run v1.22.19
outline           | $ node ./build/server/index.js
outline           | {"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
outline           | (node:28) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
outline           | 
outline           | Please migrate your code to use AWS SDK for JavaScript (v3).
outline           | For more information, check the migration guide at https://a.co/7PzMCcy
outline           | (Use `node --trace-warnings ...` to show where the warning was created)
outline           | /opt/outline/node_modules/date-fns/format/index.js:357
outline           |     throw new RangeError('Invalid time value');
outline           |           ^
outline           | 
outline           | RangeError: Invalid time value
outline           |     at format (/opt/outline/node_modules/date-fns/format/index.js:357:11)
outline           |     at checkLicense (/opt/outline/build/server/utils/startup.js:69:158)
outline           |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
outline           |     at async master (/opt/outline/build/server/index.js:57:3)
outline           |     at async throng (/opt/outline/node_modules/throng/lib/throng.js:31:3)
outline           | 
outline           | Node.js v18.16.1
outline_postgres  | 2023-08-17 13:43:50.804 KST [36] LOG:  could not receive data from client: Connection reset by peer
outline           | error Command failed with exit code 1.
outline           | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
