### DISCUSSION TITLE
Docker exits after few seconds

### DISCUSSION THREAD

**Discussion by krupers** [outline/outline#5729] [Self Hosting]
Hello everyone,
I thought that this is simple, but I failed... I can not start the Outline even I am doing everything like in the guides.

I have updated and created a docker-composer.yml like this:

```
version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.71.0
    env_file: ./docker.env
    ports:
      - "3030:3030"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6479:6479"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5532:5532"
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'minio server'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

```

and edited docker.env with all the variables I am using like this (all the other were commented):
```
NODE_ENV=production
SECRET_KEY=secret
UTILS_SECRET=secret
DATABASE_URL=postgres://user:pass@localhost:5532/outline
DATABASE_URL_TEST=postgres://user:pass@localhost:5532/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
REDIS_URL=redis://localhost:6479
REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJzZW50aW5lbC0wIiwicG9ydCI6MjYzNzl9LHsiaG9zdCI6InNlbnRpbmVsLTEiLCJwb3J0IjoyNjM3OX1dLCJuYW1lIjoibXltYXN0ZXIifQ==
URL=http://localhost:3030
PORT=3030
SLACK_CLIENT_ID=clientID
SLACK_CLIENT_SECRET=clientSecret
MAXIMUM_IMPORT_SIZE=5120000
DEBUG=http
LOG_LEVEL=info
SLACK_VERIFICATION_TOKEN=appToken
SLACK_APP_ID=appID
SLACK_MESSAGE_ACTIONS=true
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60

```

When I am composing my docker it gives me a warning like this:

```
WARNING: Some services (storage) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Recreating URL_storage_1 ...
Recreating URL_redis_1   ...
Recreating URL_storage_1  ... done
Recreating URL_redis_1    ... done
Recreating URL_postgres_1 ... done
Recreating URL_outline_1  ... done
```

When I try to check available containers I see that getoutline is available, but a few seconds later it disappear:

```
CONTAINER ID   IMAGE                                              COMMAND                  CREATED         STATUS                            PORTS                                                 NAMES
a7af1a0281ba   docker.getoutline.com/outlinewiki/outline:0.71.0   "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds                      3000/tcp, 0.0.0.0:3030->3030/tcp, :::3030->3030/tcp   URL_outline_1
6a1c222f32cb   redis                                              "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds (health: starting)   6379/tcp, 0.0.0.0:6479->6479/tcp, :::6479->6479/tcp   URL_redis_1
bc9ed8bef09f   postgres                                           "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds (health: starting)   5432/tcp, 0.0.0.0:5532->5532/tcp, :::5532->5532/tcp   URL_postgres_1
```

What am I doing wrong in this?

Thank you so much for your help!
