### DISCUSSION TITLE
Cannot upgrade outline from V0.66.3 to any upper version.

### DISCUSSION THREAD

**Discussion by madorca** [outline/outline#5761] [Self Hosting]
I tried to upgrade 0.66.3 to latest version. 

docker-compose up was easily worked, but DB migration keeps failed.

I tried with "docker compose run outline yarn db:migrate --env production-ssl-disabled"  but it keep failed.

```

yarn run v1.22.19
$ sequelize db:migrate --env=production-ssl-disabled

Sequelize CLI [Node: 18.16.0, CLI: 6.4.1, ORM: 6.29.0]
Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
== 20220810185000-scope-provider-id-uniqueness-to-team: migrating =======

ERROR: Unknown constraint error

error Command failed with exit code 1.

```

Tried with other version, including 67.0-pre.1 to latest, but everything was not working..

Sometime I got different error messages instead of Unknown constraint error.
```
"Dialect needs to be explicitly supplied as of v4.0.0 "
```

Can anybody face similar issues?

I've checked with issues below but not working.
https://github.com/outline/outline/discussions/468/8

And here is my docker-compose file 

```
version: "3.7"
services:

  outline:
    image: outlinewiki/outline:latest
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:14.5
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: *****
      POSTGRES_PASSWORD: ******
      POSTGRES_DB: outline


  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline

    restart: always
    volumes:
      - ./https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'wiki.****.com -> http://outline:3000'
      STAGE: production
      WEBSOCKET: true

volumes:
  https-portal-data:
  storage-data:
  database-data:
```
