### DISCUSSION TITLE
Cannot access endpoints of https-portal

### DISCUSSION THREAD

**Discussion by lanluu** [outline/outline#6435] [Self Hosting]
Hi Community, 

I am trying to bring the self-hosted Outline instance in my local Mac Machine to work, but facing some issues with https-portal.

My settings for https-portal in docker-compose.yml:
```
https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '8081:8080'
      - '444:443'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'
```

It is noted that in order to prevent the conflict of used ports in different local Docker Containers (yes, I am using multiple platforms in my machine now), the ports 8081/444 are exposed instead.

All associated containers are up and running well.  
<img width="1311" alt="Screenshot 2024-01-29 at 11 57 01" src="https://github.com/outline/outline/assets/3998945/23d9b3c2-b66f-4f41-8edb-06fcd52ce1cd">

However, the both configured endpoints `http://localhost:444` and `https://localhost` are still not accessible.
<img width="1350" alt="Screenshot 2024-01-29 at 11 59 03" src="https://github.com/outline/outline/assets/3998945/62426e69-5507-4f71-b2db-601ba60848dd">

Any ideas? :-)

Thank you in advance!
Lan
