### DISCUSSION TITLE
Why does the installation fail when following the documentation?

### DISCUSSION THREAD

**Discussion by AlbertXiaoPeng** [outline/outline#6585] [Self Hosting] [answered]
Document: https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t

### docker-compose.yml

Create the docker-compose file

```yml
version: "3.2"
services:

  outline:
    image: outlinewiki/outline:0.75.1
    env_file: ./docker.env
    ports:
      - "13000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - outline-postgres
      - outline-redis

  outline-redis:
    image: redis:6.2.10
    env_file: ./docker.env
    ports:
      - "16379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  outline-postgres:
    image: postgres:14.11
    env_file: ./docker.env
    ports:
      - "15432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'aB1234569780'
      POSTGRES_DB: 'outline'

volumes:
  storage-data:
  database-data:
```

### docker-env

Configure the docker.env file

![image](https://github.com/outline/outline/assets/44151574/5a6989d3-7a17-428a-8e86-32ed57c317e6)

### create database

Then run the following command according to the documentation

```shell
docker-compose run --rm outline yarn db:create --env=production-ssl-disabled
```

### error

![image](https://github.com/outline/outline/assets/44151574/d38db3a7-bf96-47da-9b55-c93525bff727)
