### DISCUSSION TITLE
Successfully deployed self hosted of outline wiki - Not getting synced with desktop version of outline wiki

### DISCUSSION THREAD

**Discussion by ghost** [outline/outline#6622] [Self Hosting]
Hi team,

I have deployed outline wiki in docker container and this was my docker compose file

```
version: "3.3"
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    ports:
      - 3000:3000
    volumes:
      - ./storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
      PGSSLMODE: disable
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${SERVER_IP}:5432/${POSTGRES_DB}
      REDIS_URL: redis://${SERVER_IP}:6379
      URL: ${URL}
      PORT: ${PORT}
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
      SLACK_CLIENT_ID: ${SLACK_CLIENT_ID}
      SLACK_CLIENT_SECRET: ${SLACK_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    restart: unless-stopped
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis.conf:/redis.conf
    command:
      - redis-server
      - /redis.conf
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 30s
      retries: 3
    restart: unless-stopped
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
      interval: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
```

its running as well, and im using slack for signing in , but if i use the same slack account in desktop version and mobile version of outline wiki, my self hosted docs not coming, any solution??
