### DISCUSSION TITLE
Suggested changes to the docker deployment documentation

### DISCUSSION THREAD

**Discussion by dreamerblue** [outline/outline#6656] [Show and tell]
Hi, I have successfully deployed Outline but after some testing and tweaking, the following parameters are recommended to be changed in document [Docker](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t).
This change was made to help users avoid error `FATAL:  role "root" does not exist` from postgres container (due to `pg_isready` trying to test with default `root` user). I'd like to submit a PR to help improve the documentation but can't find the code base of documentation, so I'm using discussion to suggest improvements.

Suggested changes:
```yaml
postgres:
  # existed configs...
  healthcheck:
    test: ["CMD", "pg_isready -d outline -U user"]
    # ... remaining configs
```
