### DISCUSSION TITLE
`Error: 400 Bad Request` when upload avatar to AWS S3

### DISCUSSION THREAD

**Discussion by nh4ttruong** [outline/outline#6704] [Self Hosting]
I cannot upload/change avatar image for org/user but I can upload document and paste image into document

Outline deployment config;
```yaml
  FILE_STORAGE: s3
  AWS_REGION: ap-southeast-1
  AWS_S3_ACCELERATE_URL: https://<bucket>.s3.ap-southeast-1.amazonaws.com
  AWS_S3_ACL: private
  AWS_S3_FORCE_PATH_STYLE: "false"
  AWS_S3_UPLOAD_BUCKET_NAME: <bucket>
  AWS_S3_UPLOAD_BUCKET_URL: https://<bucket>.s3.ap-southeast-1.amazonaws.com
  AWS_SECRET_ACCESS_KEY: ***
  AWS_ACCESS_KEY_ID: ***
```

I'm sure that I followed to document 100% (https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7#h-aws-s3)

**To Reproduce**
1. Go to 'Setting'
2. Click on 'Detail' -> 'Logo' -> 'Upload'

**Screenshots**
Error when upload:
![image](https://github.com/outline/outline/assets/61237126/60350e68-ef34-45a3-a00b-cd0e504345b0)

Success upload on document:
![image](https://github.com/outline/outline/assets/61237126/b2b68365-9330-4ebe-98ae-44a4df771e3b)

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.75.2
