### DISCUSSION TITLE
Can't upload File to doc to Minio S3 under Authelia protection

### DISCUSSION THREAD

**Discussion by catfishlty** [outline/outline#6739] [Self Hosting]
I use `Authelia` to protect all my services. And I'm pretty sure that both `docs.mydomain.com` and `minio.mydomain.com` are under authelia protection.
When uploading a file to outline, the upload requests will be failed by authelia auth check.
Then I checked the requests flow, and I think the upload requests send to minio service missing cookies with authelia auth info, so the requests are failed.

Here're 3 requests when uploading a file that I capture them on Chrome Dev Tools.
### General
Request URL: `https://docs.mydomain.com/api/attachments.create`
Request Method: `POST`
Status Code: `200 OK`

## Docker Compose File
```yml
version: "3"
services:
  outline:
    image: outlinewiki/outline:0.75.2
    container_name: outline
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    restart: always
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: us-east-1
      AWS_S3_ACCELERATE_URL: null
      AWS_S3_UPLOAD_BUCKET_URL: https://minio.mydomain.com
      AWS_S3_UPLOAD_BUCKET_NAME: outline
      FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
      AWS_S3_FORCE_PATH_STYLE: true
      AWS_S3_ACL: private
```
### Request Header
Cookie: `authelia_session={authelia_session}; sessions=%7B%7D; accessToken={accessToken}`

### Request Payload
```json
{
    "preset": "documentAttachment",
    "documentId": "xxx",
    "contentType": "image/jpeg",
    "size": 6295,
    "name": "test.jpg"
}
```

### Response
```json
{
    "data": {
        "uploadUrl": "https://minio.mydomain.com/outline",
        "form": {
            "Cache-Control": "max-age=31557600",
            "Content-Type": "image/jpeg",
            "Content-Disposition": "attachment",
            "key": "uploads/{id1}/{id2}/test.jpg",
            "acl": "private",
            "bucket": "outline",
            "X-Amz-Algorithm": "AWS4-HMAC-SHA256",
            "X-Amz-Credential": "{}",
            "X-Amz-Date": "20240329T150154Z",
            "Policy": "{}",
            "X-Amz-Signature": "{}"
        },
        "attachment": {
            "documentId": "{id3}",
            "contentType": "image/jpeg",
            "name": "test.jpg",
            "id": "{id2}",
            "url": "/api/attachments.redirect?id={id2}",
            "size": "6295"
        }
    },
    "status": 200,
    "ok": true
}
```

### General
Request URL: `https://minio.mydomain.com/outline`
Request Method: `OPTIONS`
Status Code: `200 OK`

### Request Header
No Cookies

### General
Request URL: `https://minio.mydomain.com/outline`
Request Method: `POST`
Status Code: `303 See Other`

### Request Header
No Cookies

### Request Payload
Can't see it on Chrome Dev Tools

I don't know why the requests send to minio service without cookies that is required for this situation, so I need some help to solve this problems.
Thanks~
