### DISCUSSION TITLE
Redis not obeying docker volume mounts.

### DISCUSSION THREAD

**Discussion by NKNdevs** [outline/outline#6793] [Self Hosting]
In docker-compose.yml I specify mounts for the various containers (just showing relevant stanzas)

```
services:
  outline:
    volumes:
      - storage-data:/var/lib/outline/data

  redis:
    volumes:
      - redis-data:/redis.conf

  postgres:
    volumes:
      - postgres-data:/var/lib/postgresql/data
#And at the bottom ... 
volumes:
  redis-data:
  storage-data:
  postgres-data:
```

This works for outline and postgres, but redis seems to ignore it. 

In /var/lib/docker/volumes I have this: 
```
drwx-----x  3 root root 4.0K Apr 11 08:52 0763e19ed31b79fa44783a3478e30ff95225b27abc47933bc7a389ce583bea54
drwx-----x  3 root root 4.0K Apr 11 08:26 33003d444fd915aa7b87679d439a3a96a6ea97b8370f909c4248099392919ced
drwx-----x  3 root root 4.0K Apr 11 08:31 35b19212b600c29f05bc465c32d6218bb93b9a07649dceccf3bca4b7d43a434e
drwx-----x  3 root root 4.0K Apr 11 08:56 b689503e45b1f5097df757c26ea248b1b6a060e5eddb499c1dc4736bcd5b015a
drwx-----x  3 root root 4.0K Apr 11 07:30 docker_postgres-data
drwx-----x  3 root root 4.0K Apr 11 07:30 docker_redis-data
drwx-----x  3 root root 4.0K Apr 11 07:30 docker_storage-data
drwx-----x  3 root root 4.0K Apr 11 08:02 e07c37a4c7fa83fd81867ab56f2d2589679975f06cb8fe3934b315eaa0f06ceb
drwx-----x  3 root root 4.0K Apr 11 09:07 e6c29850bdabd568b3dd1a6c3c3cb0be57bcc984947f384a5878e889a6a92b23
drwx-----x  3 root root 4.0K Apr 11 07:30 f2fd8d6f16cba72aafbb31d42c7da8333bdab9a58f29bc6ababcdb217ab42742

```
docker_redis-data is empty. However in each of the long random directory names, I see a _data/dump.rdb file. These directories are created I think every time I restart the app with docker compose down/up. 

It seems redis is ignoring docker-compose. There are no other docker containers running on the machine. Any idea what's going on? Have I made an error somewhere, or are others experiencing this too. Using latest version 0.75.
