### DISCUSSION TITLE
Please add curl, wget or even nc to your outline image

### DISCUSSION THREAD

**Discussion by ovizii** [outline/outline#7051] [Ideas]
It looks like v0.77.1 with the switch from Alpine to Debian Slim broke my healthcheck. 
I entered the container and realized there is neither curl nor wget or even nc available, so I am wondering how to add a docker healthcheck to the outline container?
Before v0.77.1 I used a healthcheck based on curl but that is gone now.

**Comment by matteo-bruni** [comment]
I thought I was going crazy. with version 0.77.1 the problems on arm were solved but traefik did not capture the configuration of the new container. 

this was due to the healthcheck config using wget missing from debian slim (if a container is unhealthy traefik ignore its configuration)
```    
outline:
    ....
    healthcheck:
        test: ["CMD", "wget", "--spider", "http://localhost:3000"]
        interval: 3s
        retries: 12
```

removing the healthcheck solves the problem but would be fine to have a node script/curl/wget as suggested
