### DISCUSSION TITLE
Changed healthcheck after switch from Alpine to Debian Slim

### DISCUSSION THREAD

**Discussion by almereyda** [outline/outline#7094] [Show and tell]
After release of f35676f3473e358f3778095c2dcf9cb7f1e1d644 with v0.77.2, a custom health check that depended on `wget` stopped working. This documents an ad hoc improvisation to return the desired behaviour:

The target here was not having to install anything into the Outline image. A separate `yarn` command could also help out here, which (quickly) calls some internal health enumerations instead. Use this snippet to adapt your own configuration:

```yaml
    volumes:
      - ${PWD}/healthcheck.sh:/opt/outline/healthcheck.sh
    healthcheck:
      test: ['CMD-SHELL', 'bash -c "[[ $$(./healthcheck.sh http://localhost:3000) == \"200\" ]]" || exit 1']
```

This requires the presence of `healthcheck.sh` in your present working directory.

```js
#!/usr/bin/env node

const http = require('http');
const https = require('https');
const url = require('url');

const [,, inputUrl] = process.argv;

if (!inputUrl) {
  console.error('Usage: ./healthcheck.sh <URL>');
  process.exit(1);
}

const parsedUrl = new url.URL(inputUrl);
const protocol = parsedUrl.protocol === 'https:' ? https : http;

const options = {
  hostname: parsedUrl.hostname,
  port: parsedUrl.port || (parsedUrl.protocol === 'https:' ? 443 : 80),
  path: parsedUrl.pathname + (parsedUrl.search || ''),
  method: 'HEAD',
  headers: {
    'Connection': 'close'
  }
};

const req = protocol.request(options, (res) => {
  console.log(`${res.statusCode}`);

  res.setEncoding('utf8');
  res.on('end', () => {
    process.exit(0);
  });
});

req.on('error', (e) => {
  console.error(`${e.message}`);
  process.exit(1);
});

req.end();
```

It needs to have write permission and needs to be owned by the `node` user in the container. Rootless setups will take care of setting the `uid` os owner through their subuid mechanism. Others will also have to employ `chown`

```sh
chown 1000:1000 healthcheck.sh
chmod u+x healthcheck.sh
```
