### DISCUSSION TITLE
1 question about upload max size and 1 issue about internal use of Outline

### DISCUSSION THREAD

**Discussion by 1mfaasj** [outline/outline#7170] [Self Hosting]
Hi,
1. I've got an environment variable but I'm not sure what this number is? kb? bytes?
`FILE_STORAGE_UPLOAD_MAX_SIZE=262144000`
it's not mentioned on the knowledge base: https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7

2. I want to access/use Outline internally, so on it's IP rather than it's domain name. This should be possible right?
but when I set the ports like this, it looks like it's trying to route me to https?

my docker compose (without postgress and redis because they are not in scope for the issue I think)
```
  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.77.2
    ports:
      - 8881:8881
    command: yarn start --env=production-ssl-disabled
    depends_on:
      - outline_postgres
      - outline_redis
    environment:
      - NODE_ENV=production
      - PGSSLMODE=disable
      - SECRET_KEY=XXX
      - UTILS_SECRET=XXX
      - DATABASE_URL=postgres://outline:outline@outline_postgres:5432/outline
      - DATABASE_CONNECTION_POOL_MIN=
      - DATABASE_CONNECTION_POOL_MAX=
      - REDIS_URL=redis://outline_redis:6379
      - URL=https://outline.mydomain.com
      - PORT=8881
      - COLLABORATION_URL=
      - FILE_STORAGE=local
      - FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
      - FILE_STORAGE_UPLOAD_MAX_SIZE=262144000
      - FILE_STORAGE_IMPORT_MAX_SIZE=262144000
      - FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=
      - OIDC_CLIENT_ID=XXX
      - OIDC_CLIENT_SECRET=XXX
      - OIDC_AUTH_URI=https://gitlab.com/oauth/authorize
      - OIDC_TOKEN_URI=https://gitlab.com/oauth/token
      - OIDC_USERINFO_URI=https://gitlab.com/oauth/userinfo
      - OIDC_USERNAME_CLAIM=XXX
      - OIDC_DISPLAY_NAME=openid
      - OIDC_SCOPES=openid email
    volumes:
      - /share/docker/outline/app:/var/lib/outline/data:rw
```

When I visit http://192.168.2.2:8881 now, I get this message:

```
This site is unavailable
https://192.168.2.2/ is not working for a while, or the page may have moved to a new web address.
ERR_SSL_UNRECOGNIZED_NAME_ALERT
```
the domain address is working fine.
Am I missing something? is there a SSL convert in the code, if so, can I disable it?

Edit: when I set this environment variable (FORCE_HTTPS=false) it's welcome me on http, but the OIDC authentication comes into play and switched back to the domain address again.
is there a way to disable authentication on http port?
