### DISCUSSION TITLE
Cloudron Image upload limit increase

### DISCUSSION THREAD

**Discussion by harveyallied** [outline/outline#7267] [Self Hosting]
Hi, I am self hosting Outline and I cannot figure out how to increase the image upload limit. Everytime I upload an image I can an error "Sorry, this file is too large – the maximum size is 1 MB" .
Is there anyway to increase this please? I use Cloudron to host this so any suggestions around this would be great, thanks!

**Comment by weironz** [comment]
Maybe this help, 100MB
```
  outline:
    image: ${OUTLINE_IMAGE_TAG}
    environment:
      FILE_STORAGE_UPLOAD_MAX_SIZE: 104857600
      FILE_STORAGE_IMPORT_MAX_SIZE: 104857600
```
