### DISCUSSION TITLE
Connection refused with Docker Compose deployment

### DISCUSSION THREAD

**Discussion by bushev** [outline/outline#7313] [Self Hosting] [answered]
I got "connection refused" when trying to access the outline by its port: http://127.0.0.1:3000/

![image](https://github.com/user-attachments/assets/33937d8c-5f44-4abe-ab41-1a4c87ecf223)

----

<img width="638" alt="image" src="https://github.com/user-attachments/assets/fe3d3c06-31df-4fb6-9b40-34999fb0851a">

----

```
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: redis
    env_file: ./docker.env
    volumes:
      - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: postgres
    env_file: ./docker.env
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "outline", "-U", "outline" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'outline'
      POSTGRES_PASSWORD: '123456789'
      POSTGRES_DB: 'outline'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

```
NODE_ENV=production
SECRET_KEY=f9903e9********f522bd3265f7bd
UTILS_SECRET=e7adfd172bf71***********83cbd75e30636f490fa4b
DATABASE_URL=postgres://outline:123456789@postgres:5432/outline
PGSSLMODE=disable
REDIS_URL=redis://redis:6379
URL=https://docs.mydomainhere.com
PORT=443
FILE_STORAGE=s3
AWS_ACCESS_KEY_ID=AKIARZ****NC
AWS_SECRET_ACCESS_KEY=En+Rd**********QKMGgwqv
AWS_REGION=us-east-1
AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=https://my-org-outline.s3.us-east-1.amazonaws.com
AWS_S3_UPLOAD_BUCKET_NAME=org-outline
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
GOOGLE_CLIENT_ID=*******.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=GOCSPX-**********
CDN_URL=https://docs.mydomainhere.com
FORCE_HTTPS=false
ENABLE_UPDATES=true
WEB_CONCURRENCY=1
DEBUG=http
LOG_LEVEL=info
SMTP_HOST=email-smtp.us-east-1.amazonaws.com
SMTP_PORT=587
SMTP_USERNAME=AKI********
SMTP_PASSWORD=BH6V************D9B
SMTP_FROM_EMAIL=info@mydomainhere.com
SMTP_SECURE=true
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```
