### DISCUSSION TITLE
Fail to upgrade to v0.78.0 with error "Migration 202406177151506-add-icon-to-user-document.js (up) failed:Original error: column icon of relation documents already exists.

### DISCUSSION THREAD

**Discussion by MorganReid** [outline/outline#7453] [Self Hosting]
Fail to upgrade from v0.77.1 to v0.78.0 with message error:
![image](https://github.com/user-attachments/assets/0721f4ec-3944-436a-b778-66751ddef3f1)

To Reproduce

Upgrade to v0.78.0
Get error :
"Migration 202406177151506-add-icon-to-user-document.js (up) failed:Original error: column icon of relation documents already exists.

Install: self hosted (docker Deployment)
Version: v0.77.1

**Comment by tommoor** [comment]
This migration and column was added in `v0.78.0`, I'm not sure how it could already exist in the database but your best option is to remove it manually if you're in this errored state.

**Reply by MorganReid** [reply]
Thanks for your reply.
For online environments, I need to be careful, so I still hope to find the cause of the error.

First Test:
Upgrading to 0.78.0 did not succeed, so I redeployed outline using 0.77.1,No changes were made to the database. The outline service can be started normally, but the `documents` and `revisions` tables in the database both have `icon` and `color` columns. Is this normal?

![image](https://github.com/user-attachments/assets/3432e95a-b8b1-4361-b03b-cc7ffcd82fa3)

![image](https://github.com/user-attachments/assets/56ac28f3-12fa-487a-9042-b888d5ec0389)

Second Test:
in the following order (based on version 0.78.0)
1: Stop both outline and database
2: Delete the relevant icon and color columns in the database first, and restart the database (I checked and found that these two columns were indeed gone)
3: Then run outline, and the error message is the same as above (these two columns were added to the database at this time)

**Reply by tommoor** [reply]
> Upgrading to 0.78.0 did not succeed

How? What was the error?

>  the documents and revisions tables in the database both have icon and color columns. Is this normal?

Not for versions lower than `0.78.0`, are the columns totally empty?
What is the latest value in the `SequelizeMeta` table?

**Reply by MorganReid** [reply]
Upgrading to 0.78.0 still failed.
I will explain the verification steps in detail
1: Use the following docker-compose-yaml to deploy 0.77.1, and the outline service is normal.

```
version: "3.2"
services:
  outline:
    image: version-0.77.1
    container_name: outline
    restart: always
    ports:
      - "3000:3000"
    networks:
      - outline-network
    environment:
       **(ignore all)
    depends_on:
      - postgres
      - redis 
   
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - /root/wiki-data-test/pg_data:/var/lib/postgresql/data
    networks:
      - outline-network
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      **(ignore)

  redis:
    image: redis
    container_name: redis
    restart: always
    command: ***
    ports:
      - "6379:6379"
    networks:
      - outline-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
      
networks:
  outline-network:
    name: outline-network
    driver: bridge
    #external: true
```



2: Enter the database through the psql command, and the query results are as follows
```
select * from  "SequelizeMeta";(last ten record)
 20240317171826-add-authentication-refresh-token.js
 20240319230356-fix-user-permissions-createdby-constraint.js
 20240327015248-add-user-role.js
 20240327235446-role-non-nullable.js
 20240329012958-remove-old-role-columns.js
 20240413010743-add-options-to-file-operation.js
 20240413042634-member-team-create.js
 20240524234042-add-content-to-collection.js
 20240617030911-add-apikey-expiry.js

table documents similar table revisions
outline=# select icon from  "revisions" where icon is not null;
 icon 
------
(0 rows)

outline=# select color from  "revisions" where color is not null;
 color 
-------
(0 rows)

outline=# select emoji from  "revisions" where emoji is not null limit 1;
 emoji 
-------
 ⚽

```

3:Change the version of docker-compose-yaml to 0.78.0. Then execute` docker compose up`
4:The outline service cannot be started normally, and the error is as follows

```
yarn run v1.22.22
$ node ./build/server/index.js
The environment variable AWS_S3_UPLOAD_MAX_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_UPLOAD_MAX_SIZE instead
The environment variable MAXIMUM_IMPORT_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_IMPORT_MAX_SIZE instead
{"label":"database","level":"info","message":"Running migrations…"}
{"label":"database","level":"info","message":"Migrating 20240617151506-add-icon-to-document.js…"}
{"level":"warn","message":"Migration 20240617151506-add-icon-to-document.js (up) failed: Original error: column \"icon\" of relation \"documents\" already exists"}
error Command failed with exit code 1.
```
5:Enter the database through the psql command again, the query result is exactly the same as step 2, and then manually execute the following command to delete

```
alter table revisions drop column icon;
alter table revisions drop column color;
alter table documents drop column color;
alter table documents drop column icon;
```
6: Execute docker compose up again, the service cannot be started normally, and the error is the same as step 4. Enter the database query result and step 2.
