### DISCUSSION TITLE
SSL issues when trying to self-host Outline - Even with the on-premise scripts. Any tips ?

### DISCUSSION THREAD

**Discussion by Klemet** [outline/outline#7496] [Self Hosting] [answered]
Hey everybody !

I was very excited to self-host Outline on a Linux VPS for an organization I'm working. However, whatever I tried, things to always fail at the SSL level. I've tried :

- Creating SSL certificates with Cerbot and then providing the files to Outline (as indicated in the docs [here](https://docs.getoutline.com/s/1c922644-40d8-41fe-98f9-df2b67239d45)); getting a bad gateway.
- Creating the redirection with Nginx or Nginx proxy manager + a certbot certificate : bad gateway.
- Using the scripts on the [outline-onprem](https://github.com/outline/outline-onprem) repo : bad gateway.

I was particularly interested in the [outline-onprem](https://github.com/outline/outline-onprem) repo to make installation and update easier. If anybody could give me a pointer on how to make it work, I'd be delighted.

Here is what I've done on a Ubuntu 22.04 VPS freshly installed (following the instructions on the repo + a couple of modifications) :

- Get a subdomaine ready (`outline.orgname.com`) and point it to the IP of the VPS.
- In a ssh session on the VPS, `git clone https://github.com/outline/outline-onprem.git`
- `cd outline-onprem`
- `./install.sh`
- Modify the `docker.env` file to indicate the Google Auth client ID + secret, and indicate "LICENSE_KEY=trial"
- Also modify the `DOMAIN` variable in `docker.env`so that `http://outline:3000` points to `http://localhost:3000`; if that's not done, the `https-portal` image returns an error while trying to launch Nginx (as http://outline doesn't point anywhere ? Don't know why this is generated this way by the `install.sh` script ?)
- `./database-setup.sh` to set up the databases (this often returns errors, but the database seems to be created properly anyway, no issues in the docker images running with them)
- `docker compose up -d` to launch the containers.

If done this way, every container is indicated as healthy by `docker ps`, and all the logs seem fine; but trying to connect to `outline.orgname.com` returns a 502 : Bad Gateway error.

I've tried everything, but hasn't been able to fix that. Any tip would be very appreciated (hoping that this might help people with the `outline-onprem` scripts in the future !)

Here are the `docker.env` and `docker-compose.yml` resulting from these steps : 

- `docker.env` (with sensitive information removed)
```bash
## Enterprise License
# Obtain a license key by contacting support, hello@getoutline.com
LICENSE_KEY=trial

## Set node environment to production
NODE_ENV=production
DEBUG=events,emails,mailer,utils,commands,server,services

## Encryption key for passwords etc in the database
SECRET_KEY={Secret_Key}

## Access key for admin utilities over API
UTILS_SECRET={Util_Secret}

## Storage credentials
# If you want to connect to a Postgres database on another host make sure
# to use SSL and comment out or remove the PGSSLMODE line below
DATABASE_URL=postgres://user:{URL}@postgres:54>PGSSLMODE=disable

POSTGRES_USER=user
POSTGRES_PASSWORD={Password}

REDIS_URL=redis://redis:6379

## Nginx server
WEBSOCKET=true
ACCESS_LOG=stdout
# Change stage=local to use a self-signed SSL certificate
STAGE=production
# The fully qualified hostname in the following two variables must match
DOMAINS=outline.organame.com-> http://localhost:3000
URL=https://outline.organame.com

# Third party signin credentials, at least one of EITHER Google OR Slack is
# required for a working installation or you'll have no sign-in options.

# To configure Slack auth, you'll need to create an Application at
# => https://api.slack.com/apps
#
# When configuring the Client ID, add a redirect URL under "OAuth & Permissions":
# https://<URL>/auth/slack.callback
SLACK_KEY=
SLACK_SECRET=

# To configure Google auth, you'll need to create an OAuth Client ID at
# => https://console.cloud.google.com/apis/credentials
#
# When configuring the Client ID, add an Authorized redirect URI:
# https://<URL>/auth/google.callback
GOOGLE_CLIENT_ID={Google_Client_ID}
GOOGLE_CLIENT_SECRET={Google_Client_Secret}

## File Storage
MINIO_ROOT_USER={Minio_user}
MINIO_ROOT_PASSWORD={Minio_Password}
MINIO_REGION_NAME=us-east-1

# For details on setting up Outline to use AWS S3 instead of Minio, see:
# https://wiki.generaloutline.com/share/125de1cc-9ff6-424b-8415-0d58c809a40f
# Set AWS_S3_FORCE_PATH_STYLE to true if using minio, false if using S3
AWS_S3_FORCE_PATH_STYLE=true
```

- `docker-compose.yml`
```yml
version: "3"
services:

  outline:
    image: outlinewiki/outline-enterprise
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:

      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3

  storage:
    image: minio/minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'mkdir -p /opt/uploads && /usr/bin/minio server /opt'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - storage-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
      - storage
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  https-portal-data:
  storage-data:
  database-data:
```
