### DISCUSSION TITLE
Auto import markdown files from a folder

### DISCUSSION THREAD

**Discussion by silversurfer98** [outline/outline#7498] [Self Hosting]
I currently have an Obsidian setup where I store all my knowledge and notes, including some important .md files that are highly useful for my daily work. I want to sync these files to Outline so that they can be viewed in a browser. Additionally, since these files are regularly edited, I have an Obsidian Git setup in place. **My question is: Is it possible to clone my notes Git repository inside a folder and have Outline read them as documents?**

I've reviewed the documentation, but I couldn't find any information related to this. Although the documentation mentions `FILE_STORAGE: local`, I wasn't able to see any files there. I would greatly appreciate more insights on this.

### my current docker setup is
```yaml
version: "3.2"
networks:
  proxy:
    external: true
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline_notes
    volumes:
      - /home/user/docker_data/outline/storage:/var/lib/outline/data
    environment:
      NODE_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      
      DATABASE_URL: ${DATABASE_URL}
      PGSSLMODE: disable
      REDIS_URL: ${REDIS_URL}
      
      URL: https://${URL}
      PORT: 3000
      FILE_STORAGE: local
      FILE_STORAGE_UPLOAD_MAX_SIZE: 262144000
      FILE_STORAGE_IMPORT_MAX_SIZE: 
      FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE:
      # FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data

      OIDC_CLIENT_ID: outline
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_AUTH_URI: https://${IDP_TLD}/api/oidc/authorization
      OIDC_TOKEN_URI: https://${IDP_TLD}/api/oidc/token
      OIDC_USERINFO_URI: https://${IDP_TLD}/api/oidc/userinfo
      OIDC_USERNAME_CLAIM: preferred_username
      OIDC_DISPLAY_NAME: IDP
      OIDC_SCOPES: openid offline_access profile email
      LOG_LEVEL: debug
      DEFAULT_LANGUAGE: en_US
      RATE_LIMITER_ENABLED: true
      RATE_LIMITER_REQUESTS: 1000
      RATE_LIMITER_DURATION_WINDOW: 60
      WEB_CONCURRENCY: 1
      FORCE_HTTPS: false
      ENABLE_UPDATES: false
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.outline.entrypoints=http"
      - "traefik.http.routers.outline.rule=Host(`${URL}`)"
      - "traefik.http.middlewares.outline-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.outline.middlewares=outline-https-redirect"
      - "traefik.http.routers.outline-secure.entrypoints=https"
      - "traefik.http.routers.outline-secure.rule=Host(`${URL}`)"
      - "traefik.http.routers.outline-secure.tls=true"
      - "traefik.http.routers.outline-secure.tls.certresolver=cloudflare" # change this to your cert resolver
      - "traefik.http.routers.outline-secure.service=outline"
      - "traefik.http.services.outline.loadbalancer.server.port=3000"
      - "traefik.docker.network=proxy"

```
