### DISCUSSION TITLE
Document Layout

### DISCUSSION THREAD

**Discussion by Slick-Nick** [outline/outline#7581] [Ideas]
I’d like to request the option to display documents in full-screen mode, maximizing the viewable area.

After experimenting with Chrome's inspection tool, I found that changing the `grid-template-columns` from:

```css
1fr minmax(0px, calc(46em + 76px)) 1fr
```

to:

```css
max-content
```

allows me to view all the data across the screen, rather than being restricted to a narrow column in the middle.

Here’s an example of the CSS:

```css
@media (min-width: 100em) {
    .gENZSs {
        grid-template-columns: max-content;
    }
}
```

Currently, it looks like this:

```css
@media (min-width: 46.0625em) {
    .gENZSs {
        display: grid;
        grid-template-columns: 1fr minmax(0px, calc(46em + 76px)) 1fr;
    }
}
```

This simple change would greatly improve document readability by utilizing the available screen width. It would be awesome to have this option natively supported.

---
