### DISCUSSION TITLE
Outline opening on web but not working/logging in

### DISCUSSION THREAD

**Discussion by shar-mayank** [outline/outline#7588] [Self Hosting] [answered]
Hello everyone, sorry if it's a dumb question but I'm facing a problem with outline. 

Let me give you an overview of the problem, so I'm SSHed into a raspberrypi of my friend. He told me to install outline on the pi, so I set up Postgres and Redis using docker and then using docker installed outline on the pi. Postgres, Redis and Outline all are in different folders. He gave me his Pi access using Twingate. 

This is the **```docker-compose.yml```** file for outline:

```
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.72.0
    env_file: ./docker.env
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}/storage-data:/var/lib/outline/data
    networks:
      - custom_bridge_network
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '3002:80'
      - '443:443'
    links:
      - outline
    restart: unless-stopped
    volumes:
      - ${PWD}/https-portal-data:/var/lib/https-portal
    environment:
      DOMAINS: 'outline.jarvishome.in -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'
      FORCE_RENEW: 'true'
    networks:
      - custom_bridge_network

networks:
  custom_bridge_network:
    external: true
```

This is the **```docker.env```** file for outline:
```
#  ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s REQUIRED  ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s

NODE_ENV=production

# Generate a hex-encoded 32-byte random key. You should use `openssl rand -hex 32`
# in your terminal to generate a random value.
SECRET_KEY=xxxx

# Generate a unique random key. The format is not important but you could still use
# `openssl rand -hex 32` in your terminal to produce this.
UTILS_SECRET=xxxx

# For production point these at your databases, in development the default
# should work out of the box.
DATABASE_URL= postgres://outline:outline123@postgress:5432/outline
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
# Uncomment this to disable SSL for connecting to Postgres
PGSSLMODE=disable

REDIS_URL=redis://rediss:6379

# URL should point to the fully qualified, publicly accessible URL. If using a
# proxy the port in URL and PORT may be different.
URL=https://outline.jarvishome.in
PORT=3000
# See [documentation](docs/SERVICES.md) on running a separate collaboration
# server, for normal operation this does not need to be set.
COLLABORATION_URL=

# Specify what storage system to use. Possible value is one of "s3" or "local".
# For "local", the avatar images and document attachments will be saved on local disk.
FILE_STORAGE=local

# If "local" is configured for FILE_STORAGE above, then this sets the parent directory under
# which all attachments/images go. Make sure that the process has permissions to create
# this path and also to write files to it.
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data

# Maximum allowed size for the uploaded attachment.
FILE_STORAGE_UPLOAD_MAX_SIZE=262144000

# Override the maximum size of document imports, generally this should be lower
# than the document attachment maximum size.
FILE_STORAGE_IMPORT_MAX_SIZE=

# Override the maximum size of workspace imports, these can be especially large
# and the files are temporary being automatically deleted after a period of time.
FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=

#  ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s AUTHENTICATION  ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s ^`^s

# To configure the GitHub integration, you'll need to create a GitHub App at
# => https://github.com/settings/apps
#
# When configuring the Client ID, add a redirect URL under "Permissions & events":
# https://<URL>/api/github.callback
GITHUB_CLIENT_ID= xxxx
GITHUB_CLIENT_SECRET=xxxx
GITHUB_APP_NAME=x-x-x
GITHUB_APP_ID= xxxx
GITHUB_APP_PRIVATE_KEY=xxxx

# To configure Discord auth, you'll need to create a Discord Application at
# => https://discord.com/developers/applications/
#
# When configuring the Client ID, add a redirect URL under "OAuth2":
# https://<URL>/auth/discord.callback
DISCORD_CLIENT_ID=xxxx
DISCORD_CLIENT_SECRET=xxxx

# DISCORD_SERVER_ID should be the ID of the Discord server that Outline is
# integrated with.
# Used to verify that the user is a member of the server as well as server
# metadata such as nicknames, server icon and name.
DISCORD_SERVER_ID=xxxx
DISCORD_SERVER_ROLES=xxxx
```

This is the **```docker-compose.yaml```** file for postgres:
```
services:
  postgres:
    container_name: postgress
    hostname: postgress
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=xxxxxxxxx
      - POSTGRES_USER=xxxx
      - POSTGRES_DB=xxxx
    networks:
      - custom_bridge_network
#    network_mode: bridge
    restart: unless-stopped

networks:
  custom_bridge_network:
    external: true
```

This is the **```docker-compose.yaml```** file for redis:
```
services:
  redis:
    container_name: redis
    hostname: rediss
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - $PWD/data:/data
    environment:
      - REDIS_USERNAME=xxxx
      - REDIS_PASSWORD=xxxx
    networks:
      - custom_bridge_network
    restart: unless-stopped

networks:
  custom_bridge_network:
    external: true
```

Screen recording of what's happening when I click login to outline:
https://github.com/user-attachments/assets/0522d700-dde6-433b-afae-3bdf21d9bdc2

Please help me figure out the possible solutions. Also, please ignore any rookie mistake, I'm new to all this. Thank you
