### DISCUSSION TITLE
Server connection lost

### DISCUSSION THREAD

**Discussion by MaxenceDeCreus** [outline/outline#7654] [Self Hosting]
Hello I have a problem about my outline self-hosted. When i want to write / read an articles. I have a little icon "Server connection lost". Can you help me ?
![image](https://github.com/user-attachments/assets/395e9a2e-5a1a-487d-8ac4-aa1c725ed6ab)

**This is my docker-compose**
```
version: '3'
services:
  outline:
    image: outlinewiki/outline:latest
    environment:
      DATABASE_URL: postgres://XX:XX@db:5432/outline
      REDIS_URL: redis://redis:6379
      URL: https://kb.prizm-security.com
      GOOGLE_CLIENT_ID: xx
      GOOGLE_CLIENT_SECRET: xx
      GOOGLE_CALLBACK_URL: https://kb.prizm-security.com/auth/google.callback
      ENABLE_GOOGLE_OAUTH: 'true'
      SECRET_KEY: ede7d761541d49ed9aba7fc4a552f0a29eab641d8ab01c88e1517d61e9cae617
      UTILS_SECRET: 0ca5107ad6c839ee05434d751bbe3a29a3df3686637da6255e695e4b83cff3b4
      PGSSLMODE: disable
      FILE_STORAGE: local
      FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
      FILE_STORAGE_UPLOAD_MAX_SIZE: 262144000
      SMTP_HOST: smtp-relay.gmail.com
      SMTP_PORT: 587
      SMTP_SECURE: 'false'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - outline_data:/app/data
    networks:
      - outline
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: XX
      POSTGRES_PASSWORD: XX
      POSTGRES_DB: outline
    volumes:
      - psql_data:/var/lib/outline/data
    networks:
      - outline
  redis:
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - outline
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - outline
    networks:
      - outline
    environment:
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'
    restart: always
volumes:
  redis_data:
  outline_data:
  psql_data:
networks:
  outline:
    driver: bridge
```

**This is my nginx.conf**
```
events {}

http {
    upstream outline {
        server outline:3000;
    }
    server {
        listen 80;
        server_name kb.prizm-security.com;

        # Rediriger tout le trafic HTTP vers HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name kb.prizm-security.com;
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_pass http://outline;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /realtime/ {
            proxy_pass http://outline;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
```
