### DISCUSSION TITLE
Error happens: "Migration 20160911234928-user-password.js (up) failed: Original error: column \"passwordDigest\" of relation \"users\" already exists"

### DISCUSSION THREAD

**Discussion by IshuaWang** [outline/outline#7670] [Self Hosting]
I tried to host myself and met a issue. I configured the outline to connect the external container redis and postgresql. I created a new database using the existing user in postgresql container.  According to the docs, it will migrate automatically. However, the logs showed:
`
1Panel-localoutline-xQnh  | {"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"} 1Panel-localoutline-xQnh  | {"level":"warn","message":"Retrying redis connection: attempt 1"} 1Panel-localoutline-xQnh  | {"level":"warn","message":"Retrying redis connection: attempt 1"} 1Panel-localoutline-xQnh  | {"label":"database","level":"info","message":"Running migrations…"} 1Panel-localoutline-xQnh  | {"label":"database","level":"info","message":"Migrating 20160911234928-user-password.js…"} 1Panel-localoutline-xQnh  | {"level":"warn","message":"Migration 20160911234928-user-password.js (up) failed: Original error: column \"passwordDigest\" of relation \"users\" already exists"} 1Panel-localoutline-xQnh  | error Command failed with exit code 1. 1Panel-localoutline-xQnh  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`
I don't know why this happened? Is this a bug?

**To Reproduce**
docker-compose.yaml
```yaml
networks:
    1panel-network:
        external: true
services:
    localoutline3:
        container_name: ${CONTAINER_NAME}
        deploy:
            resources:
                limits:
                    cpus: ${CPUS}
                    memory: ${MEMORY_LIMIT}
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE_NAME}
        image: outlinewiki/outline:0.80.1
        labels:
            createdBy: Apps
        networks:
            - 1panel-network
        ports:
            - ${HOST_IP}:${PANEL_APP_PORT_HTTP}:3010
        restart: always
        volumes:
            - ${OUTLINE_ROOT_PATH}/data:/var/lib/outline/data
```
.env
```text
CDN_URL=
SLACK_CLIENT_ID=
DISCORD_CLIENT_ID=
GOOGLE_CLIENT_ID=
PANEL_POSTGRES_SERVICE=postgresql
PANEL_POSTGRES_TYPE=postgresql
DB_PORT=5432
SMTP_USERNAME=noreply@angyx.com
URL=http://docs.angyx.com
PANEL_REDIS_SERVICE=redis
DB_USERNAME=user_XyZnmH
DISCORD_SERVER_ID=
GITHUB_APP_NAME=
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
GITHUB_CLIENT_ID=
MEMORY_LIMIT=1G
SMTP_HOST=smtp.exmail.angyx.com
DATABASE_URL=postgres://user_XyZnmH:password_GMN5JC@172.18.0.4:5432/outline_byw5d7
CPUS=1
SMTP_PASSWORD=tFY8DnKoj4eEzpwv
HOST_IP=
GITHUB_CLIENT_SECRET=
DB_DATABASE_NAME=outline_byw5d7
SMTP_PORT=465
SECRET_KEY=fbad4f5da794acbc10f060cdfcf8673300f3302d87f076d7f6e781d4840e9c3d
UTILS_SECRET=b2be1c54acbfe6d965bda01e63195cc815e4743a6fb5ba5f82eae916d98989b5
CONTAINER_NAME=1Panel-localoutline-xQnh
OUTLINE_ROOT_PATH=/data/outline
DISCORD_CLIENT_SECRET=
PANEL_REDIS_TYPE=redis
DB_HOSTNAME=172.18.0.4
SLACK_VERIFICATION_TOKEN=
IFRAMELY_URL=https://iframe.ly/api/iframely
DB_PASSWORD=password_GMN5JC
IFRAMELY_API_KEY=
DISCORD_SERVER_ROLES=
GOOGLE_CLIENT_SECRET=
SLACK_CLIENT_SECRET=
SLACK_APP_ID=
SMTP_FROM_EMAIL=noreply@wangyx.com
REDIS_URL=redis://redis_28TjFx@172.18.0.5:6379
PANEL_APP_PORT_HTTP=3050
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=20.17.0
YARN_VERSION=1.22.22
NODE_ENV=production
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
PGSSLMODE=disable
```
**Expected behavior**
The database  should migrate successfully.

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.80.1
