### DISCUSSION TITLE
Installing Outline alongside Caddy and Discord Auth

### DISCUSSION THREAD

**Discussion by revonzev** [outline/outline#7688] [Show and tell]
Installing Outline can be annoying, like, I managed to get around fourteen different errors. I made this tutorial in hopes of making it less of an annoyance: https://revonzev.com/posts/2025/april/how_to_install_outline/

I've tested it on my Linux Mint computer and I have an instance running on my Debian server.

**Comment by ps23Rick** [comment]
Hi.. I tried following the link but it doesn't work -- it just comes up with a blank page for me.  thanks!

**Reply by Moonie8t7** [reply]
Same. Which is a bugger as I am trying to do this myself at the moment ha!

**Comment by revonzev** [comment]
In case my website got down again, here's the guide:

**Step 1: Install Docker**
**Step 2: Install Caddy (Docker)**
Here's my docker-compose for Caddy:

```
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - label:disable
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./container_config:/etc/caddy
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./caddy_log:/var/log/caddy
      - /etc/localtime:/etc/localtime:ro
    networks:
      - reverseproxy-nw

networks:
  reverseproxy-nw:
    external: true
```

Don't forget to add Caddy's Caddyfile. Create a new folder named container_config and make a new file named Caddyfile inside of it.

```
http://hello-world.localhost {
  respond "Hello World!"
}
```

You can change the http://hello-world.localhost to your own domain. Caddy will not turn HTTP into HTTPS for sites with http://... e.g. http://example.com. Caddy will, however, automatically turn a site like example.com (without the http://) into HTTPS.

One last step to do is to add the reverseproxy-nw Docker network by running this in the terminal:

```
docker network create "reverseproxy-nw"
```

This is done so Caddy can access other docker containers that are connected to reverseproxy-nw Docker network.

An example of connecting to a container with it.
```
http://s.localhost {
  reverse_proxy chhoto-url:4567
}
```

chhoto-url is the Docker container's name, while 4567 is its port

Now run this command to start the docker container:

```
docker compose up -d
```

Go to [hello-world.localhost](http://hello-world.localhost/) in your browser to see if it is working or not.

**Step 3: Install Outline (Docker)**
Here's the docker-compose for my Outline:
```
services:
  outline_redis:
    image: redis
    restart: always
    container_name: outline_redis
    networks:
      - outline-internal

  outline_postgres:
    image: postgres:15
    restart: always
    container_name: outline_postgres
    security_opt:
      - label:disable
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    networks:
      - outline-internal
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro

  outline:
    image: outlinewiki/outline:latest
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn start --env=production-ssl-disabled"
    depends_on:
      - outline_postgres
      - outline_redis
    environment:
      - WEBSOCKET=true
      - FORCE_HTTPS=false
      - PGSSLMODE=disable
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline_postgres:5432/outline
      - REDIS_URL=redis://outline_redis:6379
      - URL=${WIKI_URL}
      - PORT=80
      - FILE_STORAGE=local
      - FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
      - FILE_STORAGE_IMPORT_MAX_SIZE=26214400
      - FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=26214400
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
    networks:
      - outline-internal
      - reverseproxy-nw
    volumes:
      - ./container-data/data:/var/lib/outline/data

networks:
  outline-internal:
  reverseproxy-nw:
    external: true
```

The .env file that's in the same directory as the docker-compose:
```
#secrets/passwords
SECRET_KEY=
UTILS_SECRET=
POSTGRES_PASSWORD=

#domains
WIKI_URL=http://outline.localhost

#oidc information
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_SERVER_ID=Plaintext
```

You can get the SECRET_KEY and UTILS_SECRET by running this in the terminal:

```
openssl rand -hex 32
```

Add your own password for the Postgres database and change your Outline URL to your domain if you have one ready for it.

I use Discord's OAuth to authenticate into my outline, here's how to do it in order:

- Go to Discord's developer website, [here](https://discord.com/developers/applications/)
- Login with your Discord
- Click on the New Application button
- Put in the name of the application, I put in outline
- Click on the check button to accept Discord's Developer Terms of Service and Developer Policy
- Click on the Create Button
- go to the OAuth2 in the SETTINGS on the left side bar
- Copy the CLIENT ID
- Paste the CLIENT ID at the end of the DISCORD_CLIENT_ID= inside of the .env file
- Click the Reset Secret button on your application's OAuth2 settings in the Discord developer website
- Click the Yes, do it! button
- Enter your Discord password
- Click the Submit button
- Copy the CLIENT SECRET
- Paste the CLIENT SECRET at the end of the DISCORD_CLIENT_SECRET= inside the .env file
- On your application's OAuth2 settings in the Discord developer website add a Redirect to http://outline.localhost/auth/discord.callback you can change the http://outline.localhost to your Outline URL
- Click on the Save Changes button

Add Outline to Caddyfile, you can change the http://outline.localhost to your Outline URL:

```
http://outline.localhost {
    reverse_proxy outline
}
```

After all that, run Outline with Docker:

```
docker compose up -d
```

Then go to [outline.localhost](outline.localhost) and login with your Discord. That's it. Done.
