### DISCUSSION TITLE
Outline behind Traefik gives "Internal Server Error"

### DISCUSSION THREAD

**Discussion by MrDuartePT** [outline/outline#7735] [Self Hosting]
Deploying outline in kubernetes it gives a Internet server error. 

When acessing via localhost (by setting up my URL to the LoadBalancer IP [http://10.23.0.3:3000/]) I can get to the Outline webpage without any problems.

Bellow it my deployment.yaml config.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: external-services
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
          envFrom:
            - configMapRef:
                name: outline
                optional: false
            - secretRef:
                name: outline
                optional: false
          image: outlinewiki/outline:latest
          imagePullPolicy: Always
          name: outline
          ports:
            - containerPort: 3000
              name: https
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/outline/data
              name: outline-data
              subPath: storage-data
      restartPolicy: Always
      volumes:
        - name: outline-data
          persistentVolumeClaim:
            claimName: outline-data
```

Bellow is my secret (some values are not shown) and configmap that have the enviroment variable of docker.env file:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: outline
  namespace: external-services
type: Opaque
data:
  DATABASE_URL: postgres://outline:password@postgresql.db-services.cluster.local:5432/outline
  REDIS_UTL: redis://:password@redis-master.db-services.cluster.local:6379
  OIDC_CLIENT_ID: secret_client_id
  OIDC_CLIENT_SECRET: secret_client_secrets
  REDIS_URL: 
  SECRET_KEY: secret_key
  SMTP_FROM_EMAIL: email@gmail.com
  SMTP_PASSWORD: email_password
  SMTP_REPLY_EMAIL: email@gmail.com
  SMTP_USERNAME: email@gmail.com
```

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: outline
  namespace: external-services
data:
  DEBUG: http
  DEFAULT_LANGUAGE: en_US
  ENABLE_UPDATES: 'true'
  FILE_STORAGE: local
  FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
  FORCE_HTTPS: 'false'
  LOG_LEVEL: info
  NODE_ENV: production
  OIDC_AUTH_URI: https://auth.local.domain.tld/application/o/authorize/
  OIDC_DISPLAY_NAME: authentik
  OIDC_LOGOUT_URI: https://auth.local.domain.tld/application/o/wiki/end-session/
  OIDC_SCOPES: openid profile email
  OIDC_TOKEN_URI: https://auth.local.domain.tld/application/o/token/
  OIDC_USERINFO_URI: https://auth.local.domain.tld/application/o/userinfo/
  OIDC_USERNAME_CLAIM: preferred_username
  PGSSLMODE: disable
  PORT: '3000'
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: '587'
  SMTP_SECURE: 'true'
  SMTP_TLS_CIPHERS: SSLv3
  URL: http://outline.local.domain.tld
  WEB_CONCURRENCY: '1'
```

Traefik config:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-local
  namespace: external-services
spec:
  ingressClassName: traefik-internal
  rules:
    - host: outline.local.domain.tld
      http:
        paths:
          - backend:
              service:
                name: outline
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - outline.local.domain.tld
      secretName: local-domain-tld-tls
```
