### DISCUSSION TITLE
"no cipher match" when sending emails

### DISCUSSION THREAD

**Discussion by rzippert** [outline/outline#7953] [Self Hosting] [answered]
Hi everyone,

Been trying to setup outline and until now everything works besides email.

As we try to send invites the following error keeps repeating:
```
{"error":"error:0A0000B9:SSL routines::no cipher match","level":"error","message":"Error sending email to user@domain.com","stack":"Error: error:0A0000B9:SSL routines::no cipher match\n    at configSecureContext (node:internal/tls/secure-context:168:11)\n    at Object.createSecureContext (node:_tls_common:116:3)\n    at Object.connect (node:_tls_wrap:1774:48)\n    at /opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:329:40\n    at module.exports.resolveHostname (/opt/outline/node_modules/nodemailer/lib/shared/index.js:117:20)\n    at SMTPConnection.connect (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:307:27)\n    at /opt/outline/node_modules/nodemailer/lib/smtp-transport/index.js:264:24\n    at Immediate.<anonymous> (/opt/outline/node_modules/nodemailer/lib/smtp-transport/index.js:71:35)\n    at process.processImmediate (node:internal/timers:483:21)"}
{"error":"error:0A0000B9:SSL routines::no cipher match","level":"error","message":"Error processing task in EmailTask","stack":"Error: error:0A0000B9:SSL routines::no cipher match\n    at configSecureContext (node:internal/tls/secure-context:168:11)\n    at Object.createSecureContext (node:_tls_common:116:3)\n    at Object.connect (node:_tls_wrap:1774:48)\n    at /opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:329:40\n    at module.exports.resolveHostname (/opt/outline/node_modules/nodemailer/lib/shared/index.js:117:20)\n    at SMTPConnection.connect (/opt/outline/node_modules/nodemailer/lib/smtp-connection/index.js:307:27)\n    at /opt/outline/node_modules/nodemailer/lib/smtp-transport/index.js:264:24\n    at Immediate.<anonymous> (/opt/outline/node_modules/nodemailer/lib/smtp-transport/index.js:71:35)\n    at process.processImmediate (node:internal/timers:483:21)"}
```

We're using docker-compose without the https-portal (we're tunneling HTTPS traffic from cloudflare to outline as HTTP through the cloudflare tunnel, so outline doesn't have https enabled anywhere).

docker-compose.yaml goes something like this:
```
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./.env
    volumes:
      - ./volumes/storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    networks:
      outline_network:
        ipv4_address: 172.19.102.2

  redis:
    image: redis
    env_file: ./.env
    command: ["redis-server", "/redis.conf"]
    volumes:
      - ./redis.conf:/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      outline_network:
        ipv4_address: 172.19.102.3

  postgres:
    image: postgres
    env_file: ./.env
    volumes:
      - ./volumes/database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      outline_network:
        ipv4_address: 172.19.102.4

networks:
  outline_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.102.0/24

volumes:

  storage-data:
  database-data:
```

Configuration like this:
```
POSTGRES_USER=REDACTED
POSTGRES_PASSWORD=REDACTED
POSTGRES_DB=outline
NODE_ENV=production
SECRET_KEY=REDACTED
UTILS_SECRET=REDACTED
DATABASE_URL=postgres://REDACTED:REDACTED@172.19.102.4:5432/outline
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
PGSSLMODE=disable
REDIS_URL=redis://172.19.102.3:6379
URL=https://outline.domain.tld
PORT=3000
COLLABORATION_URL=
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
FILE_STORAGE_UPLOAD_MAX_SIZE=262144000
FILE_STORAGE_IMPORT_MAX_SIZE=
FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=
AWS_ACCESS_KEY_ID=get_a_key_from_aws
AWS_SECRET_ACCESS_KEY=get_the_secret_of_above_key
AWS_REGION=xx-xxxx-x
AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=http://s3:4569
AWS_S3_UPLOAD_BUCKET_NAME=bucket_name_here
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
GOOGLE_CLIENT_ID=REDACTED.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET=REDACTED
AZURE_CLIENT_ID=
AZURE_CLIENT_SECRET=
AZURE_RESOURCE_APP_ID=
OIDC_CLIENT_ID=
OIDC_CLIENT_SECRET=
OIDC_AUTH_URI=
OIDC_TOKEN_URI=
OIDC_USERINFO_URI=
OIDC_LOGOUT_URI=
OIDC_USERNAME_CLAIM=preferred_username
OIDC_DISPLAY_NAME=OpenID Connect
OIDC_SCOPES=openid profile email
GITHUB_CLIENT_ID=
GITHUB_CLIENT_SECRET=
GITHUB_APP_NAME=
GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY=
DISCORD_CLIENT_ID=
DISCORD_CLIENT_SECRET=
DISCORD_SERVER_ID=
DISCORD_SERVER_ROLES=
SSL_KEY=
SSL_CERT=
CDN_URL=https://outline.domain.tld
FORCE_HTTPS=false
ENABLE_UPDATES=false
WEB_CONCURRENCY=4
DEBUG=http
LOG_LEVEL=debug
SLACK_VERIFICATION_TOKEN=
SLACK_APP_ID=
SLACK_MESSAGE_ACTIONS=false
DROPBOX_APP_KEY=
SENTRY_DSN=
SENTRY_TUNNEL=
SMTP_HOST=smtp-relay.gmail.com
SMTP_PORT=587
SMTP_FROM_EMAIL=noreply@domain.tld
SMTP_REPLY_EMAIL=noreply@domain.tld
SMTP_TLS_CIPHERS=TLSv1.2
SMTP_SECURE=true
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
IFRAMELY_URL=
IFRAMELY_API_KEY=
```

I have tried may combinations of SMTP configuration, even disabling the SMTP_SECURE, and found out that there is no traffic going out to the SMTP server, so the cipher error must be masking something else. From within the docker instance we're able to send a "wget smtp.gmail.com:587" and get a response, so we're sure it's not a firewall issue:
```
nodejs@405612f9e6cc:/opt/outline$ wget smtp.gmail.com:587
--2024-11-14 17:39:06--  http://smtp.gmail.com:587/
Resolving smtp.gmail.com (smtp.gmail.com)... 142.250.0.108, 2800:3f0:4003:c0f::6c
Connecting to smtp.gmail.com (smtp.gmail.com)|142.250.0.108|:587... connected.
HTTP request sent, awaiting response... 200 No headers, assuming HTTP/0.9
Length: unspecified
```

Also, this traffic is captured on our monitoring, giving us more confidence that something else is failing before the SMTP connection is really attempted. Problem is that I don't have more ideas on how to troubleshoot this further.

Does anybody has an idea?
