### DISCUSSION TITLE
Azure authentication on kubernetes selfhosted

### DISCUSSION THREAD

**Discussion by gabrielaalencastro-tivit** [outline/outline#8016] [Self Hosting]
Hi! I'm trying to install outline wiki in a microk8s cluster, the application works fine when I deploy it, but Azure authentication does not work.

To Reproduce

Configure a new Outline install in a kubernetes cluster
Use Azure as an OIDC provider
Expected behavior
You log in to your self-hosted instance of Outline with your Azure credentials.

Outline reports a :
Error during authentication | error= stack=AggregateError [ETIMEDOUT]: 
    at internalConnectMultiple (node:net:1118:18)
    at internalConnectMultiple (node:net:1186:5)
    at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
    at listOnTimeout (node:internal/timers:583:11)
    at process.processTimers (node:internal/timers:519:7)
Trying to debug using F12 in a browser i have the following error:
![image](https://github.com/user-attachments/assets/d29237f5-a142-47b1-8c4d-22955a5c0835)

Additional Information
The Azure application's redirect URL is set to https://mycustomdomain.com/auth/azure.callback.
In the azure portal logs report that my user was logged in succesfuly

Here's Outline's deployment.yml :
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: outline
data:
  CDN_URL: ""
  DATABASE_URL: postgres://outline:Outline123@localhost:5432/outline
  DATABASE_URL_TEST: postgres://outline:Outline123@localhost:5432/outline-test
  DEBUG: cache,presenters,events,emails,mailer,utils,multiplayer,server,services
  DEFAULT_LANGUAGE: en_US
  ENABLE_UPDATES: "true"
  FORCE_HTTPS: "true"
  PGSSLMODE: disable
  PORT: "80"
  REDIS_URL: redis://localhost:6379
  SMTP_FROM_EMAIL: address@your-domain.tld
  SMTP_HOST: smtp.your-mail-provider.tld
  SMTP_PORT: "587"
  SMTP_REPLY_EMAIL: address@your-domain.tld
  SMTP_USERNAME: address@your-domain.tld
  URL: https://outline-testeprd.tivit.corp
  AZURE_CLIENT_ID: myazureclientid
  AZURE_CLIENT_SECRET: myazureclientsecret
  SECRET_KEY: mysecret
  SMTP_PASSWORD: key_here
  UTILS_SECRET: mysecret
 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
spec:
  selector:
    matchLabels:
      app: outline
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: outline
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: outline-pvc
      containers:
      - name: outline
        image: outlinewiki/outline:latest
        securityContext:
          runAsUser: 0
          runAsGroup: 0
          allowPrivilegeEscalation: true
        command: ["sh", "-c", "yarn sequelize db:migrate --env=production-ssl-disabled && yarn start"]
        envFrom:
        - configMapRef:
            name: outline
        ports:
        - containerPort: 80
      - name: postgres
        volumeMounts:
        - name: data
          mountPath: "/var/lib/postgresql/data"
          subPath: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "outline"
        - name: POSTGRES_PASSWORD
          value: "Outline123"
        - name: POSTGRES_DB
          value: "outline"
        ports:
        - containerPort: 5432
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
      - name: minio
        volumeMounts:
        - name: data
          mountPath: "/data"
          subPath: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        envFrom:
        - configMapRef:
            name: outline
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
---

apiVersion: v1
kind: Service
metadata:
  name: outline
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: outline
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outliine-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - "outline-testeprd.tivit.corp"
    secretName: tls-secret
  rules:
  - host: "outline-testeprd.tivit.corp"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outline
            port:
              number: 80

```
I tried to use different kubernetes deployment from all over the internet a, as well as helm, but i receive this error everytime
