### DISCUSSION TITLE
Cannot Find Email Magic Link Option on Outline Landing Page

### DISCUSSION THREAD

**Discussion by SebDominguez** [outline/outline#8024] [Self Hosting] [answered]
I’m trying to self-host Outline and have run into an issue with the login process. I’ve successfully configured an SMTP server in my setup to enable email-based authentication (magic link login). However, when I visit the landing page, the option to login using an email magic link is not visible.

my `.env`

```
SMTP_HOST=smtp.gmail.com
SMTP_NAME=gmail.com
SMTP_PORT=456
SMTP_USERNAME=username@gmail.com
SMTP_PASSWORD='my smtp password'
SMTP_FROM_EMAIL=username@gmail.com
SMTP_REPLY_EMAIL=username@gmail.com
SMTP_TLS_CIPHERS=TLS_AES_256_GCM_SHA384
SMTP_SECURE=true
```

I’ve tried to mess with `SMTP_SECURE` set to `false` with `SMTP_PORT`set to `587`, tried different `SMTP_TLS_CIPHERS` listed here: [Ciphers for Gmail SMTP TLS connections](https://support.google.com/a/answer/9795993?hl=en)

Despite these efforts, the magic link login option remains unavailable on the landing page. I’m unsure if I’m missing a configuration step or if this could be a bug.
Any help or guidance would be greatly appreciated!

**Comment by tommoor** [comment]
SSO authentication is currently required, so you need to setup an authentication provider in addition to SMTP

**Reply by denizbinay** [reply]
This requirement is a bit inconvenient.

**Reply by SebDominguez** [reply]
Also, the documentation is quite misleading.
This is from the "[Authentication section](https://docs.getoutline.com/s/hosting/doc/email-magic-link-N2CPh5tmTS)"
"Outline supports authentication via email “magic link”. Using this method users will enter their email address on the login page and be sent a single-use, time-restricted link to their email address which they can click to sign-in without a password."

**Reply by tommoor** [reply]
If you'd like to add the ability to initialize the workspace with email magic link I'm open to such a PR, just hasn't been prioritized

**Reply by SebDominguez** [reply]
It would be nice; I just wanted to give this app a quick test. I'm trying to figure out how to set up a simple SSO provider with a small Docker image to test Outline.

**Reply by justinacolmena** [reply]
I just downloaded installed this app to try it, and created an account at Slack just for logging in to it. I haven't quite completed the Slack "integration," but it's all documented. The instuctions are there, how it all works. There's corporate security for mission-critical documents. Or was or is supposed to be. Don't lock yourself out if your app is suddenly unable to send email. You need a shoehorn or a master key to let yourself back in. Swipe your badge at one of those places when you're already late for work, and at the same time you don't want your competitors running off with the documents.

> initialize the workspace with email magic link

Click! Click! Click! Me first! No! Me first! That was my email!

**Reply by darrendavid** [reply]
+1 for magic-link-only without having to configure another method.

**Reply by amunrarara** [reply]
SSO with a big platform as a requirement kinda sours Outline's claim to FOSS, unfortunately. The software seems awesome, but my org doesn't use Slack, Microsoft, nor Google, so we're excluded from using Outline?

**Reply by tommoor** [reply, marked as answer]
[OIDC](https://docs.getoutline.com/s/hosting/doc/oidc-8CPBm6uC0I) is supported, you can integrate with any auth provider you like.

Email-only with magic link is now supported as of a couple of versions ago too.

**Reply by amunrarara** [reply]
I'd like to use email-only login for Outline Cloud, to try out the service. Perhaps off-topic for this thread, but perhaps relevant for future searches. Is that not available?

**Reply by tommoor** [reply]
Yes, but you need to contact hello@getoutline.com to setup the workspace currently.

**Reply by AlienHub** [reply]
> [OIDC](https://docs.getoutline.com/s/hosting/doc/oidc-8CPBm6uC0I) is supported, you can integrate with any auth provider you like.
> 
> Email-only with magic link is now supported as of a couple of versions ago too.

How to configure to log in only by email? I didn't find the help document. Please ask for help.

**Comment by justinacolmena** [comment]
Back end software-as-a-service connections from all the document rendering stuff? Third party equation runner services for math etc.? It's turning me off of Mediawiki, too. I installed it but I haven't made much use of it. There's a corporate gateway with private security and the ability to lock you out of your own documents at their will. Free law enforcement access to your private or non-published documents etc.

It's part of a more comprehensive propriety system where users are beholden to large corporations and arbitrary orders of law enforcement authorities without court process for access to their own documents.

Only part of which was made open source, and there are expiration dates on certain licenses — 

There's useful code that's been made open source, but it's very alarming to the FOSS community what has been revealed about the sorts of documents that would have been handled and the controls or lack of controls over them in a gigantic proprietary corporate police state document control system.

**Comment by ewilan-riviere** [comment]
Here a small guide, works for me.

# Email provider with magic link

Setup for local with docker compose.

## 1. `docker-compose.yml`

```yml
services:
  outline:
    container_name: ${CONTAINER_NAME:-outline}
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - ./outline/data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    restart: ${CONTAINER_RESTART:-unless-stopped}

  redis:
    container_name: ${CONTAINER_NAME:-outline}-redis
    image: redis
    env_file: .env
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    restart: ${CONTAINER_RESTART:-unless-stopped}

  postgres:
    container_name: ${CONTAINER_NAME:-outline}-postgres
    image: postgres:16
    env_file: .env
    expose:
      - "5432"
    volumes:
      - ./outline/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "outline"
    restart: ${CONTAINER_RESTART:-unless-stopped}
```

## 2. `.env` file

```bash
# Public URL for Outline (required, do not leave as localhost)
URL=http://localhost:3000
PORT=3000

# Secrets (generate with: openssl rand -hex 32)
SECRET_KEY=d5d1037ff71c3e2b1815f9cd9e3e4df6474a51dcd760d3a7b57ae0c2212ae1a1
UTILS_SECRET=596412aee79e13726b7434192b4a6a2010bf2ab7dfd1836de2c7639cd0daca06

# Database
POSTGRES_USER=user
POSTGRES_PASSWORD=pass
POSTGRES_DB=outline
DATABASE_URL=postgres://user:pass@postgres:5432/outline
PGSSLMODE=disable

# Redis
REDIS_URL=redis://redis:6379

# File storage (local)
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data

# SMTP
# Configure your own SMTP server settings below
SMTP_HOST=mail.domain.com
SMTP_PORT=465
SMTP_USERNAME=noreply@domain.com
SMTP_PASSWORD=
SMTP_FROM_EMAIL=noreply@domain.com
SMTP_REPLY_EMAIL=noreply@domain.com
SMTP_SECURE=true
EMAIL_ENABLED=true

# Disable forced HTTPS if your reverse proxy handles TLS
# Or in local development environments
FORCE_HTTPS=false

# Logs
LOG_LEVEL=info

# Do not leave placeholder values for unused SSO providers
# Comment out or delete all SLACK_*, GOOGLE_*, AZURE_*, etc. variables
```

> **Important:** any `SLACK_CLIENT_ID`, `GOOGLE_CLIENT_ID`, etc. variable with a non-empty value
> will be detected as an active SSO provider, even if it's just a placeholder.

## 3. First startup

```bash
docker compose up -d
```

Check the logs:

```bash
docker compose logs outline --tail=50 -f
```

## 4. Manual bootstrap (⚠️ step not officially documented)

The `bootstrap.js` script provided by Outline does not create a workspace. Everything must be inserted manually.

### 4.1 Insert the team and retrieve its ID

```bash
docker compose exec postgres psql -U user -d outline -c "
BEGIN;
WITH team AS (
  INSERT INTO teams (id, name, \"createdAt\", \"updatedAt\", \"guestSignin\")
  VALUES (gen_random_uuid(), 'My Wiki', NOW(), NOW(), true)
  RETURNING id
)
INSERT INTO authentication_providers (id, name, \"providerId\", enabled, \"teamId\", \"createdAt\")
SELECT gen_random_uuid(), 'email', 'email', true, id, NOW()
FROM team;
COMMIT;"
```

> `guestSignin = true` is **required** for the email button to appear on the login page.
> This is a hidden condition in the source code, absent from the documentation.

### 4.2 Retrieve the team UUID

```bash
docker compose exec postgres psql -U user -d outline -c "SELECT id FROM teams;"
```

### 4.3 Generate an encrypted `jwtSecret`

Outline encrypts the `jwtSecret` column with `SECRET_KEY`. You need to use its own code to generate the value:

```bash
docker compose run --rm outline node -e "
require('@dotenvx/dotenvx').config({ silent: true, ignore: ['MISSING_ENV_FILE'] });
const { default: vaults } = require('./build/server/storage/vaults');
const vault = vaults().vault('jwtSecret');
const crypto = require('crypto');
const secret = crypto.randomBytes(32).toString('hex');
const fakeModel = { _values: {} };
fakeModel.setDataValue = (k, v) => fakeModel._values[k] = v;
vault.set.call(fakeModel, secret);
console.log(Buffer.from(fakeModel._values['jwtSecret']).toString('hex'));
"
```

Copy the displayed hex value.

### 4.4 Create the admin user

Replace these values:

- `USER_MAIL` with your email address.
- `USER_NAME` with your desired username.
- `TEAM_UUID` with the result from step _4.2_ (e.g. `044374b5-cdee-4212-86f8-f1fa58aaa34b`)
- `HEX_JWT_SECRET` with the result from step _4.3_ (e.g. `2f22adcb...`)

```bash
docker compose exec postgres psql -U user -d outline -c "
INSERT INTO users (id, email, name, \"createdAt\", \"updatedAt\", \"teamId\", role, \"notificationSettings\", \"jwtSecret\")
VALUES (
  gen_random_uuid(),
  'USER_MAIL',
  'USER_NAME',
  NOW(),
  NOW(),
  'TEAM_UUID',
  'admin',
  '{}',
  decode('HEX_JWT_SECRET', 'hex')
);"
```

---

## 5. Verification

Test that the API correctly returns the email provider:

```bash
curl -s -X POST http://localhost:3000/api/auth.config | jq .
```

The response should contain:

```json
{
  "data": {
    "name": "My Wiki",
    "providers": [{ "id": "email", "name": "Email" }]
  }
}
```

---

## 7. Logging in

Go to `https://localhost:3000`, enter your admin email, and click the magic link you receive.

## Troubleshooting

| Symptom                        | Cause                               | Fix                                          |
| ------------------------------ | ----------------------------------- | -------------------------------------------- |
| Email button missing           | `guestSignin = false` on the team   | `UPDATE teams SET "guestSignin" = true`      |
| Ghost Slack/Google button      | Non-empty placeholder variables     | Comment out `SLACK_*`, `GOOGLE_*`, etc. vars |
| 500 `secretOrPrivateKey`       | `jwtSecret` is NULL or unencrypted  | Generate via the Node script (step 5.3)      |
| 500 `wrong final block length` | `jwtSecret` not encrypted correctly | Same as above                                |
| No email received              | Rate limit active                   | Wait 60s before resending                    |
| Magic link points to localhost | `URL=http://localhost:3000`         | Fix `URL` with the actual public address     |
| `bootstrap.js` does nothing    | The script is an empty stub         | Follow the manual bootstrap (step 5)         |
