### DISCUSSION TITLE
Synology C2 Configuration

### DISCUSSION THREAD

**Discussion by maxXx1** [outline/outline#8033] [Self Hosting]
Hi everyone, has anyone tried [Synology C2](https://c2.synology.com/en-us/object-storage/overview) storage? I have successfully deployed Outline on a Synology NAS including Synology SSO, so I thought that connecting it to their proprietary object storage would be great.

The configuration in my `docker-compose.yaml` looks something like this, but it doesn't work.

```yaml
      FILE_STORAGE: s3
      FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
      AWS_REGION: eu-003
      AWS_S3_FORCE_PATH_STYLE: false
      AWS_S3_UPLOAD_BUCKET_NAME: <bucket-name>
      AWS_S3_UPLOAD_BUCKET_URL: https://eu-003.s3.synologyc2.net
      AWS_ACCESS_KEY_ID: ###REDACTED###
      AWS_SECRET_ACCESS_KEY: ###REDACTED###
      AWS_S3_ACL: public-read
```
Is there anyone who could try C2 or do you have an example of a working setup? 

Thanks.
