### DISCUSSION TITLE
FATAL:  role "user" does not exist

### DISCUSSION THREAD

**Discussion by xXFreeFunXx** [outline/outline#8041] [Self Hosting]
I am trying to set up Outline on my Raspberry Pi 5 with Docker but unfortunately the outline container does not start.
Here is the error message from the log:
```
outline-postgres  | 2024-11-29 15:11:24.934 UTC [33] FATAL:  password authentication failed for user "user"
outline-postgres  | 2024-11-29 15:11:24.934 UTC [33] DETAIL:  Role "user" does not exist.
outline-postgres  |     Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
outline-main      | {"error":"password authentication failed for user \"user\"","level":"error","message":"Failed to connect to database","stack":"SequelizeConnectionError: password authentication failed for user \"user\"\n    at Client._connectionCallback (/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n    at Client._handleErrorWhileConnecting (/opt/outline/node_modules/pg/lib/client.js:327:19)\n    at Client._handleErrorMessage (/opt/outline/node_modules/pg/lib/client.js:347:19)\n    at Connection.emit (node:events:519:28)\n    at Connection.emit (node:domain:488:12)\n    at /opt/outline/node_modules/pg/lib/connection.js:117:12\n    at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:36:17)\n    at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:11:42)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:488:12)\n    at addChunk (node:internal/streams/readable:559:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n    at Readable.push (node:internal/streams/readable:390:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"}
outline-main      | {"label":"lifecycle","level":"info","message":"Gracefully quitting"}
outline-main      | Done in 4.43s.
outline-main exited with code 0
outline-postgres  | 2024-11-29 15:11:49.984 UTC [41] FATAL:  role "user" does not exist
```
Here is my `docker-compose.yml` file:
```yaml
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline-main
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: outline-redis
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: outline-postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: '2caqfsxhB7ry'
      POSTGRES_DB: 'outline'

volumes:
  https-portal-data:
  storage-data:
  database-data:
  ```
  
The installation is for my local use, I don't need SSL or a web server. I will change the password for postgres again but the scheme looks like `2caqfsxhB7ry`.
The URL is stored in the .env file as follows: `DATABASE_URL=postgres://user:2caqfsxhB7ry@postgres:5432/outline`.

I hope someone can tell me what the error is, I have not changed much in the `docker-compose.yml` file.
