### DISCUSSION TITLE
https-portal : let's encrypt : ValueError: Error creating new order:

### DISCUSSION THREAD

**Discussion by Abdelkrim** [outline/outline#8156] [Self Hosting]
start outline web application

**To Reproduce**
- write the scripts : .env, docker-compose.yml, nginx outline configuration
- create the database using the command describe here https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
- open the firewall ports https ```35125``` and http ```35124```

**Expected behavior**
the home page is displayed

**Screenshots**
![image](https://github.com/user-attachments/assets/7f1494e2-4b9c-4228-b37b-7a93331e2321)

**Outline (please complete the following information):**
- Install: self hosted
- Version: 75cd053d7feb62

### HTTPS-PORTAL LOGS

``` log
========================================
HTTPS-PORTAL v1.24.2
========================================

cont-init: info: /etc/cont-init.d/00-welcome exited 0
cont-init: info: running /etc/cont-init.d/20-setup
----------- BEGIN DOMAIN CONFIG -------------
name: outline.alt-f1.be
stage: production
upstream: 
upstreams: []
upstream_proto: 
redirect_target_url: 
basic_auth_username: 
basic_auth_password: 
access_restriction: 
-------- --- END DOMAIN CONFIG  -------------
DH parameters appear to be ok.
-----BEGIN DH PARAMETERS-----
[REDACTED]
-----END DH PARAMETERS-----
RSA key ok
[DEBUG] Starting Nginx, daemon mode = true
[DEBUG] ensure_signed
[DEBUG] create_ongoing_domain_key rsa for outline.alt-f1.be
[DEBUG] create_csr for outline.alt-f1.be
Signing certificates from https://acme-v02.api.letsencrypt.org/directory ...
Parsing account key...
Parsing CSR...
Found domains: outline.alt-f1.be
Getting directory...
Directory found!
Registering account...
Already registered! Account ID: https://acme-v02.api.letsencrypt.org/acme/acct/2135418715
Creating new order...
Traceback (most recent call last):
  File "/usr/bin/acme_tiny", line 199, in <module>
    main(sys.argv[1:])
  File "/usr/bin/acme_tiny", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/acme_tiny", line 120, in get_crt
    order, _, order_headers = _send_signed_request(directory['newOrder'], order_payload, "Error creating new order")
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/acme_tiny", line 60, in _send_signed_request
    return _do_request(url, data=data.encode('utf8'), err_msg=err_msg, depth=depth)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/acme_tiny", line 46, in _do_request
    raise ValueError("{0}:\nUrl: {1}\nData: {2}\nResponse Code: {3}\nResponse: {4}".format(err_msg, url, data, code, resp_data))
ValueError: Error creating new order:
Url: https://acme-v02.api.letsencrypt.org/acme/new-order
Data: b'{"protected": "[REDACTED]", "payload": "[REDACTED]", "signature": "[REDACTED]"}'
Response Code: 429
Response: {'type': 'urn:ietf:params:acme:error:rateLimited', 'detail': 'too many failed authorizations (5) for "outline.alt-f1.be" in the last 1h0m0s, retry after 2024-12-27 16:24:33 UTC: see https://letsencrypt.org/docs/rate-limits/#authorization-failures-per-hostname-per-account', 'status': 429}
================================================================================
Failed to sign outline.alt-f1.be.
Make sure your DNS is configured correctly and is propagated to this host
machine. Sometimes that takes a while.
================================================================================
Failed to obtain certs for outline.alt-f1.be
[DEBUG] Fail and Shutdown
cont-init: info: /etc/cont-init.d/20-setup exited 1
cont-init: info: running /etc/cont-init.d/30-set-docker-gen-status
cont-init: info: /etc/cont-init.d/30-set-docker-gen-status exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped 
```

### docker.compose.yml

``` yaml
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.81.1
    env_file: ./.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:7.4-alpine
    env_file: ./.env
    ports:
      - "6380:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:17.2-alpine
    env_file: ./.env
    ports:
      - "5433:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "getoutline_com", "-U", "user_getoutline"]
      interval: 30s
      timeout: 20s
      retries: 3
    # environment:
    #   POSTGRES_USER: 'user'
    #   POSTGRES_PASSWORD: 'pass'
    #   POSTGRES_DB: 'outline'

  https-portal:
    image: steveltn/https-portal:1.24
    env_file: ./.env
    ports:
      - '35124:80'
      - '35125:443'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    # environment:
    #   DOMAINS: 'docs.mycompany.com -> http://outline:3000'
    #   STAGE: 'production'
    #   WEBSOCKET: 'true'
    #   CLIENT_MAX_BODY_SIZE: '0'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```
