### DISCUSSION TITLE
Synology NAS + Portainer: How to install?

### DISCUSSION THREAD

**Discussion by Frixs** [outline/outline#8224] [Self Hosting] [answered]
Hello,

I’m having trouble understanding the installation process as described in the official documentation, as it seems incomplete.

Could you help me with setting up the installation on a Synology NAS using Portainer?

I have the official Docker Compose file and the Docker environment file. However, there are a few things I need clarification on:
1. Purpose of https-portal: I’m not fully sure about its role in the setup.
2. Redis Configuration: I need to know where to find the redis.conf file.
3. Installation Path: I need to specify the installation location as /volume1/docker/outlinewiki.

I struggle with properly configuring these files.

It would be cool to connect it with the Synology user system using SSO, but that's another step. First I need to install it.
Any guidance would be greatly appreciated.

Thank you!

**Comment by tommoor** [comment]
I can't help on anything related to Synology or Portainer, however the purpose of `https-portal` is to provide an automatically provisioned SSL certificate for your domain. If you have an existing certificate then it can be removed from the stack in favor of providing [SSL](https://docs.getoutline.com/s/hosting/doc/ssl-pzk7WO8d1n) manually.

**Reply by Frixs** [reply]
Ok then. Is it possible to run the Outline app by removing it from the docker-compose completely?
I'm ok running HTTP without SSL on my local network.

Edit: Well I already figure it out. Mostly. I'm missing the redis.conf file. The installation instructions on the official Outline website are just horrible.

**Reply by tommoor** [reply]
Well, there is no need for a redis.conf file if you are using the redis docker image as the docs describe but I'm glad you got it figured out

**Reply by Frixs** [reply]
That would be cool. I've never used Redis before so I have no experience with configuring it. I post what I have right now below in this discussion.

I use these instructions: https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t
There is nothing said about Redis. I want to use local storage.

**Comment by Frixs** [comment]
This is my current docker compose file:
```
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: OutlineWiki
    ports:
      - "3000:3000"
    volumes:
      - /volume1/docker/outlinewiki/data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: OutlineWiki-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: OutlineWiki-postgres
    volumes:
      - /volume1/docker/outlinewiki/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

```

The errors:
![image](https://github.com/user-attachments/assets/d98bb92f-4000-4092-b988-74347c20762b)

outline:
```
$ node ./build/server/index.js
/opt/outline/node_modules/sequelize/lib/sequelize.js:58
      options.dialect = urlParts.protocol.replace(/:$/, "");
      
TypeError: Cannot read properties of null (reading 'replace')
    at new Sequelize (/opt/outline/node_modules/sequelize/lib/sequelize.js:58:43)
    at new Sequelize (/opt/outline/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:16:9)
    at createDatabaseInstance (/opt/outline/build/server/storage/database.js:25:10)
    at Object.<anonymous> (/opt/outline/build/server/storage/database.js:93:39)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/outline/build/server/collaboration/PersistenceExtension.js:12:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
Node.js v20.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I don't know how to move out from this. :/
