### DISCUSSION TITLE
GitHub Integration

### DISCUSSION THREAD

**Discussion by aurindam** [outline/outline#8385] [Self Hosting]
I tried the instructions here https://docs.getoutline.com/s/hosting/doc/github-GchT3NNxI9 but in settings it shows “The GitHub integration is currently disabled” (see screenshot)
<img width="899" alt="Screenshot 2025-02-11 at 18 21 22" src="https://github.com/user-attachments/assets/dd57740c-c879-4d33-9df2-c967e4b9f7c3" />

**Comment by tommoor** [comment]
Only `GITHUB_CLIENT_ID` needs to be present for this warning to disappear, your environment must not be updated correctly somehow.

**Comment by baditaflorin** [comment]
@aurindam What are you using to start the server?

In docker-compose.yml 

```
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline-app
    hostname: outline-app
    ports:
      - 3000:3000
    volumes:
      - ./storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    environment:
[...]
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GITHUB_APP_NAME: ${GITHUB_APP_NAME}
      GITHUB_APP_ID: ${GITHUB_APP_ID}
      GITHUB_APP_PRIVATE_KEY: ${GITHUB_APP_PRIVATE_KEY}
```

and having a .env file in the same folder as the docekr-compose 
Where you will replace the VALUE with your settings 
```
.env
[...]

GITHUB_CLIENT_ID=VALUE
GITHUB_CLIENT_SECRET=VALUE
GITHUB_APP_NAME=VALUE
GITHUB_APP_ID=VALUE
GITHUB_APP_PRIVATE_KEY=VALUE
```

after i recreate the image i can see this 

<img width="967" alt="image" src="https://github.com/user-attachments/assets/e5e56eb5-c023-41ca-87d9-9eb2a2e7f56e" />

After i click it i go here 

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/552baa37-c5b7-4195-9793-fd1f581e1a9d" />

the payload is 

```
Request URL:
https://github.com/apps/outlineGithub/installations/new?client_id=Iv23liN4mQrxZOcEFh1v&redirect_uri=https%3A%2F%2Fdocs.replacedmyrealurl.com%2Fapi%2Fgithub.callback&state=4c06995a-c5fe-4d1d-900d-369b7188d2bd
Request Method:
GET
Status Code:
302 Found
Remote Address:
140.82.121.4:443
Referrer Policy:
no-referrer
```

Then continues with 
```
Request URL:
https://github.com/apps/outlinegithub/installations/select_target?client_id=Iv23liN4mQrxZOcEFh1v&redirect_uri=https%3A%2F%2Fdocs.replacedmyrealurl.com%2Fapi%2Fgithub.callback&state=4c06995a-c5fe-4d1d-900d-369b7188d2bd
Request Method:
GET
Status Code:
302 Found
Remote Address:
140.82.121.4:443
```


On the getoutline.com hosted version when i click the payload is 

```
Request URL:
https://github.com/apps/outline/installations/new?client_id=Iv1.7f618774af32ac0e&redirect_uri=https%3A%2F%2Fapp.getoutline.com%2Fapi%2Fgithub.callback&state=014ae406-1b32-4f29-bf0e-2e58d85e0758
Request Method:
GET
Status Code:
302 Found
Remote Address:
140.82.121.3:443
Referrer Policy:
no-referrer
```

Also even if it's succesfully integrated when you click the github integrations again you will still see the default Connect Github button, there will not be. status update showing that you previously successfully connected

Also the github app that you are creating needs to request the following "Read access to discussions, issues, metadata, and pull requests"
