### DISCUSSION TITLE
AuthorizationError (401) on home screen

### DISCUSSION THREAD

**Discussion by nitobuendia** [outline/outline#9044] [Self Hosting] [answered]
## Summary

I am trying to test a self-hosted version of Outline to see if this is for me and my use case. I have set everything up with docker using your guide, including one authentication method (magic link / SMTP).

However, when the app starts and I access localhost:3000, or mydomain.xyz:3000, the app gets hung at "Login to Outline".

Checking the console, there's a 401 error: `http://localhost:3000/api/auth.info`

Is there a way to troubleshoot this?

This seems to be the same problem as #8689, except I am not hosting on Windows.

## Details

* Method of Installation: Docker (Compose)
* Host Machine: MacOS Sequoia

docker-compose.yaml

```yaml
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: unless-stopped
    env_file: ./docker.env
    ports:
      - '3000:3000'
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - outline-postgres
      - outline-redis

  outline-redis:
    image: redis:latest
    container_name: outline-redis
    restart: unless-stopped
    env_file: ./docker.env
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  outline-postgres:
    container_name: outline-postgres
    image: postgres
    restart: unless-stopped
    env_file: ./docker.env
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3


  # Intentionally commented out as I will be using Traefik later.
  # https-portal:
  #   container_name: svelte-outline
  #   image: steveltn/https-portal
  #   restart: unless-stopped
  #   env_file: ./docker.env
  #   ports:
  #     - '80'
  #     - '443'
  #   links:
  #     - outline
  #   volumes:
  #     - https-portal-data:/var/lib/https-portal
  #   healthcheck:
  #     test: ["CMD", "service", "nginx", "status"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   environment:
  #     DOMAINS: 'my-domain -> http://localhost:3000'
  #     STAGE: 'local'
  #     FORCE_RENEW: 'false'
  #     WEBSOCKET: 'true'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

docker.env

```env
# –––––––––––––––– REQUIRED ––––––––––––––––

NODE_ENV=production

SECRET_KEY=<randomSecureCode>
UTILS_SECRET=<randomSecureCode>

POSTGRES_USER=<user>
POSTGRES_PASSWORD=<pass>
POSTGRES_DB=outline
DATABASE_URL=postgres://<user>:<pass>@outline-postgres:5432/outline
PGSSLMODE=disable

REDIS_URL=redis://outline-redis:6379

URL=http://localhost
PORT=3000
COLLABORATION_URL=

FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
FILE_STORAGE_UPLOAD_MAX_SIZE=262144000

FORCE_HTTPS=false
ENABLE_UPDATES=false
WEB_CONCURRENCY=1
DEBUG=http
LOG_LEVEL=debug
DEFAULT_LANGUAGE=en_US

RATE_LIMITER_ENABLED=false
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60

SMTP_HOST=<aws-smtp>
SMTP_PORT=587
SMTP_USERNAME=<aws-smtp-user>
SMTP_PASSWORD=<aws-smtp-pass>
SMTP_FROM_EMAIL=<email>
SMTP_TLS_CIPHERS=TLSv1.2
SMTP_SECURE=true
```

Start up logs:

```
[+] Running 3/3
 ✔ Container outline-redis     Created                                                                                                                0.0s 
 ✔ Container outline-postgres  Created                                                                                                                0.0s 
 ✔ Container outline           Created                                                                                                                0.0s 
Attaching to outline, outline-postgres, outline-redis
outline-redis     | 1:C 24 Apr 2025 07:16:09.684 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
outline-redis     | 1:C 24 Apr 2025 07:16:09.684 * Redis version=7.4.2, bits=64, commit=00000000, modified=0, pid=1, just started
outline-redis     | 1:C 24 Apr 2025 07:16:09.684 * Configuration loaded
outline-redis     | 1:M 24 Apr 2025 07:16:09.684 * monotonic clock: POSIX clock_gettime
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * Running mode=standalone, port=6379.
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * Server initialized
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * Loading RDB produced by version 7.4.2
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * RDB age 2 seconds
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * RDB memory usage when created 1.38 Mb
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * Done loading RDB, keys loaded: 4, keys expired: 0.
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * DB loaded from disk: 0.000 seconds
outline-redis     | 1:M 24 Apr 2025 07:16:09.685 * Ready to accept connections tcp
outline-postgres  | 
outline-postgres  | PostgreSQL Database directory appears to contain a database; Skipping initialization
outline-postgres  | 
outline-postgres  | 2025-04-24 07:16:09.700 UTC [1] LOG:  starting PostgreSQL 17.4 (Debian 17.4-1.pgdg120+2) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
outline-postgres  | 2025-04-24 07:16:09.700 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
outline-postgres  | 2025-04-24 07:16:09.700 UTC [1] LOG:  listening on IPv6 address "::", port 5432
outline-postgres  | 2025-04-24 07:16:09.702 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
outline-postgres  | 2025-04-24 07:16:09.705 UTC [29] LOG:  database system was shut down at 2025-04-24 07:16:07 UTC
outline-postgres  | 2025-04-24 07:16:09.707 UTC [1] LOG:  database system is ready to accept connections
outline           | yarn run v1.22.22
outline           | $ node ./build/server/index.js
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=authProvider) registered  (Adds an email magic link authentication provider.)"}
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=api) registered  (Plugin for storing files on the local file system)"}
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=api) registered  (Adds HTTP webhooks for various events.)"}
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=processor) registered WebhookProcessor "}
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=task) registered DeliverWebhookTask "}
outline           | {"label":"plugins","level":"debug","message":"Plugin(type=task) registered CleanupWebhookDeliveriesTask "}
outline           | {"label":"lifecycle","level":"info","message":"\nIs your team enjoying Outline? Consider supporting future development by sponsoring the project:\n\nhttps://github.com/sponsors/outline\n"}
outline           | {"label":"lifecycle","level":"info","message":"Starting collaboration service"}
outline           | {"label":"lifecycle","level":"info","message":"Starting websockets service"}
outline           | {"label":"lifecycle","level":"info","message":"Starting worker service"}
outline           | {"label":"lifecycle","level":"info","message":"Starting web service"}
outline           | {"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
outline           | {"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000 / http://localhost"}
```

No issues on start up.

Accessing http://localhost:3000 - outline loads, but one Network call fails:

```
curl 'http://localhost:3000/api/auth.info' \
  -X 'POST' \
  -H 'Accept-Language: en-US,en-GB;q=0.9,en;q=0.8,es-ES;q=0.7,es;q=0.6' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Length: 0' \
  -b 'postLoginRedirectPath=%2Flogin' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36' \
  -H 'accept: application/json' \
  -H 'pragma: no-cache' \
  -H 'sec-ch-ua: "Google Chrome";v="135", "Not-A.Brand";v="8", "Chromium";v="135"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'x-api-version: 3' \
  -H 'x-editor-version: 14.0.0'
```

 with 401:

```json
{
    "ok": false,
    "error": "authentication_required",
    "status": 401,
    "message": "Authentication required"
}
```

I am assuming that it's somehow expecting me to be logged in, despite not being logged in - or had a chance to do so. I am using SMTP, which is for the Magic Link, which is one of the [provided Authentication methods](https://docs.getoutline.com/s/hosting/doc/email-magic-link-N2CPh5tmTS).

It requires that "You must also ensure the "Allow email authentication” is enabled under Settings → Security". However, since you can never sign up or sign in in the first place, it's not possible to do this. Perhaps this is the error?
