### DISCUSSION TITLE
Content-Security-Policy error

### DISCUSSION THREAD

**Discussion by gazm2k5** [outline/outline#9180] [Self Hosting]
I am self hosting and my domain is behind Cloudflare. I have disabled RocketLoader for the subdomain as suggested in the FAQ. I tried using with Cloudflare Tunnels and also without (using nginx proxy manager instead).

It deploys successfully and I see a "Log in to Outline" graphic on the site, but nothing else. No text box to enter a username/pass. In the browser console I see these errors:
```
Content-Security-Policy: The page’s settings blocked an inline script (script-src-elem) from being executed because it violates the following directive: “script-src 'self' https://www.googletagmanager.com/ 'nonce-f728b2329a2b9ee46157592460588416'”

TypeError: fn is not a function

Uncaught (in promise) 
```

My docker stack looks like this:
```
services:
  outline:
    image: outlinewiki/outline:latest
    restart: always
    environment:
      - SECRET_KEY=[redacted]
      - UTILS_SECRET=[redacted]
      - URL=https://outline.[redacted].xyz
      - DATABASE_URL=postgres://outline:[redacted]@postgres:5432/outline
      - REDIS_URL=redis://redis:6379
      - FILE_STORAGE=local
      - PGSSLMODE=disable
      - FORCE_HTTPS=true
      - LOG_LEVEL=debug
    ports:
      - "[redacted]:3000"
    depends_on:
      - postgres
      - redis
    volumes:
      - /docker-volumes/outline/uploads:/var/lib/outline/uploads
    networks:
      - outline_net

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: [redacted]
      POSTGRES_DB: outline
    volumes:
      - /docker-volumes/outline/postgres:/var/lib/postgresql/data
    networks:
      - outline_net

  redis:
    image: redis:6
    restart: always
    volumes:
      - /docker-volumes/outline/redis:/data
    networks:
      - outline_net

networks:
  outline_net:
    driver: bridge
    ipam:
      config:
        - subnet: [redacted]
```

How do I solve this error?
