### DISCUSSION TITLE
Uploading custom logo fails

### DISCUSSION THREAD

**Discussion by achat-zol** [outline/outline#9266] [Self Hosting]
### 🧠 Context

We deploy Outline with an S3 bucket created via the following CloudFormation template:

```yaml
Description: stack outline

Parameters:
  AppName:
    Type: String
    Description: application name
  Environment:
    Type: String
    Description: Environnement
  OutlineUrl:
    Type: String
    Description: uri

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${Environment}"
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "PUT"
              - "POST"
            AllowedOrigins:
              - !Ref OutlineUrl
          - AllowedMethods:
              - "GET"
            AllowedOrigins:
              - "*"

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AppName}-${Environment}-user"

  S3UserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AppName}-${Environment}-S3Policy"
      Users:
        - Ref: S3User
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObjectAcl
              - s3:DeleteObject
              - s3:PutObject
              - s3:GetObject
              - s3:PutObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${AppName}-${Environment}/*"
              - !Sub "arn:aws:s3:::${AppName}-${Environment}"

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:
  AccessKeyId:
    Value: !Ref AccessKey
    Description: "Access Key ID de l'utilisateur"

  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
    Description: "Secret Access Key de l'utilisateur"
```

---

### 🐞 Bug description

When attempting to **upload the instance logo**, the request fails with a 403 error. All other uploads (like images) work correctly.

**This issue only occurs during the logo upload**.

The browser shows:

```
XHRPOST https://bucket-redacted.s3.eu-west-1.amazonaws.com/
403 Forbidden
```

And the response from AWS:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>User: arn:aws:iam::REDACTED:user/outline-docs-prod-user is not authorized to perform: s3:CreateBucket on resource: "arn:aws:s3:::bucket-redacted" because public access control lists (ACLs) are blocked by the BlockPublicAcls block public access setting.</Message>
</Error>
```

---

* The error mentions `s3:CreateBucket`, but our bucket is **already created** and is **private**.
* We suspect the error is actually due to the **upload request trying to set a `public-read` ACL**.
* Our bucket has **BlockPublicAcls** enabled (which is the default in AWS now).
