### DISCUSSION TITLE
Uploading custom logo fails

### DISCUSSION THREAD

**Discussion by ced455** [outline/outline#9267] [Self Hosting] [answered]
### 🧠 Context

We deploy Outline with an S3 bucket created via the following CloudFormation template:

```yaml
Description: stack outline

Parameters:
  AppName:
    Type: String
    Description: application name
  Environment:
    Type: String
    Description: Environnement
  OutlineUrl:
    Type: String
    Description: uri

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${Environment}"
      AccessControl: Private
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "PUT"
              - "POST"
            AllowedOrigins:
              - !Ref OutlineUrl
          - AllowedMethods:
              - "GET"
            AllowedOrigins:
              - "*"

  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AppName}-${Environment}-user"

  S3UserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AppName}-${Environment}-S3Policy"
      Users:
        - Ref: S3User
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObjectAcl
              - s3:DeleteObject
              - s3:PutObject
              - s3:GetObject
              - s3:PutObjectAcl
            Resource:
              - !Sub "arn:aws:s3:::${AppName}-${Environment}/*"
              - !Sub "arn:aws:s3:::${AppName}-${Environment}"

  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:
  AccessKeyId:
    Value: !Ref AccessKey
    Description: "Access Key ID de l'utilisateur"

  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
    Description: "Secret Access Key de l'utilisateur"
```

---

### 🐞 Bug description

When attempting to **upload the instance logo**, the request fails with a 403 error. All other uploads (like images) work correctly.

**This issue only occurs during the logo upload**.

The browser shows:

```
XHRPOST https://bucket-redacted.s3.eu-west-1.amazonaws.com/
403 Forbidden
```

And the response from AWS:

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>User: arn:aws:iam::REDACTED:user/outline-docs-prod-user is not authorized to perform: s3:CreateBucket on resource: "arn:aws:s3:::bucket-redacted" because public access control lists (ACLs) are blocked by the BlockPublicAcls block public access setting.</Message>
</Error>
```

---

* The error mentions `s3:CreateBucket`, but our bucket is **already created** and is **private**.
* We suspect the error is actually due to the **upload request trying to set a `public-read` ACL**.
* Our bucket has **BlockPublicAcls** enabled (which is the default in AWS now).

**Comment by tommoor** [comment, marked as answer]
Avatars are public and thus `BlockPublicAcls` is not supported - you need to disable this setting, private document attachments will remain private.

**Reply by ced455** [reply]
Noted. So, Avatar and Instance logo are public and use public ACLs.

Could you update [this page](https://docs.getoutline.com/s/hosting/doc/file-storage-N4M0T6Ypu7#h-aws-s3) so users are informed of this?

Also, you can share my CloudFormation template that I can confirm works.

```yaml
Description:
  Bucket creation for outline

Parameters:
  AppName:
    Type: String
    Description: Application name
  Environment:
    Type: String
    Description: staging, prepro, prod
  OutlineUrl:
    Type: String
    Description: Outline Url for CORS

Resources:
  # Création du bucket S3 privé
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AppName}-${Environment}"
      AccessControl: Private
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: true
        IgnorePublicAcls: false
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "PUT"
              - "POST"
            AllowedOrigins:
              - !Ref OutlineUrl
          - AllowedMethods:
              - "GET"
            AllowedOrigins:
              - "*"


  # Création de l'utilisateur IAM
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${AppName}-${Environment}-user"

  # Attachement des permissions de gestion complète sur le bucket
  S3UserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AppName}-${Environment}-S3Policy"
      Users:
        - Ref: S3User
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObjectAcl
              - s3:PutObjectAcl
              - s3:DeleteObject
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub "arn:aws:s3:::${AppName}-${Environment}/*"
              - !Sub "arn:aws:s3:::${AppName}-${Environment}"

  # Création de la clé d'accès pour l'utilisateur
  AccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref S3User

Outputs:
  AccessKeyId:
    Value: !Ref AccessKey
    Description: "User Access Key ID"
  
  SecretAccessKey:
    Value: !GetAtt AccessKey.SecretAccessKey
    Description: "user Secret Access Key"

```
