### DISCUSSION TITLE
Ancient migrations failing on new database

### DISCUSSION THREAD

**Discussion by dodekaphilist** [outline/outline#9364] [Self Hosting]
With a new setup of Outline, I can see in the logs that it is running migrations from 2016 onwards. At some point, one of them fails like this:

```
outline_core  | {"level":"warn","message":"Migration 20181227001547-collection-permissions.js (up) failed: Original error: column \"private\" of relation \"collections\" already exists"}
outline_core  | error Command failed with exit code 1.

outline_postgres  | ERROR:  column "private" of relation "collections" already exists
outline_postgres  | STATEMENT:  ALTER TABLE "public"."collections" ADD COLUMN "private" BOOLEAN NOT NULL DEFAULT false;

```

I tried to delete the database and restart with a new one, but each time I get the same failure, even though it will be another migration that produces the "column already exists" error.

I was wondering why it is doing these migrations in the first place – shouldn't the database just be setup with the current scheme?

Compose:
```
services:
  outline:
    image: outlinewiki/outline:0.84.0
    container_name: outline_core
    restart: unless-stopped
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 9331:3000
    volumes:
      - ${APP_DATA_PATH}/data:/var/lib/outline/data

  redis:
    image: redis:8.0.2
    container_name: outline_redis
    command: ["redis-server", "/redis.conf"]
    restart: unless-stopped
    env_file: .env    
    expose:
      - 6379
    volumes:
      - ${APP_DATA_PATH}/redis.conf:/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres:17.5
    container_name: outline_postgres
    env_file: .env    
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - ${APP_DATA_PATH}/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline_db", "-U", "outline"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: outline
      POSTGRES_PASSWORD: <password>
      POSTGRES_DB: outline_db
```
