### DISCUSSION TITLE
[Urgent] Example Docker self-hosting config exposes Postgres/Redis to the Internet

### DISCUSSION THREAD

**Discussion by burritosoftware** [outline/outline#9392] [Ideas]
This is an issue that we only noticed once we started seeing unusually high CPU usage for the Postgres and Redis instances used by Outline. We dug further, and found that Postgres and Redis were open and exposed to the Internet. We isolated them off, and our CPU usage graphs over time was literally a night and day difference, going from 100% spikes every couple seconds to a quiet 3%. **There might be more instances running with some variation of the example config that haven't noticed this and have this issue.**

I have been running an instance of Outline with the provided [example Docker configuration](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t), and the configuration exposes Postgres and Redis directly to the internet with `expose`. Along with Postgres having a default "user" and "pass" password (even in `docker.env`) and Redis having no authentication, this leaves them open to bad actors on the internet for malicious use such as installing malware (most commonly seen is cryptominers).

I strongly recommend that the example configuration is updated to create two networks, an internal and external one. This way, Postgres, Redis, and Outline all communicate to each other on their own internal network so that nobody can access the database from the outside, and then https-portal being on both the internal and external network is used to expose Outline safely to the internet.

Here's the current example config modified to isolate off Postgres, Redis, and Outline from the Internet, only exposing https-portal with these two networks. (Note, I don't personally use https-portal, since I use Cloudflare Tunnels. In my personal config, I expose Outline on the internal and external networks so that Cloudflare Tunnel can pick it up. Documentation for the Docker configuration I think should be revamped to cover different methods of getting an Outline instance on the internet besides https-portal)

```yml
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    networks:
      - internal
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    env_file: ./docker.env
    networks:
      - internal
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    networks:
      - internal
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    networks:
      - internal
      - external
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'docs.mycompany.com -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'

networks:
  internal:
    internal: true
  external:

volumes:
  https-portal-data:
  storage-data:
  database-data:
  ```
