### DISCUSSION TITLE
This site can’t be reached, when testing Outline locally with Docker local env vars

### DISCUSSION THREAD

**Discussion by chlin501** [outline/outline#9493] [General] [answered]
A similar one is like [this thread here](https://github.com/outline/outline/discussions/8339), but it's still different. So here is my question - What configuration I miss in order to startup Outline successfully so that I can test Outline APIs Auth call? Thanks

This is my docker compose file borrowed from the outline [doc](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t).

```
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    env_file: ./docker.env
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres
    env_file: ./docker.env
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  #https-portal:
  #  container_name: https_portal
  #  image: steveltn/https-portal
  #  env_file: ./docker.env
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #  links:
  #    - outline
  #  restart: always
  #  volumes:
  #    - https-portal-data:/var/lib/https-portal
  #  healthcheck:
  #    test: ["CMD", "service", "nginx", "status"]
  #    interval: 30s
  #    timeout: 20s
  #    retries: 3
  #  environment:
  #    DOMAINS: 'docs.mycompany.com -> http://outline:3000'
  #    STAGE: 'production'
  #    WEBSOCKET: 'true'
  #    CLIENT_MAX_BODY_SIZE: '0'

volumes:
  # https-portal-data:
  storage-data:
  database-data:

```

And updated docker.env
```
# The rest variables is the same as https://github.com/outline/outline/blob/main/.env.sample
URL=http://localhost:3000
SECRET_KEY=... # a value generated through openssl rand -hex 32
PGSSLMODE=disable
FORCE_HTTPS=false
```

The outline logs `docker logs outline` looks like up running
```
{"label":"lifecycle","level":"info","message":"Starting collaboration service"}
{"label":"lifecycle","level":"info","message":"Starting websockets service"}
{"label":"lifecycle","level":"info","message":"Starting worker service"}
{"label":"lifecycle","level":"info","message":"Starting web service"}
{"level":"warn","message":"Enforced https was disabled with FORCE_HTTPS env variable"}
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:3000 / http://localhost:3000"}
...
{"label":"http","level":"info","message":"  <-- GET /_health"}
{"label":"http","level":"info","message":"  --> GET /_health 200 5ms 2b"}
```
And accessing through `curl http://localhost:3000` returns some html doc, except it can't be accessed through browser. 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Outline</title>
    <meta name="theme-color" content="#FFF" />
    <meta name="slack-app-id" content="A0XXXXXXX" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, interactive-widget=resizes-content" />
...
    <script type="module" nonce="4f7921ac19904b283e589add4235fb2a" src="/static/assets/index.BwklcUfm.js"></script>
  </body>
</html>
```
