### DISCUSSION TITLE
Issue with opening attachments in new tab/viewing uploaded picture URL directly

### DISCUSSION THREAD

**Discussion by alaub-mtg** [outline/outline#9499] [Self Hosting]
I am selfhosting Outline. Everything is working as expected without issue other than that once I upload images or attachments, if I open them in a new tab I get the following errors in my browser:

![image](https://github.com/user-attachments/assets/f7553c68-5850-4fbb-98e2-ccbf015f496f)
![image](https://github.com/user-attachments/assets/a9983fdd-27b9-446e-ad9f-2bf1ef802755)

This happens on Chromium browsers primarily. I typically have no problem using firefox although I have seen the error a couple times in firefox as well. I have tried from many machines local to the network and remote including mobile devices and I get these errors. If I wait 1-5 minutes occasionally the URL will load. I can see the file on the server and in the database and the images load inside of Outline without issue.

I have tried many combinations of FORCE_HTTPS on or off, and I added the collaboration URL since I saw another thread about adding that to prevent redirect issues but there is no change. I have also modified my NGINX multiple times based on some of the troubleshooting threads I have seen here.

Below is my .env and my compose with info redacted. I am running this behind nginx.

compose file:

```
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./container-data/outline:/var/lib/outline/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGSSLMODE=disable
      - FILE_STORAGE=local
      - FORCE_HTTPS=true
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline-db:5432/outline
      - REDIS_URL=redis://outline-redis:6379
      - URL=${WIKI_URL}
      - COLLABORATION_URL=${COLLAB_URL}
      - PORT=8080
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - OIDC_AUTH_URI=${OIDC_AUTH_URI}
      - OIDC_TOKEN_URI=${OIDC_TOKEN_URI}
      - OIDC_USERINFO_URI=${OIDC_USERINFO_URI}
      - OIDC_DISPLAY_NAME=${OIDC_DISPLAY_NAME}
      - OIDC_USERNAME_CLAIM=email
      - SMTP_HOST=${SMTP_SERVICE}
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_SECURE=false
      - SLACK_VERIFICATION_TOKEN=${SLACK_VERIFICATION_TOKEN}
      - SLACK_APP_ID=${SLACK_APP_ID}
      - SLACK_MESSAGE_ACTIONS=true
      - SLACK_CLIENT_ID=${SLACK_CLIENT_ID}
      - SLACK_CLIENT_SECRET=${SLACK_CLIENT_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - outline-nw

  redis:
    image: redis
    container_name: outline-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - outline-nw

  postgres:
    image: postgres
    restart: always
    container_name: outline-db
    ports:
      - "5432:5432"
    volumes:
      - ./container-data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    networks:
      - outline-nw

networks:
  outline-nw:
```

.env:
```
#secrets/passwords. Generated 3x using `openssl rand -hex 32`
SECRET_KEY=XXXXXXXXXXXXXXXXXXXXXXX
UTILS_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXX
POSTGRES_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXX

#domains
WIKI_URL=https://kb2.247tech.com

#oidc information
OIDC_CLIENT_ID=XXXXXXXXXXXXXXXX
OIDC_CLIENT_SECRET=XXXXXXXXXXXXXXXXXX
OIDC_AUTH_URI=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
OIDC_TOKEN_URI=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
OIDC_USERINFO_URI=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
OIDC_DISPLAY_NAME=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#smtp info
SMTP_SERVICE=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SMTP_USERNAME=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SMTP_PASSWORD=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SMTP_FROM_EMAIL=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#slack sign-in
SLACK_CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SLACK_CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# For a complete Slack integration with search and posting to channels the
# following configs are also needed in addition to Slack authentication:
# DOCS: https://docs.getoutline.com/s/hosting/doc/slack-G2mc8DOJHk
SLACK_VERIFICATION_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
SLACK_APP_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

# processes
WEB_CONCURRENCY=32

# The default interface language. See translate.getoutline.com for a list of
# available language codes and their rough percentage translated.
DEFAULT_LANGUAGE=en_US

# The in-memory database pool per-process settings. Ensure that the pool size that will not exceed
# the maximum number of connections allowed by your database. Defaults to 0 and 5.
DATABASE_CONNECTION_POOL_MIN=0
DATABASE_CONNECTION_POOL_MAX=32

#collab URL
COLLAB_URL:wss://kb2.247tech.com

```
