### DISCUSSION TITLE
Can't sign in using email. Outline logs complains Error: connect ECONNREFUSED 127.0.0.1:587

### DISCUSSION THREAD

**Discussion by chlin501** [outline/outline#9505] [General] [answered]
After searching the Discussions, [this thread](https://github.com/outline/outline/discussions/4608) is similar to what I am after, but it's different because my problem looks like the outline attempts sending magic sign in link email to SMTP at 127.0.0.1:587, not the one I configured in docker.env.

I am testing locally, so I disable ssl, https env values. Here is my setup: 

- Generate workspace `docker-compose run --rm outline node build/server/scripts/seed.js myname@email-provider.com` by following [this thread](https://github.com/outline/outline/discussions/6155#discussioncomment-7571518)

- docker-compose.yaml
```
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    container_name: redis
    image: redis
    env_file: ./docker.env
    expose:
      - "6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    container_name: postgres
    image: postgres
    env_file: ./docker.env
    expose:
      - "5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  #https-portal:
  #  container_name: https_portal
  #  image: steveltn/https-portal
  #  env_file: ./docker.env
  #  ports:
  #    - '80:80'
  #    - '443:443'
  #  links:
  #    - outline
  #  restart: always
  #  volumes:
  #    - https-portal-data:/var/lib/https-portal
  #  healthcheck:
  #    test: ["CMD", "service", "nginx", "status"]
  #    interval: 30s
  #    timeout: 20s
  #    retries: 3
  #  environment:
  #    DOMAINS: 'docs.mycompany.com -> http://outline:3000'
  #    STAGE: 'production'
  #    WEBSOCKET: 'true'
  #    CLIENT_MAX_BODY_SIZE: '0'

volumes:
  # https-portal-data:
  storage-data:
  database-data:
```

- docker.env
```
URL=http://mylaptop:3000
SECRET_KEY=..# generate via openssl rand -hex 32
PGSSLMODE=disable
FORCE_HTTPS=false
SLACK_CLIENT_ID=
SLACK_CLIENT_SECRET=
# email
SMTP_SERVICE=imap.email-provider.com:993 # this values is the one in real life that's working
SMTP_USERNAME=myname@email-provider.com
SMTP_PASSWORD=this_uses_real_password
SMTP_FROM_EMAIL=myname@email-provider.com 
```

I also checked the outline code in docker. The error seemingly stems from at the line 131 in `./build/server/emails/mailer.js`. But the try-catch block wraps a piece of code that I do not find the part that attempts connecting to smtp server, except `replyTo` but that seems not the issue. 

```
try {
        _Logger.default.info("email", `Sending email "${data.subject}" to ${data.to}`);
        const info = await transporter.sendMail({
          from: data.from,
          replyTo: data.replyTo ?? _env.default.SMTP_REPLY_EMAIL ?? _env.default.SMTP_FROM_EMAIL,
          to: data.to,
          messageId: data.messageId,
          references: data.references,
          inReplyTo: data.references?.at(-1),
          subject: data.subject,
          html,
          text: data.text,
          list: data.unsubscribeUrl ? {
            unsubscribe: {
              url: data.unsubscribeUrl,
              comment: "Unsubscribe from these emails"
            }
          } : undefined,
          attachments: _env.default.isCloudHosted ? undefined : [{
            filename: "header-logo.png",
            path: process.cwd() + "/public/email/header-logo.png",
            cid: "header-image"
          }]
        });
        if (useTestEmailService) {
          _Logger.default.info("email", `Preview Url: ${_nodemailer.default.getTestMessageUrl(info)}`);
        }
      } catch (err) {
        _Logger.default.error(`Error sending email to ${data.to}`, err);
        throw err; // Re-throw for queue to re-try
      }
```

Where to configure this smtp server value that causes Error: connect ECONNREFUSED 127.0.0.1:587? Thanks
