### ISSUE TITLE
Provide a Docker image on Dockerhub

### ISSUE THREAD

**Issue by rutgerbrf** [outline/outline#1009]
Currently no prebuilt Docker image is provided for Outline on Dockerhub. This would be very handy for (easily) deploying Outline locally or in a Kubernetes cluster and keeping Outline up to date.

The image could be automatically built and pushed using CircleCI (see https://circleci.com/docs/2.0/building-docker-images/#example and https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/) at every tag (see https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag). This image could, for example, be provided under outline-wiki/outline.

The following CircleCI configuration (which I have not tested yet) could perhaps be merged with the current configuration, and could build, tag and push the Docker image automatically when a Git tag is created. An account would have to be created on Dockerhub and the secrets `DOCKERHUB_PASS` and `DOCKERHUB_USERNAME` would have to be added in CircleCI.

```yaml
jobs:
  docker-build:
    environment:
      IMAGE_NAME: outline-wiki/outline
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$CIRCLE_TAG -t $IMAGE_NAME:latest .
  docker-push:
    environment:
      IMAGE_NAME: outline-wiki/outline
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:$CIRCLE_TAG

workflows:
  version: 2
  build:
    jobs:
      - build
  build-tag:
    jobs: 
      - build:
          filters:
            tags:
              only: /^v.*/
      - docker:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
```
