### ISSUE TITLE
Cannot auth with Microsoft Azure

### ISSUE THREAD

**Issue by muuvmuuv** [outline/outline#3051]
Following the docs here: https://wiki.generaloutline.com/share/dfa77e56-d4d2-4b51-8ff8-84ea6608faa4

We are unable to auth against Azure. It just get stuck right after saying "Accept" after the login window. /auth/azure.callback never succeeds. We self-host outline and just setup a new instance because adding the env vars did not show MS login methods.

<details>
<summary>docker-compose.yml</summary>

```
version: "3.9"

#
# [ services ]
#

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:cached
      - ./data/www:/var/www/certbot/:ro
      - ./data/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - outline
      - minio
    networks:
      - wiki

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - proxy
    volumes:
      - ./data/www/:/var/www/certbot/:rw
      - ./data/conf/:/etc/letsencrypt/:rw

  redis:
    image: redis:alpine
    container_name: cache
    restart: always
    networks:
      - wiki

  postgres:
    image: postgres:alpine
    container_name: db
    restart: always
    # ports: [ "5432:5432" ]
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      PGSSLMODE: disable
    volumes:
      - ./database:/var/lib/postgresql/data:delegated
    networks:
      - wiki

  minio:
    image: minio/minio
    container_name: storage
    restart: always
    environment:
      MINIO_BROWSER: off
      MINIO_ROOT_USER: 
      MINIO_ROOT_PASSWORD: 
      MINIO_SITE_REGION: eu-central-1
    volumes:
      - ./storage:/data:delegated
    networks:
      - wiki
    command: minio server /data --console-address ":9001"

  outline:
    image: outlinewiki/outline
    container_name: outline
    env_file: outline.env
    depends_on:
      - redis
      - postgres
      - minio
    networks:
      - wiki
    # Run this on first start!
    # command: sh -c "NODE_ENV=production-ssl-disabled yarn sequelize:migrate --env production-ssl-disabled"
    # Single migration
    # command: sh -c "NODE_ENV=production-ssl-disabled node ./build/server/scripts/20210226232041-migrate-authentication.js"

#
# [ networks ]
#

networks:
  wiki:
    name: entergon-wiki
    driver: bridge
```

</details>

**To Reproduce**
1. RUn compose above
2. Try to auth against azure

**Expected behavior**

/auth/azure.callback never succeeds

**Screenshots**
If applicable, add screenshots or videos to help explain your problem.

**Outline (please complete the following information):**
- Install: self hosted
- Version: ca0c67c44273

**Desktop (please complete the following information):**
 - OS: macos
 - Browser edge
 - Version latest

**Mobile (please complete the following information):**
