### ISSUE TITLE
cannot disable email login

### ISSUE THREAD

**Issue by treasuretron** [outline/outline#3227]
in the previous version we were on (4 versions back) we were able to disable email login. Now we are on .62 and 'Allow email authentication' is enabled but doesn't allow disabling.

no SMTP settings are enabled in the .env. The other authentication method is OIDC.

**To Reproduce**
1. Go to Settings->Security
2. See error

**Expected behavior**
Should be able to disable email login.

**Screenshots**
![Screen Shot 2022-03-10 at 12 51 07 PM](https://user-images.githubusercontent.com/679113/157762520-170fa195-472b-41ce-8eee-7fc8835a13ad.png)

**Outline (please complete the following information):**
- Install: self hosted .62
- Version: 3ac125d

**Desktop (please complete the following information):**
 - OS: mac/linux
 - Browser firefox

**Comment by tommoor** [comment]
Hi, does the email option appear on your login page?

**Comment by treasuretron** [comment]
yes, and we'd like to disable it

**Comment by Saeverix** [comment]
Even though this is a long time ago, I believe the issue is back. I have setup an OIDC provider and later also enabled SMTP for emails to be sent.

This automatically causes the `@ Email` sign-in method to be enabled. Also the switch is read-only, so I cannot disable it. This causes the unwanted "Continue with Email" button to appear at the sign-in screen.

<img width="756" height="547" alt="Image" src="https://github.com/user-attachments/assets/d3b9a3fe-4da8-4661-809d-3f088f537d89" />

Here are all the ENV variables I have set:
```
    environment:
      OUTLINE_DOMAIN: "${OUTLINE_DOMAIN:?OUTLINE_DOMAIN required}"
      AUTH_DOMAIN: "${AUTH_DOMAIN:?AUTH_DOMAIN required}"
      NODE_ENV: production
      SECRET_KEY: "${SECRET_KEY:?SECRET_KEY required}"
      UTILS_SECRET: "${UTILS_SECRET:?UTILS_SECRET required}"
      DATABASE_URL: "postgres://outline:${POSTGRES_PASSWORD:?POSTGRES_PASSWORD required}@postgres:5432/outline"
      REDIS_URL: "redis://redis:6379"
      URL: "https://${OUTLINE_DOMAIN:?OUTLINE_DOMAIN required}"
      PGSSLMODE: "disable"
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID:?OIDC_CLIENT_ID required}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET:?OIDC_CLIENT_SECRET required}"
      OIDC_AUTH_URI: "https://${AUTH_DOMAIN:?AUTH_DOMAIN required}/application/o/authorize/"
      OIDC_TOKEN_URI: "https://${AUTH_DOMAIN:?AUTH_DOMAIN required}/application/o/token/"
      OIDC_USERINFO_URI: "https://${AUTH_DOMAIN:?AUTH_DOMAIN required}/application/o/userinfo/"
      OIDC_LOGOUT_URI: "https://${AUTH_DOMAIN:?AUTH_DOMAIN required}/application/o/${OIDC_APPLICATION_SLUG:?OIDC_APPLICATION_SLUG required}/end-session/"
      OIDC_USERNAME_CLAIM: "preferred_username"
      OIDC_DISPLAY_NAME: "authentik"
      OIDC_SCOPES: "openid profile email"
      SMTP_HOST: "${SMTP_HOST:?SMTP_HOST required}"
      SMTP_PORT: "${SMTP_PORT:?SMTP_PORT required}"
      SMTP_USERNAME: "${SMTP_USERNAME:?SMTP_USERNAME required}"
      SMTP_PASSWORD: "${SMTP_PASSWORD:?SMTP_PASSWORD required}"
      SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL:?SMTP_FROM_EMAIL required}"
      FILE_STORAGE: "local"
      FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"
```

The current documentation also does not reflect the current implementation: https://docs.getoutline.com/s/hosting/doc/email-magic-link-N2CPh5tmTS
