### ISSUE TITLE
Can't upload images with spaces in names

### ISSUE THREAD

**Issue by Halogenek** [outline/outline#3414]
I have:
- Self hosted instance (all config files below).
- Minio as S3 storage.
- Instance behind nginx SSL proxy_pass.
- Minio redirected from `https://outline.domain.com/minio-db` instead dedicated domain like `https://s3.domain.com/` but the path through nginx should be the same with proxy_pass.

I can upload images to pages. **I can't upload the same images with a space added in the name.**

**To Reproduce**
1. Create instance with attached config files.
2. Check if instance is working by logging and uploading image **without spaces in filename**.
3. Add space to image filename.
4. Try to upload it a second time.

**Expected behavior**
Uploading images to instance without any problem.

**Screenshots**
Working example (image in center of the page displaying number 13.78...)
![working example](https://user-images.githubusercontent.com/22716728/163804186-2000488f-652b-4885-b6c5-29e4383abbc6.png)
After adding space in filename the image is grayed out and can't be clicked
![not working example](https://user-images.githubusercontent.com/22716728/163804367-8104b493-8c5d-4cfa-8b53-b4ee62fbbf85.png)
Request for filename with space (the filename name is `mala grafika.png`:
```
GET /minio-db/bucket/uploads/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/mala%20grafika.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=xxxxxxxxxxxxxxxx%2F20220418%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220418T115114Z&X-Amz-Expires=60&X-Amz-Signature=xxxxxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-SignedHeaders=host HTTP/1.1
Host: outline.xxxxxxxx.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
Accept: image/avif,image/webp,*/*
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
DNT: 1
Connection: keep-alive
Cookie: lastSignedIn=slack; sessions=%7B%7D; accessToken=xxxxaccesstokenxxxx
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
```
Response for filename with space:
```
HTTP/1.1 400 Bad Request
Server: nginx/1.18.0
Date: Mon, 18 Apr 2022 11:51:15 GMT
Content-Type: text/plain; charset=utf-8
Connection: close
```

**Outline (please complete the following information):**
- Install: self hosted
- Version: image: outlinewiki/outline:0.63.0

docker-compose.yml:
```
version: "3"
services:
  redis:
    image: redis
    restart: always
    networks:
      - outlinewiki
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - outlinewiki
  minio:
    image: minio/minio
    volumes:
      - ./data/minio_root:/minio_root:z
      - ./data/certs:/root/.minio/certs:z
    command: "minio server /minio_root"
    env_file: ./env.minio
    restart: always
    ports:
      - 127.0.0.1:8083:9000
    networks:
      - outlinewiki
  minio-createbuckets:
    image: minio/mc
    depends_on:
      - minio
    env_file:
      - ./env.minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 xxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/bucket;
      /usr/bin/mc policy set download minio/bucket;
      exit 0;
      "
    networks:
      - outlinewiki
  outline:
    image: outlinewiki/outline:0.63.0
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/outline
      - DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./env.outline
      - ./env.slack
    restart: always
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - 127.0.0.1:8082:3000
    networks:
      - outlinewiki
networks:
  outlinewiki:
```

env.minio:
```
MINIO_ACCESS_KEY=xxxxxxxxxxxxxxxx
MINIO_SECRET_KEY=xxxxxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MINIO_BROWSER=off
MINIO_ADRESS=127.0.0.1:9000
```

env.slack:
```
SLACK_APP_ID=xxxx
SLACK_KEY=xxxx.xxxx
SLACK_SECRET=xxxx
SLACK_VERIFICATION_TOKEN=xxxx
```

env.outline:
```
# Copy this file to .env, remove this comment and change the keys. For development
# with docker this should mostly work out of the box other than setting the Slack
# keys (for auth) and the SECRET_KEY.
#
# Please use `openssl rand -hex 32` to create SECRET_KEY
SECRET_KEY=xxxx
UTILS_SECRET=xxxx


# Must point to the publicly accessible URL for the installation
URL=https://outline.xxxxxxxx.com
PORT=3000

# Optional. If using a Cloudfront distribution or similar the origin server
# should be set to the same as URL.
CDN_URL=https://outline.xxxxxxxx.com

# enforce (auto redirect to) https in production, (optional) default is true.
# set to false if your SSL is terminated at a loadbalancer, for example
FORCE_HTTPS=false

ENABLE_UPDATES=false
DEBUG=cache,presenters,events,emails,mailer,utils,multiplayer,server,services

# AWS credentials (optional in development)
AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxxxxcxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
AWS_REGION=us-east-1
#AWS_S3_UPLOAD_BUCKET_URL=minio://minio:9000
AWS_S3_UPLOAD_BUCKET_URL=https://outline.xxxxxxxx.com/minio-db
AWS_S3_UPLOAD_BUCKET_NAME=bucket
AWS_S3_UPLOAD_MAX_SIZE=26214400
AWS_S3_FORCE_PATH_STYLE=true
# uploaded s3 objects permission level, default is private
# set to "public-read" to allow public access
AWS_S3_ACL=private

# Emails configuration (optional)
SMTP_HOST=xxxx
SMTP_PORT=xxxx
SMTP_USERNAME=xxxx
SMTP_PASSWORD=xxxx
SMTP_FROM_EMAIL=xxxx
SMTP_REPLY_EMAIL=xxxx

# Custom logo that displays on the authentication screen, scaled to height: 60px
TEAM_LOGO=xxxx

# See translate.getoutline.com for a list of available language codes and their
# percentage translated.
DEFAULT_LANGUAGE=en_US
HTTP_PORT=3000
PGSSLMODE=disable
```

/etc/nginx/sites-enabled/outline.xxxxxxxx.com:
```
server {
  server_name outline.xxxxxxxx.com;
  client_max_body_size 100M;
  proxy_buffering off;

  location / {
     client_body_buffer_size 100M;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_set_header Host $http_host;
     proxy_connect_timeout 3000;
     proxy_set_header Upgrade $http_upgrade;
     proxy_set_header Connection "upgrade";
     add_header Service-Worker-Allowed /;
     proxy_redirect off;
     proxy_pass http://127.0.0.1:8082;
  }

  location ~* "/minio-db(.*)$" {
     client_body_buffer_size 100M;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
     proxy_set_header X-Forwarded-Proto $scheme;
     proxy_set_header Host $http_host;
     proxy_connect_timeout 3000;
     proxy_http_version 1.1;
     proxy_set_header Connection "";
     chunked_transfer_encoding off;
     proxy_pass "http://127.0.0.1:8083$1";
  }
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/outline.xxxxxxxx.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/outline.xxxxxxxx.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = outline.xxxxxxxx.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot
  server_name outline.xxxxxxxx.com;
  listen 80;
    return 404; # managed by Certbot
}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser: Firefox
 - Version: 99.0 Ubuntu .deb package

**What I have tried so far**
Using `location /minio-db/` and `proxy_pass http://localhost:8083/` instead regex but I could not upload any images through Outline even with minio instance accessible by browser.
