### ISSUE TITLE
Outline 0.64.0 breaks local Postgres and Redis URLs

### ISSUE THREAD

**Issue by Nikas36** [outline/outline#3574]
I was using the following compose file until now to self-host outline:

```yaml
version: '3.9'

services:
    outline:
        image: outlinewiki/outline
        container_name: outline
        restart: unless-stopped
        command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
        environment:
            - SECRET_KEY=${OUTLINE_SECRET_KEY}
            - UTILS_SECRET=${OUTLINE_UTILS_SECRET}
            - DATABASE_URL=postgres://outline:outline@outline_db:5432/outline
            - DATABASE_URL_TEST=postgres://outline:outline@outline_db:5432/outline-test
            - PGSSLMODE=disable
            - REDIS_URL=redis://outline_broker:6379
            - URL=${OUTLINE_URL}
            - PORT=${OUTLINE_PORT}
            - FORCE_HTTPS=false
            - ENABLE_UPDATES=true
            - [redacted AWS, OIDC, SMTP vars]
        depends_on:
            - outline_db
            - outline_broker
        networks:
            - outline
            - proxy

    outline_db:
        image: postgres
        container_name: outline_db
        restart: unless-stopped
        environment:
            - POSTGRES_USER=outline
            - POSTGRES_PASSWORD=outline
            - POSTGRES_DB=outline
        volumes:
            - /home/nick/configs/documents/outline/db:/var/lib/postgresql/data
        networks:
            - outline
        user: 1000:1000

    outline_broker:
        image: redis
        container_name: outline_broker
        restart: unless-stopped
        networks:
            - outline

    outline_s3:
        image: minio/minio
        container_name: outline_s3
        restart: unless-stopped
        command: "minio server /data"
        environment:
            - MINIO_ROOT_USER=${MINIO_ID}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET}
            - MINIO_BROWSER=off
        volumes:
            - /home/nick/configs/documents/outline/s3:/data
        networks:
            - outline
            - proxy
        user: 1000:1000

    outline_s3_init:
        image: minio/mc
        container_name: outline_s3_init
        entrypoint: >
            /bin/sh -c "
            until (/usr/bin/mc config host add minio http://outline_s3:9000 ${MINIO_ID} ${MINIO_SECRET}) do
                echo 'Waiting for minio...' && sleep 1;
            done;
            /usr/bin/mc mb minio/outline;
            /usr/bin/mc policy set download minio/outline;
            exit 0;
            "
        networks:
            - outline
        depends_on:
            - outline_s3

networks:
    outline:
        name: outline
    proxy:
        external: true
        name: proxy
```

On 0.63.0 Outline would initialize normally but after updating to 0.64.0 with Watchtower I get the following error:

```
yarn run v1.22.18
$ sequelize db:migrate --env production-ssl-disabled

Sequelize CLI [Node: 16.14.2, CLI: 6.3.0, ORM: 6.9.0]

Loaded configuration file "server/config/database.json".
Using environment "production-ssl-disabled".
No migrations were executed, database schema was already up to date.
Done in 0.48s.
yarn run v1.22.18
$ node ./build/server/index.js
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"level":"warn","message":"Environment configuration is invalid, please check the following:\n\n"}
{"level":"warn","message":"- DATABASE_URL must be an URL address"}
{"level":"warn","message":"- REDIS_URL must be an URL address"}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Is there something wrong with my configuration or is this an actual bug?

**Outline:**
- Install: self-hosted
- Version: 0.64.0

**Desktop (please complete the following information):**
 - OS: Arch Linux (Docker)
