### ISSUE TITLE
Deleting a document does not remove attachments

### ISSUE THREAD

**Issue by ToshY** [outline/outline#4132]
_A clear and concise description of what the bug is._

Removing a (published) document does not remove the attachments within from database and storage.

**To Reproduce**
1. Create a new document.
2. Add image to it.
3. Publish the document.
4. Delete the document.
5. Image is still in `attachments` table _and_ still in storage (Minio)

**Expected behavior**
The attachment(s) in a document get deleted from database as well as storage.

**Screenshots**

_Minio_
![image](https://user-images.githubusercontent.com/31921460/190497734-6119d728-09e7-44cc-9282-41ec29b5870d.png)

**Logs**
On moment of deletion

```txt
outline-outline-1          | 2022-09-15T19:44:23.901344019Z {"label":"http","level":"info","message":"  <-- POST /api/documents.delete"}
outline-outline-1          | 2022-09-15T19:44:24.171970385Z {"label":"http","level":"info","message":"  --> POST /api/documents.delete 200 271ms 39b"}
outline-outline-1          | 2022-09-15T19:44:24.175012598Z {"name":"documents.delete","modelId":null,"attempt":0,"label":"worker","level":"info","message":"Processing documents.delete"}
outline-outline-1          | 2022-09-15T19:44:24.176988434Z {"name":"documents.delete","modelId":null,"label":"worker","level":"info","message":"BacklinksProcessor running documents.delete"}
outline-outline-1          | 2022-09-15T19:44:24.182852204Z {"name":"documents.delete","modelId":null,"label":"worker","level":"info","message":"WebhookProcessor running documents.delete"}
outline-outline-1          | 2022-09-15T19:44:24.244002168Z {"userId":"0220013c-a67f-4487-ac55-6a1c4fa0aa85","label":"hocuspocus","level":"info","message":"Closed connection to \"document.514bfe7b-bd74-413e-9a7e-67983b2d20ea\""}
outline-outline-1          | 2022-09-15T19:44:24.245147892Z {"label":"database","level":"info","message":"Persisting 514bfe7b-bd74-413e-9a7e-67983b2d20ea"}
outline-outline-1          | 2022-09-15T19:44:24.293494823Z {"label":"http","level":"info","message":"  <-- POST /api/documents.info"}
outline-outline-1          | 2022-09-15T19:44:24.357756108Z {"label":"http","level":"info","message":"  --> POST /api/documents.info 200 61ms 814b"}
outline-outline-1          | 2022-09-15T19:44:24.357778576Z {"label":"http","level":"info","message":"  <-- POST /api/collections.info"}
outline-outline-1          | 2022-09-15T19:44:24.382570788Z {"label":"http","level":"info","message":"  --> POST /api/collections.info 200 26ms 683b"}
outline-outline-1          | 2022-09-15T19:44:24.389105979Z {"label":"http","level":"info","message":"  <-- POST /api/pins.list"}
outline-outline-1          | 2022-09-15T19:44:24.425419553Z {"label":"http","level":"info","message":"  --> POST /api/pins.list 200 37ms 156b"}
outline-outline-1          | 2022-09-15T19:44:24.426435574Z {"label":"http","level":"info","message":"  <-- POST /api/documents.list"}
outline-outline-1          | 2022-09-15T19:44:24.498907095Z {"label":"http","level":"info","message":"  --> POST /api/documents.list 200 72ms 3.31kb"}
```

Document ID `514bfe7b-bd74-413e-9a7e-67983b2d20ea` still available in `attachments` table after "deletion"

```
-[ RECORD 24 ]-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
id          | f94615d1-1a5d-4213-aa84-bb37d23faf10
teamId      | 7bb1c9eb-d835-40d6-a1c8-f6f45f373bf1
userId      | 0220013c-a67f-4487-ac55-6a1c4fa0aa85
documentId  | 514bfe7b-bd74-413e-9a7e-67983b2d20ea
key         | uploads/0220013c-a67f-4487-ac55-6a1c4fa0aa85/b3dc295b-4409-4088-aa05-571abceca6b9/openvideo.png
contentType | image/png
size        | 1254469
acl         | private
createdAt   | 2022-09-15 19:42:48.165+00
updatedAt   | 2022-09-15 19:42:48.165+0
```

**Outline (please complete the following information):**
- Install: docker compose
- Version: v0.66.0

#### Outline docker-compose.yml
```yaml
version: '3.9'

services:
  outline:
    image: outlinewiki/outline:${OUTLINE_IMAGE_VERSION}
    command: sh -c "yarn sequelize:migrate --env=$$PRODUCTION_SSL_DISABLED && yarn start --env=$$PRODUCTION_SSL_DISABLED"
    environment:
      DEBUG: http
      NODE_ENV: ${OUTLINE_NODE_ENV}
      PRODUCTION_SSL_DISABLED: ${OUTLINE_PRODUCTION_SSL_DISABLED}
      SECRET_KEY: ${OUTLINE_SECRET_KEY}
      UTILS_SECRET: ${OUTLINE_UTILS_SECRET}
      OIDC_CLIENT_ID: ${OUTLINE_OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OUTLINE_OIDC_CLIENT_SECRET}
      OIDC_AUTH_URI: ${OUTLINE_OIDC_AUTH_URI}
      OIDC_TOKEN_URI: ${OUTLINE_OIDC_TOKEN_URI}
      OIDC_USERINFO_URI: ${OUTLINE_OIDC_USERINFO_URI}
      OIDC_USERNAME_CLAIM: ${OUTLINE_OIDC_USERNAME_CLAIM:-email}
      OIDC_DISPLAY_NAME: ${OUTLINE_OIDC_DISPLAY_NAME}
      OIDC_SCOPES: ${OUTLINE_OIDC_SCOPES:-email}
      DATABASE_URL: ${OUTLINE_DATABASE_URL}
      DATABASE_URL_TEST: ${OUTLINE_DATABASE_URL_TEST}
      DATABASE_CONNECTION_POOL_MIN: ${OUTLINE_DATABASE_CONNECTION_POOL_MIN}
      DATABASE_CONNECTION_POOL_MAX: ${OUTLINE_DATABASE_CONNECTION_POOL_MAX}
      PGSSLMODE: ${OUTLINE_PGSSLMODE}
      REDIS_URL: ${OUTLINE_REDIS_URL}
      URL: ${OUTLINE_URL}
      COLLABORATION_URL: ${OUTLINE_COLLABORATION_URL}
      AWS_ACCESS_KEY_ID: ${OUTLINE_AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${OUTLINE_AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${OUTLINE_AWS_S3_REGION}
      AWS_S3_UPLOAD_BUCKET_URL: ${OUTLINE_AWS_S3_UPLOAD_BUCKET_URL}
      AWS_S3_UPLOAD_BUCKET_NAME: ${OUTLINE_AWS_S3_UPLOAD_BUCKET_NAME}
      AWS_S3_UPLOAD_MAX_SIZE: ${OUTLINE_AWS_S3_UPLOAD_MAX_SIZE}
      AWS_S3_FORCE_PATH_STYLE: ${OUTLINE_AWS_S3_FORCE_PATH_STYLE}
      AWS_S3_ACL: ${OUTLINE_AWS_S3_ACL}
      FORCE_HTTPS: ${OUTLINE_FORCE_HTTPS}
      ENABLE_UPDATES: ${OUTLINE_ENABLE_UPDATES}
      WEB_CONCURRENCY: ${OUTLINE_WEB_CONCURRENCY}
      MAXIMUM_IMPORT_SIZE: ${OUTLINE_MAXIMUM_IMPORT_SIZE}
      DEFAULT_LANGUAGE: ${OUTLINE_DEFAULT_LANGUAGE}
      RATE_LIMITER_ENABLED: ${OUTLINE_RATE_LIMITER_ENABLED}
      RATE_LIMITER_REQUESTS: ${OUTLINE_RATE_LIMITER_REQUESTS}
      RATE_LIMITER_DURATION_WINDOW: ${OUTLINE_RATE_LIMITER_DURATION_WINDOW}
    depends_on:
      - postgres
      - redis
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.outline.tls: true
      traefik.http.routers.outline.entrypoints: websecure
      traefik.http.routers.outline.rule: Host(`docs.${APP_DOMAIN}`, `www.docs.${APP_DOMAIN}`)
      traefik.http.routers.outline.service: outline
      traefik.http.services.outline.loadbalancer.server.port: 3000
    networks:
      - proxy
      - outline
```

Outline (relevant) variables
```
OUTLINE_NODE_ENV="production"
OUTLINE_PRODUCTION_SSL_DISABLED="production-ssl-disabled"
OUTLINE_SECRET_KEY="<redacted>"
OUTLINE_UTILS_SECRET="<redacted>"
OUTLINE_URL="https://docs.${APP_DOMAIN}"
OUTLINE_COLLABORATION_URL=""
OUTLINE_AWS_ACCESS_KEY_ID="<redacted>" # minio root user
OUTLINE_AWS_SECRET_ACCESS_KEY="<redacted>" # minio root password
OUTLINE_AWS_S3_REGION="local"
OUTLINE_AWS_S3_UPLOAD_BUCKET_NAME="outline"
OUTLINE_AWS_S3_UPLOAD_BUCKET_URL="https://s3.${APP_DOMAIN}"
OUTLINE_AWS_S3_UPLOAD_MAX_SIZE="26214400"
OUTLINE_AWS_S3_FORCE_PATH_STYLE="true"
OUTLINE_AWS_S3_ACL="private"
OUTLINE_FORCE_HTTPS="true"
OUTLINE_ENABLE_UPDATES="true"
OUTLINE_WEB_CONCURRENCY="1"
OUTLINE_MAXIMUM_IMPORT_SIZE="5120000"
OUTLINE_DEFAULT_LANGUAGE="en_US"
OUTLINE_RATE_LIMITER_ENABLED="true"
OUTLINE_RATE_LIMITER_REQUESTS="1000"
OUTLINE_RATE_LIMITER_DURATION_WINDOW="60"
```

#### Minio docker-compose.yml

```yaml
version: '3.9'

services:
  minio:
    image: minio/minio:${MINIO_IMAGE_VERSION} #RELEASE.2022-09-01T23-53-36Z
    command: server /data --address :9010 --console-address :9011
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BROWSER_REDIRECT_URL: https://storage.${APP_DOMAIN}
    volumes:
      - minio:/data
    labels:
      traefik.enable: true
      traefik.docker.network: proxy
      traefik.http.routers.minio-console.tls: true
      traefik.http.routers.minio-console.entrypoints: websecure
      traefik.http.routers.minio-console.rule: Host(`storage.${APP_DOMAIN}`, `www.storage.${APP_DOMAIN}`)
      traefik.http.routers.minio-console.service: minio-console
      traefik.http.services.minio-console.loadbalancer.server.port: 9011
      traefik.http.routers.minio.tls: true
      traefik.http.routers.minio.entrypoints: websecure
      traefik.http.routers.minio.rule: Host(`s3.${APP_DOMAIN}`, `www.s3.${APP_DOMAIN}`)
      traefik.http.routers.minio.service: minio
      traefik.http.services.minio.loadbalancer.server.port: 9010
    networks:
      - minio
      - proxy
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 105.0.5195.102
