### ISSUE TITLE
OIDC authentication failed with Authelia for self-hosted

### ISSUE THREAD

**Issue by catfishlty** [outline/outline#4546]
Hi~
The problem is that I just can't login to `outline` with `Authelia OIDC`, but `gitea` works successfully with it, so I think the problem can be found in `outline` side.
I'm pretty sure that `DNS` is setting correctly and no connections issue between containers. And all subdomains are served by `nginx-proxy-manager` with wildcard self-signed SSL cert by `mkcert`.

Base on the error message in outline container, the error message is not enough for me to solve the problems.
```
ERR Error during authentication | error=Failed to obtain access token stack=InternalOAuthError: Failed to obtain access token
    at OAuth2Strategy._createOAuthError (/opt/outline/node_modules/passport-oauth2/lib/strategy.js:423:17)
    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:177:45
    at /opt/outline/node_modules/oauth/lib/oauth2.js:191:18
    at ClientRequest.<anonymous> (/opt/outline/node_modules/oauth/lib/oauth2.js:162:5)
    at ClientRequest.emit (node:events:526:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Outline Docker Compose Definitions
```yml
version: "3"
services:
  outline:
    image: outlinewiki/outline
    domainname: outline.internal
    ports:
      - "3000:3000"
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    environment:
      NODE_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      UTILS_SECRET: ${UTILS_SECRET}
      DATABASE_URL: postgres://outline_service:${POSTGRES_PASSWORD}@postgres.outline.internal:5432/outline
      DATABASE_URL_TEST: postgres://outline_service:${POSTGRES_PASSWORD}@postgres.outline.internal:5432/outline-test
      PGSSLMODE: disable
      URL: https://outline.mydomain.com
      PORT: 3000
      REDIS_URL: redis://redis.outline.internal:6379
      AWS_ACCESS_KEY_ID: outline_service
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
      AWS_REGION: us-east-1
      AWS_S3_ACCELERATE_URL:
      AWS_S3_UPLOAD_BUCKET_URL: http://minio.outline.internal:9000
      AWS_S3_UPLOAD_BUCKET_NAME: outline
      AWS_S3_UPLOAD_MAX_SIZE: 26214400
      AWS_S3_FORCE_PATH_STYLE: "true"
      AWS_S3_ACL: private
      DEFAULT_LANGUAGE: en_US
      FORCE_HTTPS: "true"
      OIDC_CLIENT_ID: outline
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_AUTH_URI: https://auth.mydomain.com/api/oidc/authorization
      OIDC_TOKEN_URI: https://auth.mydomain.com/api/oidc/token
      OIDC_USERINFO_URI: https://auth.mydomain.com/api/oidc/userinfo
      OIDC_USERNAME_CLAIM: preferred_username
      OIDC_DISPLAY_NAME: Authelia
      OIDC_SCOPES: "openid offline_access profile email"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      local_net:
        aliases:
          - "outline.internal"
      outline_net:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /root/data/outline/redis/config/redis.conf:/redis.conf
      - /root/data/outline/redis/data:/data
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      outline_net:
        aliases:
          - "redis.outline.internal"
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /root/data/outline/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: outline_service
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: outline
    networks:
      outline_net:
        aliases:
          - "postgres.outline.internal"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    command: server /data --console-address ":9001" --address ":9000"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MINIO_ACCESS_KEY: outline_service
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      outline_net:
        aliases:
          - "minio.outline.internal"
networks:
  local_net:
    external: true
  outline_net:
    external: false
```

### OIDC Configuration in Authelia
```yml
...
    clients:
      - id: outline
        description: Outline
        secret: ${OIDC_CLIENT_SECRET}
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://outline.mydomain.com/auth/oidc.callback
        scopes:
          - openid
          - offline_access
          - profile
          - email
        userinfo_signing_algorithm: none
...
```

**To Reproduce**
1. Go to 'outline.mydomain.com'
2. Click on 'Use Authelia to login (Translations maybe not correct)', redirect to `authelia` page
3. Then click on `Accept`

**Expected behavior**
Login to `Outline` and see the home page of `Outline`

**Screenshots**
![1670312807](https://user-images.githubusercontent.com/12734411/205851682-2b3af48d-f48d-4ad3-9002-ea4fb3cf2ad4.png)

**Outline (please complete the following information):**
- Install: self hosted by docker-compose
- Version: `sha256:31d5119b4296366c70a2d377cb9caa59f287cc7cd88f00127e9141228d53e4d6`

**Desktop (please complete the following information):**
 - OS: Docker CE in WSL2 in Windows 10
 - Browser: Chrome
 - Version: Docker version 20.10.21,docker-compose version 1.17.1
