### ISSUE TITLE
Installed Outline Wiki; A few days later: FATAL Password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by Tagette** [outline/outline#4739]
Hello, I recently installed outline wiki v0.67.1 using docker compose and at first it was working. A few days later

### The Problem
```
outline2-postgres-1         | 2023-01-19 03:53:08.967 UTC [1111] FATAL:  password authentication failed for user "postgres"
outline2-postgres-1         | 2023-01-19 03:53:08.967 UTC [1111] DETAIL:  Role "postgres" does not exist.
outline2-postgres-1         |   Connection matched pg_hba.conf line 100: "host all all all scram-sha-256"
```

These errors spam my docker logs and the service no longer works with a 503 error.

### Details
My docker compose looks like this:
```yaml
version: "3"
services:

  storage_startup:
    image: minio/mc:RELEASE.2023-01-11T03-14-16Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio http://minio:9000 secret secret2
      /usr/bin/mc mb minio/outline-bucket;
      /usr/bin/mc anonymous set download minio/outline-bucket;
      exit 0;
      "

  outline:
    image: outlinewiki/outline:0.67.1
    command: sh -c "yarn sequelize:migrate --env production-ssl-disabled && yarn start"
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - minio

  redis:
    image: redis:7.0.7
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]

  postgres:
    image: postgres:15.1
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - /storage/outline/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'

  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z
    env_file: ./minio.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'minio server /minio_root'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /storage/outline/file_data:/data
      - /storage/outline/files:/minio_root
```
Here is some entries from docker.env:
```
DATABASE_URL=postgres://user:pass@postgres:5432/outline
DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
# Uncomment this to disable SSL for connecting to Postgres
PGSSLMODE=disable

URL=https://wiki.mydomain.com
PORT=3000

# The default interface language. See translate.getoutline.com for a list of
# available language codes and their rough percentage translated.
DEFAULT_LANGUAGE=en_US

# Optionally enable rate limiter at application web server
RATE_LIMITER_ENABLED=true

# Configure default throttling parameters for rate limiter
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

Everything is run on the same machine in docker. Ports 3000 and 9000 are open in the firewall.
(I found I had to open port 9000 to get minio to work. Maybe someone knows a better way?)

### My Question
Does anyone know why postgres would stop working all of a sudden? Why is it complaining about the postgres user when the user is supposed to be "user"? Thanks.
