### ISSUE TITLE
Authentication error (self-signed certificate)

### ISSUE THREAD

**Issue by ZarKyo** [outline/outline#5563]
Hi ! I have an error when I try to authenticate myself because of the self-signed certificate even if I put `NODE_TLS_REJECT_UNAUTHORIZED="0"` like specified in the documentation.

**Screenshots**

![image](https://github.com/outline/outline/assets/57832781/4d9fef45-318e-4565-8e77-902efb6d95b7)

**Outline:**
- Install:  self-hosted (docker)
- Version: last version

Outline docker logs :

```
ERR ERR ERR ERR Error during authentication | ERR ERR ERR ERR Error during authentication | error=self-signed certificate ERR ERR ERR ERR Error during authentication | ERR ERR ERR ERR Error during authentication | error=self-signed certificate stack=Error: self-signed certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12)
```
 A part of my docker-compose.yml : 

```yml
  outline:
    image: outlinewiki/outline:latest
    user: root
    restart: always
    container_name: outline
    command: sh -c "yarn start --env=production-ssl-disabled"
    depends_on:
      - outline_postgres
      - outline_redis
      - outline_minio
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED="0"
      [...]
```
