### ISSUE TITLE
Duplicated document links in navigation and collection history

### ISSUE THREAD

**Issue by almereyda** [outline/outline#5948]
There are a few documents in our instance, which appear multiple times in listings, such as the navigation sidebar, and in the document list of a collection.

**To Reproduce**
1. Create a document
2. Change its title
3. Choose to publish it
4. See it multiple times in the sidebar and in the list

**Expected behavior**
Any document is only listed once.

**Screenshots**

The documents called *Untitled*, *Mondeggi* and *Digitales Verrotten* appear multiple times here and there. Note the browser status bar indicating the same link destination when hovering the individual instances.

<details><summary>Screenshots</summary>
<p>

![grafik](https://github.com/outline/outline/assets/1645308/f0b2cb28-8a78-48d9-bdc7-9daabc1b49be)
![grafik](https://github.com/outline/outline/assets/1645308/363365d1-72f7-4356-9485-8aa73b94b96f)
![Bildschirmfoto vom 2023-10-06 00-24-52](https://github.com/outline/outline/assets/1645308/b41806a2-7d65-41f7-8072-f643aa992c80)
![Bildschirmfoto vom 2023-10-06 00-21-44](https://github.com/outline/outline/assets/1645308/884b2d9c-5144-434f-8cef-ce863580f633)
![Bildschirmfoto vom 2023-10-06 00-21-41](https://github.com/outline/outline/assets/1645308/c30b76a8-4a7f-4f75-893f-828c30f216ac)
![Bildschirmfoto vom 2023-10-06 00-21-38](https://github.com/outline/outline/assets/1645308/b90c9efe-9007-4312-831c-c68501950fc7)
![Bildschirmfoto vom 2023-10-06 00-21-36](https://github.com/outline/outline/assets/1645308/29ed2d18-a160-473e-bbff-577f56384347)
![Bildschirmfoto vom 2023-10-06 00-21-32](https://github.com/outline/outline/assets/1645308/199d8865-22ec-417f-b9d4-420c6965fbef)
![Bildschirmfoto vom 2023-10-06 00-21-29](https://github.com/outline/outline/assets/1645308/93047431-7d25-4639-a62e-94c2ab07f80c)
![Bildschirmfoto vom 2023-10-06 00-21-25](https://github.com/outline/outline/assets/1645308/9b9ced8f-b47d-46e0-9bf9-252b363cc48e)
![grafik](https://github.com/outline/outline/assets/1645308/accfaa6d-7da6-4239-9612-6643af848667)

Here we also see

- https://github.com/outline/outline/issues/5949

in effect.

</p>
</details> 

This happened a while after collaborative editing was enabled, and was maybe caused by flaky connections. Yet since this is reproducible across browsers and platforms, it seems there may be some database corruption, which would need to be repaired. Or another regression some place else.

**Outline:**
- Self-hosted version: `0.72.0` 

**Desktop:**
 - OS: Ubuntu 23.10, Fedora 38
 - Browser: Firefox, Chromium
 - Version: a lot

**Mobile:**
 - Device: Samsung Galaxy Tab S6, CAT S62 Pro
 - OS: Android
 - Browser: Firefox, Chrome

This has been nagging me for a long time, and effectively stopped me from rolling out the application broadly. This might have to do with collaborative editing, but then I don't know how real-time versions are materialised to the database or how snapshots are being kept.

**Comment by tommoor** [comment]
@almereyda I'm not sure what's going on with your instance to be honest, we've not had any other reports of this and it's never happened in the cloud-hosted instance to my knowledge

**Comment by ovizii** [comment]
@almereyda happy to hear I am not the only one with the same problem :-)

I have seen the exact same behaviour except this instance is only used by me for note-taking so no collaboration happening. 
I am on version 0.72.2 
Accessing outline behind traefik as reverse proxy.

Outline has been working perfectly fine for a couple of months for me, I had this problem once before, I think it was a few weeks ago, and it disappeared after a docker compose down followed by docker-compose up -d. 
Unfortunately this time it does not help.

OS: win 11
Browser latest Chrome

I clicked the "+" sign next to the collection named docker, edited the new page then published it. Didn't notice an issue. Later on, I wondered why I had a second draft and noticed the draft had the same name as the published page. If I publish the draft, it creates a second page with the same name. If I delete it, the published page also disappears.

Initial situation:
![image](https://github.com/outline/outline/assets/837902/c99d05da-be0d-45b1-909f-ff0a601bbeb9)

if I delete the draft, the draft stays and the published page disappears:
![image](https://github.com/outline/outline/assets/837902/68157175-1ac1-45ee-8d5d-aeba354b65bb)

Once I click the draft it also appears in the sidebar menu:
![image](https://github.com/outline/outline/assets/837902/88bfd7e2-6e2f-439a-9cb3-2f79998bd0a7)

As soon as I hit publish:
![image](https://github.com/outline/outline/assets/837902/b4fd2ba9-35c6-45b7-8075-4f4e5452d260)


This is very confusing, and the logs do not show any errors. Happy to share, just not sure if there's anything confidential in them, let me know if you like to see them.

The logs show quite a lot of these entries:

`outline           | {"event":{"actorId":"36490d7c-e628-42ea-bc05-16d0a5c9dc67","collectionId":"f025880e-6f1f-4f1b-a209-407244a0c2ec","createdAt":"2023-10-13T12:22:36.413Z","data":null,"documentId":"b58421b1-b1df-47a4-bc80-a605b95bc035","id":"235c7ab4-4491-4802-b8af-b552fe370942","ip":"82.76.153.242","modelId":"b5584af9-0063-4640-aaa6-897a202ce2ce","name":"revisions.create","teamId":"39849d48-6d55-41a5-8af7-c93d913e0039","userId":null},"label":"worker","level":"info","message":"WebhookProcessor running revisions.create"}
`

**Comment by almereyda** [comment]
This data is returned from a call to `collections.documents`, so we could trace back the code path it took from being entered in this seemingly fragile state.

![image](https://github.com/outline/outline/assets/1645308/c0cb0e17-a3fb-4aef-9464-5241556032f3)

Any hints hat how this may be debugged are highly appreciated. If we have some kind of (frontend) profiling mode, I'm also happy to enable this.

Thank you for the excellent reproducer. I was able to witness failing WebSocket connections and failing succeeding API requests:

![image](https://github.com/outline/outline/assets/1645308/e1221b0e-8003-4199-ba2c-ba328dcbdaaa)

It appears the WebSockets connection is flakey, and some expected objects do not exist, yet. Is there some kind of hand over of state from the WebSockets connection to the HTTP API service?

In my reenactment, I've found all of the above, summarising in other words:

- A published document shows in the sidebar. When it is clicked, also its Draft sibling appears, and the document is opened.
- Publishing it again will create a second (published) draft in the collection,   
- Multiple publishes to a collaction will all show in the sidebar, but being shown as drafts in a collection's overview.
- The single draft always remains in the global drafts section, and in the collection's sidebar listing, and it does not have the three-dot menu, and cannot be deleted.

<details><summary>Screenshots</summary>
<p>

![image](https://github.com/outline/outline/assets/1645308/4375d984-c956-4a84-b9d2-809154a63169)

![image](https://github.com/outline/outline/assets/1645308/e7aacc18-d2a2-46fa-b1d4-77ad1b8d077b)

![image](https://github.com/outline/outline/assets/1645308/13c18f72-8a3c-4f75-b02a-ccc200c7ac1b)

![image](https://github.com/outline/outline/assets/1645308/b0b98f31-07de-4a17-8f81-8d2f623b238b)

![Bildschirmfoto vom 2023-10-14 21-54-11](https://github.com/outline/outline/assets/1645308/c86465d1-cf43-41e9-94e4-5fafb6f0d7cb)

![Bildschirmfoto vom 2023-10-14 21-54-08](https://github.com/outline/outline/assets/1645308/b0b6fa22-75b6-4423-b60f-37f3d7048eb8)

</p>
</details> 

It is also Traefik that we use, so I suspect there's some issue with the WebSockets connection, and that's about it.

Outline could fail a little more gracefully, though.

**Comment by ovizii** [comment]
I doubt its traefik, I have a few more apps using websockets behind it. Happy to provide logs or help debugging.

**Comment by almereyda** [comment]
You don't have WebSocket errors and subsequently failing POST requests in your browser console?

I will follow down along that path for a moment, and report back here.

Actually I'm already glad to know, that we're not alone with this edge case over here.

**Comment by tommoor** [comment]
As it seems to be reproducible, the best thing to do is take a screen recording with the inspector open – to show all errors, network requests etc.

**Comment by tommoor** [comment]
FWIW these screenshots all seem like expected behavior, which would mostly rule out websocket issues

**Comment by ovizii** [comment]
Any other tips what to do to sort this out? 
I have two drafts I cannot delete as they keep reappearing, and I can't publish them either without creating duplicates.

Willing to show all my configs and debug given more instructions.

**Comment by tommoor** [comment]
Probably best not to wipe the install.

- Are you still able to reproduce the issue reliably?
- Are you using the standard Postgres database in Docker?

If the bad data persisted after reloading the app then it's definitely not a websockets issue FWIW, we can count that out. I've traced through the code again and it continues to confound – the entire publish operation takes place in a transaction, it should be impossible for the data to be added to the sidebar and _not_ be published.

**Comment by ovizii** [comment]
First of all, sorry to take over this thread, happy to open a new one if we notice it is unrelated to the original poster.

I can still reproduce it. 
After this exporting issue https://github.com/outline/outline/issues/6094 is sorted I'd make a complete export and after that I am happy to try anything you like with this instance. 


<details><summary>For now, here is my docker-compose</summary>

```
version: "2.4"

services:

  outline-redis:
    image: redis:7-alpine
    container_name: outline-redis
    hostname: outline-redis
    restart: "no"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    cpus: 1
    mem_limit: 512M
    networks:
      - outline

  outline-postgres:
    image: postgres:13-alpine
    hostname: outline-postgres
    container_name: outline-postgres
    restart: "no"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=outline
      - POSTGRES_DB=outline
    volumes:
      - ./postgres:/var/lib/postgresql/data:Z
#    healthcheck:
#      test: ["CMD", "pg_isready"]
#      interval: 30s
#      timeout: 20s
#      retries: 3
    cpus: 1
    mem_limit: 1G
    networks:
      - outline


  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    hostname: outline
    user: root
    restart: "no"
    command: sh -c "yarn db:migrate --env=production-ssl-disabled && yarn start --env=production-ssl-disabled"
    volumes:
      - ./outline:/var/lib/outline/data
    environment:
      - PGSSLMODE=disable
      - NODE_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - UTILS_SECRET=${UTILS_SECRET}
      - DATABASE_URL=postgres://outline:${POSTGRES_PASSWORD}@outline-postgres:5432/outline
      - REDIS_URL=redis://outline-redis:6379
      - URL=https://wiki.domain.tld
      - PORT=3000
      - FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=eu-de-mil
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_UPLOAD_BUCKET_URL=https://s3.domain.tld
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_FORCE_PATH_STYLE=true
      - AWS_S3_ACL=private
      - AWS_S3_ACCELERATE_URL=
      - FORCE_HTTPS=false
      - SMTP_HOST=10.10.10.10
      - SMTP_PORT=25
      - SMTP_FROM_EMAIL=Outline <ovizii+outline@domain.tld>
      - SMTP_REPLY_EMAIL=Outline <ovizii+outline@domain.tld>
      - SMTP_SECURE=false
      - SMTP_USERNAME=
      - SMTP_PASSWORD
      - ALLOWED_DOMAINS=mydomain.tld
      - WEB_CONCURRENCY=2
      - RATE_LIMITER_ENABLED=true
      - RATE_LIMITER_DURATION_WINDOW=60
      - RATE_LIMITER_REQUESTS=1000
    depends_on:
      - outline-postgres
      - outline-redis
    cpus: 1
    mem_limit: 1G
    networks:
      - outline
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.outline.tls=true"
      - "traefik.http.routers.outline.entrypoints=websecure"
      - "traefik.http.routers.outline.middlewares=secHeaders@file"
      - "traefik.http.routers.outline.rule=Host(`wiki.domain.tld`)"
      - "traefik.http.routers.outline.service=outline"
      - "traefik.http.services.outline.loadbalancer.server.port=3000"

networks:
    traefik:
        external: true
        name: traefik
    outline:
        external: true
        name: outline


```
</details>
