### ISSUE TITLE
OIDC: Login page fails when hosted on subdomain of subdomain 

### ISSUE THREAD

**Issue by jwillp** [outline/outline#5961]
This might be a misconfiguration on my part but I am trying to selfhost outline on a subdomain of a subdomain, something like:
`outline.subdomain.mydomain.com`
Unfortunately I am welcomed with:
`TypeError: Failed to construct 'URL': Invalid URL`

Looking at the stack trace:
```
react-dom.production.min.js:216  TypeError: Failed to construct 'URL': Invalid URL
    at useRedirectHref (AuthenticationProvider.tsx:28:15)
    at AuthenticationProvider (AuthenticationProvider.tsx:79:16)
    at Ch (react-dom.production.min.js:157:137)
    at Bo (react-dom.production.min.js:267:460)
    at bk (react-dom.production.min.js:250:347)
    at ak (react-dom.production.min.js:250:278)
    at Tj (react-dom.production.min.js:250:128)
    at Lj (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at e.unstable_runWithPriority (scheduler.production.min.js:18:343)
```
Which points to the following line:
```
const url = new URL(env.URL);
```

**To Reproduce**
1. Install outline and setup OIDC:
```
environment:
  # other env vars  omitted for brevity
  URL: outline.subdomain.mydomain.com
  PORT: 3000
  OIDC_CLIENT_ID: "outline"
  OIDC_CLIENT_SECRET: "client-secret"
  OIDC_AUTH_URI: "https://auth.subdomain.mydomain.com/api/oidc/authorization"
  OIDC_TOKEN_URI: "https://auth.subdomain.mydomain.com/api/oidc/token"
  OIDC_USERINFO_URI: "https://auth.subdomain.mydomain.com/api/oidc/userinfo"
 ```
2. Go to outline.subdomain.mydomain.com
3. See error

**Expected behavior**
No error, and the ability to login using my OIDC Authentication Provider.

**Outline:**
- Install: self hosted using docker
- Version: outlinewiki/outline@sha256:bb5e42acbbb972572015bc6db448b2c508456a5ade2bc4281bdc3b3e07b0f616

**Desktop:**
 - OS: Ubuntu 22.04.2 LTS
