### ISSUE TITLE
Impossible to install a fresh self-hosted Outline

### ISSUE THREAD

**Issue by BenjaminMorvan** [outline/outline#6121]
Hello, I followed [the installation guide](https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t) on the website and when I migrate the database with `docker-compose run --rm outline yarn db:migrate --env=production-ssl-disabled`, the following error appears: 

```
........
== 20230621004649-add-include-attachments-file-operation: migrating =======
== 20230621004649-add-include-attachments-file-operation: migrated (0.005s)

== 20230720002422-add-insights-control: migrating =======
== 20230720002422-add-insights-control: migrated (0.005s)

== 20230723231806-fix-file-operation-constraints: migrating =======
== 20230723231806-fix-file-operation-constraints: migrated (0.010s)

== 20230815063830-add-emoji-to-revisions: migrating =======
== 20230815063830-add-emoji-to-revisions: migrated (0.005s)

== 20230815063834-migrate-emoji-in-document-title: migrating =======
undefined:1
True
^

SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at Environment.toBoolean (/opt/outline/build/server/env.js:460:27)
    at Environment.initializer (/opt/outline/build/server/env.js:607:17)
    at _initializerDefineProperty (/opt/outline/build/server/env.js:15:305)
    at new Environment (/opt/outline/build/server/env.js:182:5)
    at Object.<anonymous> (/opt/outline/build/server/env.js:919:13)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)

Node.js v18.18.1

ERROR: Command failed: node /opt/outline/build/server/scripts/20230815063834-migrate-emoji-in-document-title.js

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: 1
```

**To Reproduce**

docker-compose.yml : 
```
version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.72.2
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'outline'

  https-portal:
    image: steveltn/https-portal
    env_file: ./docker.env
    ports:
      - '80:80'
      - '443:443'
    links:
      - outline
    restart: always
    volumes:
      - https-portal-data:/var/lib/https-portal
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      DOMAINS: 'doc.outline.mycomp -> http://outline:3000'
      STAGE: 'production'
      WEBSOCKET: 'true'
      CLIENT_MAX_BODY_SIZE: '0'

volumes:
  https-portal-data:
  storage-data:
  database-data:
```

docker.env : 

```
NODE_ENV=production
SECRET_KEY=mysecretkey
UTILS_SECRET=myutilskey
DATABASE_URL=postgres://postgres:password@postgres/outline
DATABASE_URL_TEST=postgres://postgres:password@postgres/outline-test
DATABASE_CONNECTION_POOL_MIN=1
DATABASE_CONNECTION_POOL_MAX=3
REDIS_URL=redis://redis:6379
URL=http://doc.outline.mycomp
PORT=3000
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
FILE_STORAGE_UPLOAD_MAX_SIZE=26214400
GOOGLE_CLIENT_ID=google_client_id
GOOGLE_CLIENT_SECRET=google_client_secret
ENABLE_UPDATES=true
WEB_CONCURRENCY=3
MAXIMUM_IMPORT_SIZE=5120000
DEBUG=http
LOG_LEVEL=info
SMTP_HOST=smtp_host
SMTP_PORT=587
SMTP_USERNAME=smtp_username
SMTP_PASSWORD=smtp_password
SMTP_FROM_EMAIL=smtp_from_email
SMTP_REPLY_EMAIL=smtp_reply_email
SMTP_TLS_CIPHERS=TLSv1.2
SMTP_SECURE=true
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

- Docker version 24.0.7
- Docker version 24.0.7
- Debian 12 (same problem on Debian 11)
