### ISSUE TITLE
Multiple Workspaces with Docker & OpenID

### ISSUE THREAD

**Issue by melvin-suter** [outline/outline#6200]
On a self-hosted instance of outline we added a OpenID IdP.
I logged in first, a second user after me. All worked fine. When the 3rd user logged in, it created a second workspace.
If he looks under members, it showes me as the admin. I can see the 2nd workspace in the dropdown, but if I click on it I still land in the original one. We all login with the same email tld from the same IdP.

Logs have no errors in them (except SMTP, which is a firewall issue atm).

**To Reproduce**
1. Deploy Outline
2. Setup OpenID
3. Login

**Expected behavior**
We should all end up in the same workspace.

**Screenshots**
<img width="175" alt="image" src="https://github.com/outline/outline/assets/44713851/e5148deb-fd4f-4df3-ad97-e27a41ce3681">

**Outline:**
- Install: self hosted
- Version: 0.73.1

**Deployment**

I deployed it on kubernetes with these environment variables:

```
  NODE_ENV: production  
  SECRET_KEY: KEY
  UTILS_SECRET: KEY

  # Database
  DATABASE_URL: postgres://outline:PW@postgres:5432/outline
  PGSSLMODE: disable
  POSTGRES_USER: outline
  POSTGRES_PASSWORD: PW
  POSTGRES_DB: outline

  # Redis
  REDIS_URL: redis://redis:6379

  # App Settings
  URL: https://outline.example.local
  PORT: "3000"
  FORCE_HTTPS: "false"
  ENABLE_UPDATES: "false"
  # translate.getoutline.com
  DEFAULT_LANGUAGE: en_US

  # Storage
  FILE_STORAGE: local
  FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
  FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"


  # Tunables
  WEB_CONCURRENCY: "1"
  MAXIMUM_IMPORT_SIZE: "5120000"
  # error, warn, info, http, verbose, debug and silly
  LOG_LEVEL: warn
  RATE_LIMITER_ENABLED: "false"

  # Mail
  SMTP_HOST: mail.example.local
  SMTP_PORT: "25"
  # SMTP_USERNAME: 
  # SMTP_PASSWORD: 
  SMTP_FROM_EMAIL: no-reply@example.local
  SMTP_REPLY_EMAIL: no-reply@example.local
  SMTP_SECURE: "false"

  # Auth
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  OIDC_CLIENT_ID: client-id
  OIDC_CLIENT_SECRET: "client-secret"
  OIDC_AUTH_URI: "https://openid.example.local/realms/mybuehl/protocol/openid-connect/auth"
  OIDC_TOKEN_URI: "https://openid.example.local/realms/mybuehl/protocol/openid-connect/token"
  OIDC_USERINFO_URI: "https://openid.example.local/realms/mybuehl/protocol/openid-connect/userinfo"
  OIDC_USERNAME_CLAIM: preferred_username
  OIDC_DISPLAY_NAME: OpenID
  OIDC_SCOPES: openid profile email
  ALLOWED_DOMAINS: example.local
```

Redis 7 and Postgres 16 standard deployment.
The outline container is deployed like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline-web
  labels:
    stack: outline
    app: web
    instance: itwiki
spec:
  selector:
    matchLabels:
      stack: outline
      app: web
      instance: itwiki
  template:
    metadata:
      labels:
        stack: outline
        app: web
        instance: itwiki
    spec:
      volumes:
      - name: pvc-outline-storage
        persistentVolumeClaim:
          claimName: pvc-outline-storage
      containers:
        - imagePullPolicy: Always
          name: container-0
          image: outlinewiki/outline:0.73.1
          envFrom:
          - configMapRef:
              name: itwiki-outline-config
          ports:
          - name: http
            protocol: TCP
            containerPort: 3000
          volumeMounts:
          - mountPath: /var/lib/outline/data
            name: pvc-outline-storage
      restartPolicy: Always
  replicas: 1
```

Hope anyone can shed some light on this issue. We really want  to use and support outline.
This kinda is a deal-breaker.
