### ISSUE TITLE
This version of Outline cannot start until a data migration is complete.

### ISSUE THREAD

**Issue by purashy** [outline/outline#6237]
**To Reproduce**
1. Get latest pull (v0.73.1)
2. create `docker-compose.yaml` + `docker.env`
3. `docker compose up + db:create + db:migrate`
4. login, works.
5. restart/pull down the container and start it again.
6. see following message: 

```shell
WRN WRN WRN WRN 
This version of Outline cannot start until a data migration is complete.
Backup your database, run the database migrations and the following script:
(Note: script run needed only when upgrading to any version between 0.54.0 and 0.61.1, including both)

$ node ./build/server/scripts/20210226232041-migrate-authentication.js
 ```

**Expected behavior**
1. Produce step 1 to 5 from the above.
2. once container is restarted, everything should work.

**Outline:**
- **Install:** self hosted
- **Version:** v0.73.1 - 2c870f0

**Desktop:**
 - **OS:** windows
 - **Browser:** chrome
 - **Version:** 117.0.5938.157

Basically in short, I got the latest pull (specifically version 0.73.1), works fine at first. but as soon as I restart the docker container it gives the error mentioned above.

**Docker-compose.yaml:**

```yaml
version: "3.2"
services:

  outline:
    image: docker.getoutline.com/outlinewiki/outline:0.73.1
    container_name: outline
    env_file: ./docker.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - storage

  storage:
    image: minio/minio
    container_name: outline-minio
    env_file: ./docker.env
    ports:
      - "9000:9000"
    entrypoint: sh
    command: -c 'minio server'
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  redis:
    image: redis
    container_name: outline-redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    container_name: outline-postgres
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'outline'
```

**Docker.env:**

```
# –––––––––––––––– REQUIRED ––––––––––––––––
 
NODE_ENV=production
SECRET_KEY=xxx
UTILS_SECRET=xxx
DATABASE_URL=postgres://xxx:xxx@IP/postgres:5432/outline
DATABASE_URL_TEST=postgres://xxx:xxx@IP/postgres:5432/outline-test
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
PGSSLMODE=disable
REDIS_URL=redis://redis:6379
URL=https://outline.domain.com
PORT=3000
COLLABORATION_URL=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_REGION=local
AWS_S3_ACCELERATE_URL=
AWS_S3_UPLOAD_BUCKET_URL=http://minio:9000
AWS_S3_UPLOAD_BUCKET_NAME=outline
FILE_STORAGE_UPLOAD_MAX_SIZE=5242880000
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
AWS_S3_FORCE_PATH_STYLE=true
AWS_S3_ACL=private
 
# –––––––––––––– AUTHENTICATION ––––––––––––––

FORCE_HTTPS=false
URL=https://outline.domain.com
 
# –––––––––––––––– OPTIONAL ––––––––––––––––

SSL_KEY=
SSL_CERT=
CDN_URL=
ENABLE_UPDATES=false
WEB_CONCURRENCY=1
MAXIMUM_IMPORT_SIZE=52428800
DEBUG=http
LOG_LEVEL=info
SMTP_NAME=gmail.com
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=xxx@gmail.com
SMTP_PASSWORD=xxx
SMTP_FROM_EMAIL=xxx@gmail.com
SMTP_REPLY_EMAIL=xxx@gmail.com
SMTP_TLS_CIPHERS=TLS_AES_256_GCM_SHA384
SMTP_SECURE=false
DEFAULT_LANGUAGE=en_US
RATE_LIMITER_ENABLED=true
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

Found #1981 which is from 2021 and #4934 which leads to discussion [with a marked answer](https://github.com/outline/outline/discussions/4935#discussioncomment-5120710). But I have no clue how to do this.

Thank you in advance.
