### ISSUE TITLE
Unable to change profile avatar and import data from Notion

### ISSUE THREAD

**Issue by enmanuelmoreira** [outline/outline#6333]
I am getting the following error when I tried to change the profile avatar:

```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
{"label":"lifecycle","level":"info","message":"Listening on http://localhost:8080 / https://notes.domain.com"}
{"attempt":0,"event":{"actorId":"4d690ec7-4889-441e-9132-8324063a90d3","collectionId":null,"createdAt":"2023-12-30T15:20:57.488Z","data":{"name":"avatar.jpg"},"documentId":null,"id":"f1937b1b-0b5b-47f4-8365-191672a9e29a","ip":"192.168.x.x","modelId":"c5d867a7-dd76-4043-87ad-aba086844f9f","name":"attachments.create","teamId":"719e2d5e-9ba5-4467-8d25-1e5f25014c79","userId":null},"label":"worker","level":"info","message":"Processing attachments.create"}
{"event":{"actorId":"4d690ec7-4889-441e-9132-8324063a90d3","collectionId":null,"createdAt":"2023-12-30T15:20:57.488Z","data":{"name":"avatar.jpg"},"documentId":null,"id":"f1937b1b-0b5b-47f4-8365-191672a9e29a","ip":"192.168.x.x","modelId":"c5d867a7-dd76-4043-87ad-aba086844f9f","name":"attachments.create","teamId":"719e2d5e-9ba5-4467-8d25-1e5f25014c79","userId":null},"label":"worker","level":"info","message":"WebhookProcessor running attachments.create"}
```

**Comment by tommoor** [comment]
I didn't see any error in the logs you submitted? This is probably a configuration problem.

**Comment by enmanuelmoreira** [comment]
Any other method to obtain detailed logs?

My env vars:

```yaml
              LOG_LEVEL: verbose
              TIME_ZONE: America/Santiago
              PGSSLMODE: disable
              URL: "https://notes.domain.com"
              PORT: &port 8080
              WEB_CONCURRENCY: 10
              REDIS_URL: ioredis://eyJkYiI6MTUsInNlbnRpbmVscyI6W3siaG9zdCI6InJlZGlzLW5vZGUtMC5yZWRpcy1oZWFkbGVzcy5kYXRhYmFzZXMuc3ZjLmNsdXN0ZXIubG9jYWwiLCJwb3J0IjoyNjM3OX0seyJob3N0IjoicmVkaXMtbm9kZS0xLnJlZGlzLWhlYWRsZXNzLmRhdGFiYXNlcy5zdmMuY2x1c3Rlci5sb2NhbCIsInBvcnQiOjI2Mzc5fSx7Imhvc3QiOiJyZWRpcy1ub2RlLTIucmVkaXMtaGVhZGxlc3MuZGF0YWJhc2VzLnN2Yy5jbHVzdGVyLmxvY2FsIiwicG9ydCI6MjYzNzl9XSwibmFtZSI6InJlZGlzLW1hc3RlciJ9
              AWS_REGION: us-east-1
              AWS_S3_ACL: private
              AWS_S3_FORCE_PATH_STYLE: "true"
              AWS_S3_UPLOAD_BUCKET_NAME: outline
              AWS_S3_UPLOAD_BUCKET_URL: "https://s3.domain.com"
              ENABLE_UPDATES: "false"
              FILE_STORAGE_UPLOAD_MAX_SIZE: "26214400"
              OIDC_DISPLAY_NAME: Authentik
              OIDC_AUTH_URI: "https://sso.domain.com/application/o/authorize/"
              OIDC_TOKEN_URI: "https://sso.domain.com/application/o/token/"
              OIDC_USERINFO_URI: "https://sso.domain.com/application/o/userinfo/"
              OIDC_USERNAME_CLAIM: preferred_username
              OIDC_SCOPES: openid profile email
```

Secrets:

```yaml
        # App
        SECRET_KEY: "{{ .OUTLINE_SECRET_KEY }}"
        UTILS_SECRET: "{{ .OUTLINE_UTILS_SECRET }}"
        # Minio
        AWS_ACCESS_KEY_ID: "{{ .OUTLINE_AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .OUTLINE_AWS_SECRET_ACCESS_KEY }}"
        # Database URL
        DATABASE_URL: "postgres://{{ .OUTLINE_DATABASE_USER }}:{{ .OUTLINE_DATABASE_PASS }}@{{ .POSTGRES_HOST }}/{{ .OUTLINE_DATABASE_NAME }}"
        # OIDC
        OIDC_CLIENT_ID: "{{ .OUTLINE_OAUTH_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .OUTLINE_OAUTH_CLIENT_SECRET }}"
        # Postgres Init
        INIT_POSTGRES_HOST: "{{ .POSTGRES_HOST }}"
        INIT_POSTGRES_DBNAME: "{{ .OUTLINE_DATABASE_NAME }}"
        INIT_POSTGRES_USER: "{{ .OUTLINE_DATABASE_USER }}"
        INIT_POSTGRES_PASS: "{{ .OUTLINE_DATABASE_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # SMTP
        SMTP_HOST: "{{ .SMTP_SERVER }}"
        SMTP_PORT: "{{ .SMTP_PORT }}"
        SMTP_USERNAME: "{{ .SMTP_USERNAME }}"
        SMTP_PASSWORD: "{{ .SMTP_PASSWORD }}"
        SMTP_FROM_EMAIL: "{{ .SMTP_USERNAME }}"
        SMTP_REPLY_EMAIL: "{{ .SMTP_USERNAME }}"
```
