### ISSUE TITLE
Ensure code is built by default in production

### ISSUE THREAD

**Issue by enzolutions** [outline/outline#666]
Hi maintainers.
I am trying Outline in a self-hosted platform and works like a charm, but when I tried to use yarn start as the application suggest to run a production environment the application stop working and I just end **Not Found** in all paths

This is the section outline of my **docker-compose.yml** file

```
outline:
    image: outline:v001
    command: yarn start
    build:
      context: .
      dockerfile: Dockerfile
      args:
        pull: 1
    ports:
      - "80:3000"
    volumes:
      - .:/opt/outline
    depends_on:
      - postgres
      - redis
```
