### ISSUE TITLE
Image upload no longer works

### ISSUE THREAD

**Issue by accesstechnology-mike** [outline/outline#6671]
v 0.75.2

I transitioned from Minio in the last upgrade without losing previously stored data; however, any new image uploads fail.

Copy-paste image, or upload via /image fails with "! Upload Failed" notification.

Console states:

```
 POST https://domain.co.uk/api/files.create 500 (Internal Server Error)

Error: Upload failed
    at uploadFile (files.ts:71:11)
    at async Editor.tsx:123:12
```

My docker-compose.yml for reference:

```
version: "3"
services:
  outline_redis:
    image: redis
    container_name: outline_redis
    restart: unless-stopped
    networks:
      - outline-internal
    command: redis-server --save 60 1 --loglevel warning
    sysctls:
      - net.core.somaxconn=1024
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    volumes:
      - redis-data:/redis-data

  outline_postgres:
    image: postgres:13
    container_name: outline_postgres
    env_file: ./.env
    restart: unless-stopped
    networks:
      - outline-internal
    volumes:
      - ./db:/var/lib/postgresql/data

  outline:
    image: outlinewiki/outline
    container_name: outline
#   set this command instead to initialize/upgrade the db
#   command: sh -c "sleep 5 && yarn sequelize:migrate --env=production-ssl-disabled"
#   command: yarn db:migrate --env=production-ssl-disabled
    command: yarn start --env=production-ssl-disabled
    depends_on:
      - outline_postgres
      - outline_redis
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/outline/data
    labels:
      caddy: ${URL}
      caddy.reverse_proxy: "{{upstreams 4443}}"
      caddy.reverse_proxy.1_header_up_0: "X-Forwarded-Proto {scheme}"
      caddy.reverse_proxy.2_header_up_1: "X-Forwarded-Host {host}"
    networks:
      - outline-internal
      - caddy

networks:
  outline-internal:
  caddy:
    external: true

volumes:
  redis-data: {}
```
