### ISSUE TITLE
AWS CRT binary not present in any of the following locations

### ISSUE THREAD

**Issue by MichaelSasser** [outline/outline#7033]
Unable to start container after upgrading to `outlinewiki/outline:0.77.0`.

**To Reproduce**
1. Update from 0.76.1 to 0.77.0
2. Container is restarting
3. Check logs

**Expected behavior**
Application starts

**Logs**
```log
Node.js v20.14.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.22
$ node ./build/server/index.js
/opt/outline/node_modules/aws-crt/dist/native/binding.js:109
    throw new Error("AWS CRT binary not present in any of the following locations:\n\t" + search_paths.join('\n\t'));
    ^

Error: AWS CRT binary not present in any of the following locations:
        /opt/outline/node_modules/aws-crt/dist/bin/linux-arm64-musl/aws-crt-nodejs.node
    at Object.<anonymous> (/opt/outline/node_modules/aws-crt/dist/native/binding.js:109:11)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/opt/outline/node_modules/aws-crt/dist/native/auth.js:20:35)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
    at require (node:internal/modules/helpers:179:18)
```
**Environment Variables**

(Those are added as environment variables on deployment.)

```yaml
  #
  # Application secrets
  #
  SECRET_KEY: "{{ secret_outline_secret_key }}" # openssl rand -hex 32
  UTILS_SECRET: "{{ secret_outline_utils_secret }}" # openssl rand -hex 32

  #
  # Postgres
  #
  DATABASE_URL: "postgres://{{ scratch_outline_service_name }}:{{ secret_outline_db_password }}@postgres:5432/{{ scratch_outline_service_name }}"
  DATABASE_URL_TEST: "postgres://{{ scratch_outline_service_name }}-test:{{ secret_outline_db_test_password }}@postgres:5432/{{ scratch_outline_service_name }}-test"
  DATABASE_CONNECTION_POOL_MIN: 1
  DATABASE_CONNECTION_POOL_MAX: 5
  PGSSLMODE: disable

  #
  # Redis
  #
  REDIS_URL: redis://redis-outline:6379/0?pool_size=10&idle_timeout=60s

  #
  # Auth
  #
  OIDC_CLIENT_ID: mpkb
  OIDC_CLIENT_SECRET: "{{ secret_outline_oidc_client_secret }}"
  OIDC_AUTH_URI: "{{ global_vars.oidc.mp.authorization_endpoint }}"
  OIDC_TOKEN_URI: "{{ global_vars.oidc.mp.token_endpoint }}"
  OIDC_USERINFO_URI: "{{ global_vars.oidc.mp.userinfo_endpoint }}"
  OIDC_LOGOUT_URI: "{{ global_vars.oidc.mp.end_session_endpoint }}"
  OIDC_USERNAME_CLAIM: "{{ global_vars.oidc.mp.username_claim }}"
  OIDC_DISPLAY_NAME: "{{ global_vars.oidc.mp.displayname }}"
  OIDC_SCOPES: "{{ global_vars.oidc.mp.default_scopes | join(' ') }}"
  # OIDC_DISABLE_REDIRECT: "false"

  #
  # Object Storage
  #
  FILE_STORAGE: s3
  FILE_STORAGE_UPLOAD_MAX_SIZE: 26214400
  AWS_REGION: "{{ global_vars.s3.default.region }}"
  AWS_S3_UPLOAD_BUCKET_NAME: outline-mp
  AWS_S3_UPLOAD_BUCKET_URL: "https://{{ global_vars.s3.default.host }}"
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_ACCESS_KEY_ID: "{{ secret_outline_s3_access_key }}"
  AWS_SECRET_ACCESS_KEY: "{{ secret_outline_s3_secret_key }}"

  # Workaround:
  # MAXIMUM_IMPORT_SIZE: 26214400 #  5120000
  FILE_STORAGE_IMPORT_MAX_SIZE: 26214400
  # FILE_STORAGE_UPLOAD_MAX_SIZE: 5120000

  #
  # Mail
  #
  SMTP_HOST: "{{ global_vars.mail_mp.host }}"
  SMTP_PORT: "{{ global_vars.mail_mp.smtp.port }}"
  SMTP_USERNAME: "{{ global_vars.mail_mp.no_reply_user }}"
  SMTP_PASSWORD: "{{ secret_outline_smtp_password }}"
  SMTP_FROM_EMAIL: "{{ global_vars.mail_mp.no_reply_sender }}"

  #
  # Rate Limit
  #
  RATE_LIMITER_ENABLED: "true"
  RATE_LIMITER_DURATION_WINDOW: 60
  RATE_LIMITER_REQUESTS: 1000
```

**Outline (please complete the following information):**
- Install: self-hosted; Docker version 26.1.4, build 5650f9b
- Version: `outlinewiki/outline:0.77.0`

**Desktop (please complete the following information):**
(not applicable)

**Mobile (please complete the following information):**
(not applicable)
