### ISSUE TITLE
Switching from 0.77.0 to 0.77.1 /.2 /.3 causes Node JS error

### ISSUE THREAD

**Issue by jensschaerer** [outline/outline#7242]
I use the default docker setup and tried to update from 0.77.0 to 0.77.3 using just a docker-compose pull. I get some Node JS errors and I can't deal with them. Same for 0.77.1 and 0.77.2. 0.77.0 works great and there was no problem at all.

Check this error log, hopefully it helps:

```
  #  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xcba1e7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd39a6e node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd39b4c node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc6e2f7  [node]
 5: 0xc6f854 node::Start(int, char**) [node]
 6: 0x7fdacd2b824a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fdacd2b8305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xbc430e _start [node]
Aborted (core dumped)

  #  node[7]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
  #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

 1: 0xcba1e7 node::Assert(node::AssertionInfo const&) [node]
 2: 0xd39a6e node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
 3: 0xd39b4c node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
 4: 0xc6e2f7  [node]
 5: 0xc6f854 node::Start(int, char**) [node]
 6: 0x7fde15e3c24a  [/lib/x86_64-linux-gnu/libc.so.6]
 7: 0x7fde15e3c305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0xbc430e _start [node]
Aborted (core dumped)
```

**Comment by tommoor** [comment]
What OS and CPU architecture are you running on?

**Comment by jensschaerer** [comment]
I'm on Ubuntu 20.04.4 LTS in a virtualized environment with two x64 cores. nothing special at all, no ARM

**Comment by jensschaerer** [comment]
additional info, see my docker-compose.yml for reference, maybe there is something wrong?

```yaml
version: "3"
services:

  outline:
    restart: always
    image: outlinewiki/outline:0.77.0
    env_file: ./docker.env
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ./storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    restart: always
    image: redis:bullseye
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    restart: always
    image: postgres:14
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: <PASS>
      POSTGRES_DB: outline
```
