### ISSUE TITLE
Update Data Directory Permissions

### ISSUE THREAD

**Issue by QYG2297248353** [outline/outline#7454]
```yml
services:
  outline:
    image: outlinewiki/outline:0.78.0
    volumes:
      - ${OUTLINE_ROOT_PATH}/data:/var/lib/outline/data
```

When it comes to uploading files, a status code without permission 500 appears 
I want, when the app starts, by calling the sh script, to modify the directory permissions. 
Or the initiated identity user specifies it himself

```
CMD ["yarn", "start"]
```

The user runs the program as root via user: 0

```yml
services:
  outline:
    image: outlinewiki/outline:0.78.0
    user: 0
```

Or via environment variables 
`UID GID`
 
Use docker-compose to mount to the data volume regardless of permission issues. 
But mounting to the host directory will cause permission problems.

Refer to 
Modify mounted directory permissions by executing a script at startup

```
CMD ["/usr/local/bin/docker-entrypoint.sh"]
```

```
chmod -R 777 $TARGET_DIR
exec xxx
```
