### ISSUE TITLE
Missing SMTP config

### ISSUE THREAD

**Issue by ludenticus** [outline/outline#8125]
I'm trying to setup a self-hosted Outline server with docker. I have a reverse proxy with apache2 running on a Ubuntu 24.04 LTS host. So far, however, I haven't been able to make it work the SMTP.

Mi `compose-docker.yml` is as follows:

```yml
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: Outline_knowledge_base
    restart: always
    environment:
      - DATABASE_URL=postgres://outline:password@db:5432/outline
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=jwtsecret
      - SECRET_KEY=secretkey
      - UTILS_SECRET=utils_pass
      - PGSSLMODE=disable
      - URL=https://outline.mysite.com
      - FORCE_HTTPS=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_NAME=GmailSMTPServer
      - SMTP_USERNAME=user@gmail.com
      - SMTP_PASSWORD=apppass
      - SMTP_FROM=user@gmail.com
      - SMTP_REPLY_EMAIL=user@gmail.com
      - SMTP_SECURE=true
      - SMTP_PORT=587
      - SMTP_TLS_CIPHERS=TLSv1.3
    depends_on:
      - db
      - redis
    networks:
      - outline-net
    ports:
      - "3000:3000"
    volumes:
      - outline-data:/var/lib/outline

  db:
    image: postgres:15
    container_name: outline-db
    restart: always
    environment:
      - POSTGRES_USER=outline
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outline
    ports:
      - "5432:5432"
    networks:
      - outline-net
    volumes:
      - outline-db-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: outline-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - outline-net

networks:
  outline-net:
    external: true

volumes:
  outline-data:
  outline-db-data:
```

Whenever I try to send an invite, the app reports that the email was sent, but it isn't true: the log complains:

```log
Outline_knowledge_base  | {"label":"email","level":"info","message":"Email InviteEmail not sent due to missing SMTP configuration"}
```

If I log in the container with `docker exec -it` and type `openssl s_client -starttls smtp -connect smtp.gmail.com:587`, I can get a valid `235 2.7.0 Accepted` response after `EHLO localhost`, `AUTH LOGIN` and the user and pass in base64. So, Outline is able to connect to the Google smtp server if I type the credentials provided in the `yml` file.

Question is: **What is the missing SMTP config?**
