### ISSUE TITLE
Documentation - Self signed certificates - Mention NODE_EXTRA_CA_CERTS variable

### ISSUE THREAD

**Issue by modcritical** [outline/outline#8147]
The documentation suggests an overly complex solution of extending the container image to add additional trusted certs.

Adding a trusted CA cert is likely necessary if using OIDC and internally hosted IdP, and/or internally hosted SMTP, with an internal PKI. Extending the outline container image adds complexity to deployment and updates, and is not needed because env var NODE_EXTRA_CA_CERTS works as expected out-of-the-box.

**Expected behavior**

Documentation should read something like this:

### Configuration

To have Outline trust your self-signed root certificate, you must bind mount it to the container and inform Node where to find it. For example, in your `docker-compose.yml` file, bind mount the CA certificate file in the `volumes` section:

```
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    ports:
      - "3000:3000"
    volumes:
      - storage-data:/var/lib/outline/data
      - /etc/ssl/myca.crt:/etc/ssl/myca.crt:ro
    depends_on:
      - postgres
      - redis
```

Then, add `NODE_EXTRA_CA_CERTS` to your docker.env file, with the path to the CA cert:

```
...
NODE_EXTRA_CA_CERTS=/etc/ssl/myca.crt
...
```

If you are running the container on an SELinux enabled system, you must either enable access to certificates in `/etc/ssl`, or store the certificate in a location specifically for container data and ensure it has type label `container_file_t`. To enable access to `/etc/ssl` certificates, ensure the certificate file has the type label `cert_t` and enable sebool `container_read_certs`.

**Outline (please complete the following information):**

Documentation at https://docs.getoutline.com/s/hosting/doc/self-signed-certificates-IcLsCLsjje
