### ISSUE TITLE
Self Hosted: File become 0B after upload

### ISSUE THREAD

**Issue by lightumcc** [outline/outline#8176]
I found some issues with uploading the file. If I upload pictures or small attachments, it works fine. But if I upload some large documents, let's say 20M, the file will upload "successfully", and show the correct file size. But if I tried to download this file, 502 error showed. And if I try to use terminal to check this file (by using the `sig` value when I download), it will show the file take 0B of space.

I'm pretty sure the configs of the max file size limit in both Nginx and Cloudflare are correct.

**To Reproduce**
1. Go to a document
2. Try to use `File Attachment` to upload a file
3. Download this file, see 502 error from Cloudflare and both Nginx

**Expected behavior**
Download successfully

**Screenshots**
<img width="902" alt="image" src="https://github.com/user-attachments/assets/a2a87a8d-9048-443d-a609-9ef0c2850c4b" />
<img width="1306" alt="image" src="https://github.com/user-attachments/assets/46617ff1-ebf0-4649-a003-2094e0dffc17" />
<img width="1827" alt="image" src="https://github.com/user-attachments/assets/50b3d9c2-c7fe-4628-ba6d-fbb1bbfdee78" />

> I've already tried to do this in Google Chrome

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.81.1

**Env File about File Storage**
```
FILE_STORAGE=local
FILE_STORAGE_LOCAL_ROOT_DIR=/var/lib/outline/data
FILE_STORAGE_UPLOAD_MAX_SIZE=31457280
```

**Docker Compose File**
```
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    restart: unless-stopped
    env_file: ./docker.env
    ports:
      - "2777:3000"
    volumes:
      - /root/data/docker_data/outline/storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    restart: unless-stopped
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - /root/data/docker_data/outline/redis.conf:/redis.conf
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    image: postgres
    restart: unless-stopped
    env_file: ./docker.env
    ports:
      - "5432:5432"
    volumes:
      - /root/data/docker_data/outline/database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "SOME DATABASE", "-U", "SOME USER"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      POSTGRES_USER: 'SOME USER'
      POSTGRES_PASSWORD: 'SOME PASSWORD'
      POSTGRES_DB: 'SOME DATABASE'
```

**Log of container (DEBUG Level)**
```
INF INF INF INF   <-- POST /api/attachments.create | INF INF INF INF   <-- POST /api/attachments.create | label=http
DBG DBG DBG DBG Jessie Zhu changed document.521e9192-a4ad-4c73-924c-c9c2e60f104f | DBG DBG DBG DBG Jessie Zhu changed document.521e9192-a4ad-4c73-924c-c9c2e60f104f | label=multiplayer
INF INF INF INF   --> POST /api/attachments.create 200 98ms 563b | INF INF INF INF   --> POST /api/attachments.create 200 98ms 563b | label=http
INF INF INF INF Processing attachments.create | INF INF INF INF Processing attachments.create | attempt=0 INF INF INF INF Processing attachments.create | INF INF INF INF Processing attachments.create | attempt=0 event={"actorId":"d00a8b54-3e19-46a1-83dd-1dc4be006e70","authType":"app","changes":null,"collectionId":null,"createdAt":"2024-12-31T06:48:51.112Z","data":{"name":"1.pdf"},"documentId":null,"id":"76a8c9e8-9cc9-4ac6-976b-47e388909d0d","ip":"1.1.1.1","modelId":"33bbb599-c799-4ac4-98e1-0d5ec5a83da7","name":"attachments.create","teamId":"f3ade516-9443-437e-9de0-4c4041d18461","userId":null} INF INF INF INF Processing attachments.create | INF INF INF INF Processing attachments.create | attempt=0 INF INF INF INF Processing attachments.create | INF INF INF INF Processing attachments.create | attempt=0 event={"actorId":"d00a8b54-3e19-46a1-83dd-1dc4be006e70","authType":"app","changes":null,"collectionId":null,"createdAt":"2024-12-31T06:48:51.112Z","data":{"name":"1.pdf"},"documentId":null,"id":"76a8c9e8-9cc9-4ac6-976b-47e388909d0d","ip":"1.1.1.1","modelId":"33bbb599-c799-4ac4-98e1-0d5ec5a83da7","name":"attachments.create","teamId":"f3ade516-9443-437e-9de0-4c4041d18461","userId":null} label=worker
INF INF INF INF WebhookProcessor running attachments.create | INF INF INF INF WebhookProcessor running attachments.create | event={"actorId":"d00a8b54-3e19-46a1-83dd-1dc4be006e70","authType":"app","changes":null,"collectionId":null,"createdAt":"2024-12-31T06:48:51.112Z","data":{"name":"1.pdf"},"documentId":null,"id":"76a8c9e8-9cc9-4ac6-976b-47e388909d0d","ip":"1.1.1.1","modelId":"33bbb599-c799-4ac4-98e1-0d5ec5a83da7","name":"attachments.create","teamId":"f3ade516-9443-437e-9de0-4c4041d18461","userId":null} INF INF INF INF WebhookProcessor running attachments.create | INF INF INF INF WebhookProcessor running attachments.create | event={"actorId":"d00a8b54-3e19-46a1-83dd-1dc4be006e70","authType":"app","changes":null,"collectionId":null,"createdAt":"2024-12-31T06:48:51.112Z","data":{"name":"1.pdf"},"documentId":null,"id":"76a8c9e8-9cc9-4ac6-976b-47e388909d0d","ip":"1.1.1.1","modelId":"33bbb599-c799-4ac4-98e1-0d5ec5a83da7","name":"attachments.create","teamId":"f3ade516-9443-437e-9de0-4c4041d18461","userId":null} label=worker
```

**Log of Nginx (Download)**
```
2024/12/31 14:19:58 [error] 1399#0: *253 upstream prematurely closed connection while reading response header from upstream, client: CLIENT IP, server: OUTLINE DOMAIN, request: "GET /api/files.get?sig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ1cGxvYWRzL2QwMGE4YjU0LTNlMTktNDZhMS04M2RkLTFkYzRiZTAwNmU3MC81NDg3NWE3ZC0wYmQ1LTQ1MzItODhiYy05MjdiYWVlODdiNWUvVmlkZW8gVHV0b3JpYWwgb2YgRW5yb2xsIGEgTWFjQm9vay5tcDQiLCJ0eXBlIjoiYXR0YWNobWVudCIsImlhdCI6MTczNTYyNTk4NywiZXhwIjoxNzM1NjI2MDQ3fQ.MKtyNPNhI2rIOKfPFwfjlZMC-Q4BoHuXQ5ZCQRpgLrE HTTP/2.0", upstream: "http://127.0.0.1:2777/api/files.get?sig=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ1cGxvYWRzL2QwMGE4YjU0LTNlMTktNDZhMS04M2RkLTFkYzRiZTAwNmU3MC81NDg3NWE3ZC0wYmQ1LTQ1MzItODhiYy05MjdiYWVlODdiNWUvVmlkZW8gVHV0b3JpYWwgb2YgRW5yb2xsIGEgTWFjQm9vay5tcDQiLCJ0eXBlIjoiYXR0YWNobWVudCIsImlhdCI6MTczNTYyNTk4NywiZXhwIjoxNzM1NjI2MDQ3fQ.MKtyNPNhI2rIOKfPFwfjlZMC-Q4BoHuXQ5ZCQRpgLrE", host: "OUTLINE DOMAIN"
```
