### ISSUE TITLE
OIDC /api/auth.info not forwarded to subdomain

### ISSUE THREAD

**Issue by alfureu** [outline/outline#8202]
So I have a docker stack set up of `traefik` + `authelia` (OICD) +` outline`. All containers are on the same container network `traefik_net`.

Everything is set-up following the guides and official documentations, namely:

- https://www.authelia.com/integration/openid-connect/outline/
- https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t

In traefik I use forward-auth middleware, according to the manuals:

```
    middlewares-authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/authz/forward-auth'
        trustForwardHeader: true
        authResponseHeaders:
          - 'Remote-User'
          - 'Remote-Groups'
          - 'Remote-Email'
          - 'Remote-Name'
 ```

The only difference is that `outline` runs on the main domain `example.com` and not on a subdomain of outline.example.com. Authelia runs on `authelia.example.com` and I can log in via that page. 

**The problem:**

When I load `example.com`, I see the infamous "Login to Outline" page, but no login button, and I see in the browser logs the 401 error for `"POST https://example.com/api/auth.info"`. This is obviously wrong, as I want to have this request to `https://authelia.example.com/api/auth.info`, which is reachable. 

I haven't found where to set the correct forward URL in the documentation, as my `.env` file is:

```
URL=https://example.com
PORT=3000
COLLABORATION_URL=https://example.com

# OIDC SETUP
OIDC_CLIENT_ID=redacted
OIDC_CLIENT_SECRET=redacted
OIDC_AUTH_URI=https://authelia.example.com/api/oidc/authorization
OIDC_TOKEN_URI=https://authelia.example.com/api/oidc/token
OIDC_USERINFO_URI=https://authelia.example.com/api/oidc/userinfo
OIDC_USERNAME_CLAIM=preferred_username
OIDC_DISPLAY_NAME=OpenID
OIDC_SCOPES=openid groups offline_access profile email
```

Anyone with an idea? Many thanks in advance...
