### ISSUE TITLE
Can't start docker image

### ISSUE THREAD

**Issue by shelldandy** [outline/outline#8431]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

Using the provided docker-config from the docs: https://docs.getoutline.com/s/hosting/doc/docker-7pfeLP5a8t

The container can't seem to start and always exits

```
outline        | yarn run v1.22.22
outline        | $ node ./build/server/index.js
outline        | /opt/outline/node_modules/sequelize/lib/sequelize.js:58
outline        |       options.dialect = urlParts.protocol.replace(/:$/, "");
outline        |                                           ^
outline        | 
outline        | TypeError: Cannot read properties of null (reading 'replace')
outline        |     at new Sequelize (/opt/outline/node_modules/sequelize/lib/sequelize.js:58:43)
outline        |     at new Sequelize (/opt/outline/node_modules/sequelize-typescript/dist/sequelize/sequelize/sequelize.js:16:9)
outline        |     at createDatabaseInstance (/opt/outline/build/server/storage/database.js:25:10)
outline        |     at Object.<anonymous> (/opt/outline/build/server/storage/database.js:93:39)
outline        |     at Module._compile (node:internal/modules/cjs/loader:1469:14)
outline        |     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
outline        |     at Module.load (node:internal/modules/cjs/loader:1288:32)
outline        |     at Module._load (node:internal/modules/cjs/loader:1104:12)
outline        |     at Module.require (node:internal/modules/cjs/loader:1311:19)
outline        |     at Hook.Module.require (/opt/outline/node_modules/dd-trace/packages/dd-trace/src/ritm.js:85:33)
outline        |     at require (node:internal/modules/helpers:179:18)
outline        |     at Object.<anonymous> (/opt/outline/build/server/collaboration/PersistenceExtension.js:12:17)
outline        |     at Module._compile (node:internal/modules/cjs/loader:1469:14)
outline        |     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
outline        |     at Module.load (node:internal/modules/cjs/loader:1288:32)
outline        |     at Module._load (node:internal/modules/cjs/loader:1104:12)
outline        | 
outline        | Node.js v20.18.0
outline        | error Command failed with exit code 1.
outline        | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
outline exited with code 1
```

### Expected Behavior

Container starts properly

### Steps To Reproduce

M1 Macbook Pro

```yml
services:
  outline:
    image: docker.getoutline.com/outlinewiki/outline:latest
    container_name: outline
    ports:
      - "3000:3000"
    volumes:
      - ./data/outline:/var/lib/outline/data
    environment:
      - TZ=${TZ}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  redis:
    container_name: outline_redis
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      TZ: ${TZ}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "outline"
    restart: unless-stopped

networks:
  frontend:
    external: true

volumes:
  database:
    driver: local
  redis:
    driver: local
```

### Environment

```markdown
n/a
```
