### ISSUE TITLE
"Image failed to load" after upgrading (0.81.1 > 0.82.0)

### ISSUE THREAD

**Issue by sypion** [outline/outline#8588]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

After upgrading my self-hosted instance of Outline, images that were attached to my documents no longer load properly. 

<img width="738" alt="Image" src="https://github.com/user-attachments/assets/fcdce7d2-b018-4187-98bd-cbb353013ddc" />

### Steps To Reproduce

1. Running in a typical Docker environment.
2. My `.env` file is as follows and hasn't changed since the last version:
```
NODE_ENV=production

# Generate a hex-encoded 32-byte random key. You should use `openssl rand -hex 32`
# in your terminal to generate a random value.
SECRET_KEY=[redacted]

# Generate a unique random key. The format is not important but you could still use
# `openssl rand -hex 32` in your terminal to produce this.
UTILS_SECRET=[redacted]

# For production point these at your databases, in development the default
# should work out of the box.
DATABASE_URL=postgres://outline:[redacted]@localhost:5432/outline
DATABASE_CONNECTION_POOL_MIN=
DATABASE_CONNECTION_POOL_MAX=
# Uncomment this to disable SSL for connecting to Postgres
PGSSLMODE=disable

# For redis you can either specify an ioredis compatible url like this
REDIS_URL=redis://outline-redis:6379
# or alternatively, if you would like to provide additional connection options,
# use a base64 encoded JSON connection option object. Refer to the ioredis documentation
# for a list of available options.
# Example: Use Redis Sentinel for high availability
# {"sentinels":[{"host":"sentinel-0","port":26379},{"host":"sentinel-1","port":26379}],"name":"mymaster"}
# REDIS_URL=ioredis://eyJzZW50aW5lbHMiOlt7Imhvc3QiOiJzZW50aW5lbC0wIiwicG9ydCI6MjYzNzl9LHsiaG9zdCI6InNlbnRpbmVsLTEiLCJwb3J0IjoyNjM3OX1dLCJuYW1lIjoibXltYXN0ZXIifQ==

# URL should point to the fully qualified, publicly accessible URL. If using a
# proxy the port in URL and PORT may be different.
URL=https://outline.domain.org
PORT=3005

# See [documentation](docs/SERVICES.md) on running a separate collaboration
# server, for normal operation this does not need to be set.
COLLABORATION_URL=

# Specify what storage system to use. Possible value is one of "s3" or "local".
# For "local", the avatar images and document attachments will be saved on local disk. 
FILE_STORAGE=local

# If "local" is configured for FILE_STORAGE above, then this sets the parent directory under
# which all attachments/images go. Make sure that the process has permissions to create
# this path and also to write files to it.
FILE_STORAGE_LOCAL_ROOT_DIR=/home/dock/outline/data

# Maximum allowed size for the uploaded attachment.
FILE_STORAGE_UPLOAD_MAX_SIZE=262144000

# Override the maximum size of document imports, generally this should be lower
# than the document attachment maximum size.
FILE_STORAGE_IMPORT_MAX_SIZE=

# Override the maximum size of workspace imports, these can be especially large
# and the files are temporary being automatically deleted after a period of time.
FILE_STORAGE_WORKSPACE_IMPORT_MAX_SIZE=

# To support uploading of images for avatars and document attachments in a distributed 
# architecture an s3-compatible storage can be configured if FILE_STORAGE=s3 above.
#AWS_ACCESS_KEY_ID=get_a_key_from_aws
#AWS_SECRET_ACCESS_KEY=get_the_secret_of_above_key
#AWS_REGION=xx-xxxx-x
#AWS_S3_ACCELERATE_URL=
#AWS_S3_UPLOAD_BUCKET_URL=http://s3:4569
#AWS_S3_UPLOAD_BUCKET_NAME=bucket_name_here
#AWS_S3_FORCE_PATH_STYLE=true
#AWS_S3_ACL=private

# –––––––––––––– AUTHENTICATION ––––––––––––––

# To configure generic OIDC auth, you'll need some kind of identity provider.
# See documentation for whichever IdP you use to acquire the following info:
# Redirect URI is https://<URL>/auth/oidc.callback
OIDC_CLIENT_ID=redacted
OIDC_CLIENT_SECRET=redacted
OIDC_AUTH_URI=redacted
OIDC_TOKEN_URI=redacted
OIDC_USERINFO_URI=redacted
#OIDC_LOGOUT_URI=

# Specify which claims to derive user information from
# Supports any valid JSON path with the JWT payload
OIDC_USERNAME_CLAIM=preferred_username

# Display name for OIDC authentication
OIDC_DISPLAY_NAME=OIDC

# Space separated auth scopes.
OIDC_SCOPES=openid profile email


# –––––––––––––––– OPTIONAL ––––––––––––––––

# Auto-redirect to https in production. The default is true but you may set to
# false if you can be sure that SSL is terminated at an external loadbalancer.
FORCE_HTTPS=true

# Have the installation check for updates by sending anonymized statistics to
# the maintainers
ENABLE_UPDATES=true

# How many processes should be spawned. As a reasonable rule divide your servers
# available memory by 512 for a rough estimate
WEB_CONCURRENCY=1

# You can remove this line if your reverse proxy already logs incoming http
# requests and this ends up being duplicative
DEBUG=http

# Configure lowest severity level for server logs. Should be one of
# error, warn, info, http, verbose, debug and silly
LOG_LEVEL=debug

# To support sending outgoing transactional emails such as "document updated" or
# "you've been invited" you'll need to provide authentication for an SMTP server
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=email@email.com
SMTP_PASSWORD=password
SMTP_FROM_EMAIL=outline@domain.org
SMTP_REPLY_EMAIL=outline@domain.org
SMTP_TLS_CIPHERS=
SMTP_SECURE=true

# The default interface language. See translate.getoutline.com for a list of
# available language codes and their rough percentage translated.
DEFAULT_LANGUAGE=en_US

# Optionally enable rate limiter at application web server
RATE_LIMITER_ENABLED=true

# Configure default throttling parameters for rate limiter
RATE_LIMITER_REQUESTS=1000
RATE_LIMITER_DURATION_WINDOW=60
```

Here are the logs I see in my browser's console:

<img width="1121" alt="Image" src="https://github.com/user-attachments/assets/3205f3f7-b6c7-41ad-ae9b-79132d03a6dc" />

### Environment

```markdown
- Outline: Outline 0.82.0
- Browser: All browsers.
```

### Anything else?

I appreciate any of the support you can give me. My team and I use Outline extensively and we love it!

**Comment by sypion** [comment]
I'd also like to mention that there was an existing issue for this (#8521) but was closed. For the other OPs instance, however, they switched storages when they upgraded. I did not (still using local).

**Comment by tommoor** [comment]
There were no code changes in the file storage plugin between `0.81.1` -> `0.82.0` . What does your docker volume / bind setup look like, how are you persisting these files?

**Comment by sypion** [comment]
Supposedly, files are to be saved in `/home/dock/outline/data/` as depicted in the compose file:
```
services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file: ./docker.env
    user: root
    ports:
      - "3005:3005"
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/outline/data
    depends_on:
      - redis
    networks:
      - outline

  redis:
    image: redis
    container_name: outline-redis
    env_file: ./docker.env
    ports:
      - "6379:6379"
    volumes:
      - type: bind
        source: ./redis.conf
        target: /redis.conf
      - type: bind
        source: ./redis-data
        target: /data
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      - outline

networks:
  outline:
    name: outline
    external: true
```

However, the `/data` folder is empty, even when uploading assets in Outline? Is it just being dumped into Redis? I'm not too sure here.

**Comment by burakince** [comment]
Also, you use `FILE_STORAGE_LOCAL_ROOT_DIR=/home/dock/outline/data` configuration but you bind `/var/lib/outline/data` folder to `./data` folder with the following configuration.

```yaml
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/outline/data
```
